cmd/dexctl/main.go
db/gc.go
db/password.go
db/user.go
pkg/crypto/rand.go
pkg/http/client.go
refresh/repo.go
server/auth_middleware.go
server/http.go
server/register.go
server/server.go
session/manager.go
user/api/api.go
user/password.go

Whenever it makes the code easier to follow, use early return to
avoid else statements.
It's a dirty job, but someone has to do it.

Remove unnecessary else statements

---

Documentation/getting-started.md

A new API key can be generated in an existing Google project
Fixes #123
Signed-off-by: Chris Swan <@cpswan>

Documentation: no need to create a new Google project

---

cmd/dex-worker/main.go

Otherwise, if worker starts without connectors, and then connectors are
added workers have to be restarted to pick up the changes.

cmd/dex-worker: wait 'til connectors are available

---

server/server.go
server/user.go

This change disables the URL fixing behavior or the router associated
with the user management schema. After this commit, URLS routing
to /api/$VERSION/users must target exactly the specified paths. In
addition, `/api/$VERSION/users/` will serve a 404
This change allows users to hit the user create endpoint, which
would previously serve a redirect rather than actually making the
associated change.

server: user management endpoints strictly conform to schema

---

user/api/api.go
user/api/api_test.go

Before, when a call was made with a bad URL, the call returned an error but the user was created anyway.

api: don't create a user if you can't send them an email

---

Godeps/Godeps.json
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3/LICENSE
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3/README.md
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3/encodedword.go
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3/encodedword_test.go
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3/pool.go
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3/pool_go12.go
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3/reader.go
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3/reader_test.go
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3/writer.go
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3/writer_test.go

quotedprintable is part of the standard library in Go 1.5 but is needed in Godeps in earlier versions.

build: vendor quotedprintable to build on Go < 1.5

---

Documentation/getting-started.md

Provides a more accurate walk through of the screens and menus of the Google
Developers Console encountered whilst creating a client ID.
Fixes #125
Signed-off-by: Chris Swan <@cpswan>

Documentation: clearer guidance on creating OAuth 2 client ID

---

build

With `go version go1.5.1 darwin/amd64`, I was getting the following warning twice when building:
```
link: warning: option -X main.version 6970b481f4d8c6b65d72e6bd9000340fa934187b may not work in future releases; use -X main.version=6970b481f4d8c6b65d72e6bd9000340fa934187b
```
This modification adds the "=" sign (as directed) and prevents the warning.

build: add equals sign to avoid link warning when building project

---

db/client.go
db/password.go
db/refresh.go
db/session.go
db/session_key.go
db/user.go

gorp schema errors are a big deal, and probably worth some log information. This PRQ also changes the error protocol of some DB functions to distinguish between nil (which seems like a common thing) and type assertion failures (which are super scary)

db: log schema errors, distinguish them from nil results where needed

---

cmd/dex-worker/main.go
server/config.go
server/http.go
server/http_test.go
server/server.go
server/testutil.go
static/html/login.html

For situations where admins add users.

server,cmd: Add flag for disabling registation

---

Documentation/getting-started.md
cmd/dex-overlord/main.go
contrib/standup-db.sh
integration/admin_api_test.go
server/admin.go

Requests made to admin API must have an `Authorization` header with 128 bytes encoded base64

Protect admin api

---

refresh/repo.go
server/server_test.go

Previously if we use the in-memory backend, it will return a raw
binary token for refresh token. This fixes the case.
Fix #153

refreshtoken: return base64 encoded token for in-memory backend.

---

README.md

great work with dex guys! I remember talking to some of you back a year ago for using Auth0 internally for your products but you had some special requirements and it didn't work out. We are using CoreOS extensibly on our product for code sandboxing (https://medium.com/aws-activate-startup-blog/sandboxing-code-in-the-era-of-containers-294edb3a674) and we love it. 
Since you are listing similar software, I thought adding Auth0 would make sense, here. Writing a post on our blog about chaining dex with Auth0 would be nice as well.

Add auth0 on Similar Software list

---

pkg/http/http.go
server/http.go

Go 1.4+ has https://golang.org/pkg/net/http/#Request.BasicAuth
method for http.Request and it was requested by CoreOS(kelsey) [1]
with the same functionalities. If dex's Go development is being done
in Go 1.4 or later, we should use the standard library.
Thanks!
---
[1] https://codereview.appspot.com/76540043/

server: use standard lib http.Request.BasicAuth

---

build
server/password.go
server/password_test.go
test
user/email/email.go
user/email_verification.go
user/email_verification_test.go
user/password.go
user/password_test.go
user/user.go

This change proposes to unify behavior and source code for token generation between email verification and password reset, in order to make it simpler to add other user-facing, token dependent services to dex.

server: Share token code

---

examples/README.md
static/fixtures/clients.json

I want to enable people to use Dex with Bitly's OAUTH2 proxy. These are some
docs and fixture improvements to make that work really quickly.
See the PR here: https://github.com/bitly/oauth2_proxy/pull/163

Improve docs for the getting started guide for oauth2_proxy

---

server/register.go

need to make sure the scope is present otherwise will be considered an invalid request
fixes #135

server: add scope to newLoginURLFromSession

---

server/config.go
server/email_verification.go
server/http.go
server/invitation.go
server/invitation_test.go
server/password.go
server/password_test.go
server/server.go
server/testutil.go
user/api/api.go
user/email/email.go
user/email/email_test.go
user/email_verification.go
user/invitation.go
user/invitation_test.go
user/manager.go
user/password.go
user/password_test.go
user/user.go

An alternative to https://github.com/coreos/dex/pull/157 - allow newly invited users to simultaneously verify their email addresses and reset their passwords.

New invitation endpoint

---

user/user.go
user/user_test.go

mail.ParseAddress will stop parsing a string once it finds a valid
email address. This means you could give ValidUser an email
address followed by junk and it would mark it valid.
This commit fixes this behavior and adds some more test cases.
Fixes #189

user: fix bug in ValidEmail helper

---

server/register.go
server/register_test.go

Trim spaces when registering emails to address #163.
Also added a basic sanity check to catch invalid emails. Before you could enter an email like "asfddsaf asdf asdf".

registration: trim spaces and sanity check user email from form

---

Documentation/getting-started.md
contrib/standup-db.sh

base64 wraps lines on Linux after 76 characters. Use tr to trim
the newlines in a portable way.

*: trim newlines from base64 command for Linux compatibility

---

Documentation/getting-started.md

In the 'getting started' doc create a user and database for dex to
clarify that the user needs permissions to create databases, but
dex does not.
closes #127

documentation: clarify db permissions in getting started doc

---

build-docker-push
cmd/dex-worker/main.go
examples/emailtester/main.go

Align with RFC2606 for example email addresses, using example.com
in place of coreos.com where appropriate.
Fix #86, supersedes #187

*: use example.com in place of coreos.com

---

admin/api.go
cmd/dex-overlord/main.go
connector/config_repo.go
connector/interface.go
db/connector_config.go
functional/repo/connector_repo_test.go
integration/common_test.go
server/config.go
server/email_verification.go
server/invitation.go
server/password.go
server/register.go
server/server.go
server/testutil.go
server/user.go
test
user/api/api.go
user/api/api_test.go
user/manager/manager.go
user/manager/manager_test.go

Before creating a user, ensure the local connector ID held by the
overlord and worker match the ID of a local connector in the
database.
Fixes #198

api: validate local connector existence before creating user

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/go-oidc/oidc/client.go
Godeps/_workspace/src/github.com/coreos/go-oidc/oidc/provider.go

Update `github.com/coreos/go-oidc/...` to include coreos/go-oidc#27 which fixes a race condition in the OIDC connector when syncing provider configurations.

Godeps: update coreos/go-oidc to include OIDC race condition fixes

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/go-oidc/oidc/provider.go

Correct provider config field "id_token_alg_values_supported" to "id_token_signing_alg_values_supported".
Fixes #212

Godeps: update github.com/coreos/go-oidc/oidc to fix field name

---

server/http_test.go

In #210 a field name in the provider config was corrected. However the old, and incorrect, value was hard coded in the tests. This change updates the test case to hold the correct field name.
There are no other references to the old name in dex or its vendored packages.
Sorry about breaking the tests everybody.

server: fix tests

---

cmd/dex-overlord/main.go
cmd/dex-worker/main.go
db/key.go
db/key_test.go

Passing an empty list to the overlord's --key-secrets flag currently causes an out of range panic. Always check to ensure there's at least one element.
Fixes #130

cmd, db: verify at least one secret is passed to --key-secrets

---

.travis.yml

Moved postgres image from personal account to quay.io/coreos.

*: use coreos postgres image for travis ci

---

cmd/dex-worker/main.go

Reduces the max amount of time between retries when waiting for the database to populate connectors from 1 minute to 8 seconds. 
fixes #177

cmd: reduce backoff max when worker is waiting for connectors

---

server/server.go

This cleans up the code that deals with a user attempting to login through a different connector than they registered with. The only functional change is that `newLoginURLFromSession` is now called with register = false when a user has an existing account.
It fixes weird behavior seen in [this comment](https://github.com/coreos/dex/issues/180#issuecomment-166473092).

server: fix flow when user logs in through wrong connector

---

contrib/k8s/README.md

A fix to get rid of the -t deprecation notice 
`Flag shorthand -t has been deprecated, please use --template instead`

Update k8s README to --template syntax

---

server/http.go
server/register.go
server/register_test.go
server/server.go
server/testutil.go
static/html/register.html

Instead of cryptic message with nowhere to, give them the choice to
login with that account or register.

server: better UX when remote ID already exists

---

pkg/flag/base64.go

```
$ ./bin/dex-overlord --key-secrets 'YWFhYWJiYmJjY2NjZGRkZGVlZWVmZmZmZ2dnZ2hoaGgK'
invalid value "YWFhYWJiYmJjY2NjZGRkZGVlZWVmZmZmZ2dnZ2hoaGgK" for flag -key-secrets: expected 32-byte secret, got 33-byte secret
...
$ ./bin/dex-overlord --key-secrets 'YWFhYWJiYmJjY2NjZGRkZGVlZWVmZmZmZ2dnZ2hoaGg=,fasdfaf'
invalid value "YWFhYWJiYmJjY2NjZGRkZGVlZWVmZmZmZ2dnZ2hoaGg=,fasdfaf" for flag -key-secrets: error decoding string 1: illegal base64 data at input byte 4
...
```

pkg: improve base64 flag error message

---

admin/api_test.go

These tests aren't included in the top level test script so have
unintentionally been ignored and currently don't compile. Until
this is fixed (see #257) add a build tag so tools ignore them.

admin: add build ignore tag to tests that don't compile

---

.travis.yml

Travis has a nicer `deploy` construct which has builtin support for conditioning on branches, language versions, tags, conditions, etc. I think this should work the same for you.
* https://docs.travis-ci.com/user/deployment/script
* https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A
Fixed spacing to consistently use 2 spaces instead of a blend of 1 and 2.

travis: Change from after_success script to travis deploy

---

server/user.go
user/api/api.go

Move client authentication into its own middleware and provide
differentiation between HTTP requests that do not provide
credentials (401) and requests that authenticate as a non-admin
user (403).
Closes #152

*: move user API auth to middleware and fix return status

---

contrib/standup-db.sh

This change is required because otherwise i get ` unknown shorthand flag: 'd'`

Fixed db-url flag in standup-db.sh

---

Documentation/getting-started.md

As was noted in #293 --db-url must take two slashes, not one.

Documentation: fix --db-url flag

---

contrib/standup-db.sh

As discussed in #295 registration was not working because the flag was not set on the worker startup. I also added the emailer config because I had to change the name of this file manually to get it picked up so it would be nice if it just started.

worker start command missing registration and emailer config.

---

admin/api_test.go
test

Fixed code for admin/api_test.go. We have changed the code comparison to error comparison  to use the same coding style as in user/api_test.go
regards

 admin: tests do not compile (Fixes #257)

---

cmd/dex-overlord/main.go
cmd/dex-worker/main.go
cmd/dexctl/command_version.go

Output now looks like
```
$ ./bin/dexctl version
dex version 0.2.3
go version 1.5.3
$ ./bin/dex-worker --version
dex version 0.2.3
go version 1.5.3
$ ./bin/dex-overlord --version
dex version 0.2.3
go version 1.5.3
```
Attempts to mimic rkt's output:
```
$ rkt version
rkt version 0.15.0
appc version 0.7.4
```

cmd: add version to command worker and overlord, print go version

---

README.md

We've seen lot of issues opened recently that require a better place for general discussion than GitHub issues. Because of this, I've gone ahead and created a dex-dev google group.
As a first order of business, we'd like to use that form to coordinate a dex community hangout so we can update and get feedback from those outside of CoreOS on dex's roadmap.
cc @bobbyrullo, @philips, @rsoletob, @adrianlop, @fnordahl

README: add note about roadmap and google group

---

connector/connector_ldap.go

Not all LDAP servers have entryDN available as an attribute. Reading up on
https://tools.ietf.org/html/rfc5020 tells me that entryDN is intended for
making the DN available for attribute value assertions. Thus it is not
mandatory for a LDAP server to make it available as an retrievable
attribute.
The DN is always a part of the entry returned in a search result, just use
it.
Fixes #314

Get DN from entry, not entryDN attribute

---

connector/config_repo_test.go
user/password.go
user/password_test.go

PasswordInfos are marshaled when storing them in the database as
part of the local connector. However, the custom unmarsheler
defined could not unmarshal the standard marshling of this struct.
Add a struct tag to the Password field to correct this.
I'd like to see #334 be the long term fix to this. However for now, this works.
Closes #332 
cc @fnordahl

user: fix password info JSON encoding to survive round trips

---

.travis.yml
functional/db_test.go
functional/dexctl_test.go
functional/ldap_test.go

It's currently very hard to run functional tests because you need
to set both the Postgres and LDAP environment variables or the
init() functions for the various test suites will kill all the
functional tests before they can start.
Use t.Fatal instead of os.Exit in the init().
Closes #318

functional: don't fail if postgres or ldap isn't available

---

db/conn.go
db/conn_test.go

sqlite3 in memory databases do not support concurrent writes. Limit
number of open connections to prevent race conditions.

db: only allow one open connection for in memory databases

---

build
db/client.go
db/conn.go
db/conn_postgres.go
db/conn_sqlite3.go
env
release

Closes #354. Fixes the release script by protecting the sqlite3 import with a cgo tag.

Fix cross compilation

---

integration/user_api_test.go
schema/workerschema/README.md
schema/workerschema/v1-gen.go
schema/workerschema/v1-json.go
schema/workerschema/v1.json
server/user.go
user/api/api.go
user/api/api_test.go

This change solves the User's API problem when you want to create an user that its email hasn't been verified yet but it exist.
At now, you can resend invitation email using endpoint /users/{id}/resend-invitation
Fixes #184

add support for resend an invite email

---

integration/user_api_test.go

#331 was merged after we lowercased all emails in the database (#339). This change fixes the test in #331 to conform to the new standard.

integration: fix email case sensitivity test

---

server/config.go

Static analysis showed we were never using `db.NewHealthChecker`. Seemed like an oversight.
Add the db health checker to the list of server health checks.

server: add db heatlh checker to server checkers

---

server/http.go
server/http_test.go

This commit fix problem with response_type param, which is required according to OIDC spec, when it is missing.
At now, when connector_id url query param is not set, connector view use response_type that client requested instead of default "code".
Fixes #370

Fix response_type missing param

---

Documentation/getting-started.md

It's no longer exists and isn't used anywhere else in the "getting started" guide.
Fixes #365

Documentation: remove reference to DEX_APP_REDIRECTURL

---

connector/config_repo_test.go
connector/connector_local.go
integration/oidc_test.go
server/config.go
server/config_test.go
server/server.go
static/fixtures/connectors.json.sample
static/fixtures/users.json.sample

In --no-db mode, load passwords from the users file instead of the
connectors file. This allows us to remove the password infos field
from the local connector and stop loading them during connector
registration, a case that was causing panics when using a real
database (see #286).
Fixes #286
Closes #340

remove passwordInfos from local connector

---

db/refresh.go
functional/repo/client_repo_test.go
functional/repo/refresh_repo_test.go
integration/user_api_test.go
refresh/repo.go
schema/generator
schema/workerschema/README.md
schema/workerschema/v1-gen.go
schema/workerschema/v1-json.go
schema/workerschema/v1.json
server/config.go
server/server.go
server/user.go
user/api/api.go
user/api/api_test.go

I'm opening this in place of #329 because last time I forced a push for #329 all the inline comments disappeared.
This PR adds API endpoints for listening clients with refresh tokens and revoking refresh tokens. Work needed for #261 (note we've considered splitting the UI work from the API work needed for #261).

add ability to revoke refresh tokens in user API

---

.travis.yml

It's part of the standard tooling and no longer lives in
golang.org/x/tools.
See https://golang.org/cl/20810

*: don't go get vet

---

server/user.go

In #386, the intention was to expose some of this functionality to _ordinary users_. However, [down the road](https://github.com/coreos/dex/pull/386/files#diff-fb49ec733096f07f50a1275c54e5889cR303), `getCreds()` would fail if the user wasn't _admin_:
```go
if !isAdmin {
return api.Creds{}, api.ErrorForbidden
}
```

bugfix: make getCreds work for non-admins

---

db/client.go
db/user.go

When client secrets are not base64 encoded, print an error message
that's not a generic base64 decode error:
client secrets must be base64 decodable. See issue #337.
Please consider replaceing "secret" with "c2VjcmV0"
When a user file is missing a mandatory field print an error message.
Unable to build Server: user elroy-foo is missing email field
For #400

db: print better error messages for invalid input

---

server/config.go
server/config_test.go

In #393 the format of the static user file in --no-db mode changed.
However, the old format loads without error, which has caused
issues for developers with existing user files.
Add an explicit check to ensure the file is not using the old
format. If they are, print a better error message.

server: add more validation to --no-db static file parsing

---

contrib/k8s/dex-overlord.yaml

ConfigMap must be defined before it can be used; moved the ConfigMap definition prior to the dec-overlord container definition in the yams file.

K8S dex-overlord.yaml ordering fix

---

contrib/k8s/dex-overlord.yaml
contrib/k8s/dex-worker.yaml

- Add resource requests for deployments
- Add readiness probe for master
- Use YAML references for easier maintenance/readability

contrib/k8s: YAML brevity via references, minimum resource requests

---

Dockerfile-builder
go-docker

I switched to the official golang image. Not sure if there was a reason to use the dex-builder image?
supersedes #406
fixes #404

use go 1.6.2 for docker go build

---

Documentation/connectors-configuration.md
connector/connector_ldap.go
functional/ldap_test.go
glide.lock
glide.yaml

The initial implementation of the LDAP connector initiates and tears down a connection for each session. Although the creation and tear-down of connections are light weight operations for most LDAP server implementations, it is not hard to imagine that this at some point will become a bottle neck and scaling issue.
This PR addresses this issue by implementing connection pooling for the LDAP connections. The pooled connections are checked for liveliness and kept alive. The number of connections to keep as well as the interval for liveliness checks are configurable.
Fixes #309

connector_ldap: Implement connection pooling for LDAP connections

---

examples/app/main.go

Fixes issue #450.
Added two flags for passing the cert and key files. If both flags are set, the server is started using TLS.
Also added UX to ensure that "--listen" and "--callbackURL" are HTTPS when user provides TLS cert and key.

Added TLS support to the example application

---

client/manager/manager.go
client/manager/manager_test.go
db/client.go
functional/config/config_sample_test.go
functional/repo/refresh_repo_test.go
integration/common_test.go
integration/oidc_test.go
integration/user_api_test.go
server/client_resource_test.go
server/config.go
server/http_test.go
server/server_test.go
server/testutil.go
test
test-functional
user/api/api_test.go

* change generateClientCreds to addClientCreds - more accurate reflection of the API
* add test to make sure that clients in sample file are valid, and that they can be authenticated against (this makes me worry less about screwing up the encoding/hashing of client_secrets)
* in preparation for removing ClientManagerFromClients, fix up a lot of copy-pasta in server tests and use testutil code instead to create fixtures
* finally, remove ClientManagerFromClients, in favor of a similar method in the repo layer

Various client api tweaks

---

cmd/dex-worker/main.go

Right now it is not clear what connector is failing. It will be easier to debug with more specific error message.
Related to #400

#400 Add connector id to the registration error message

---

glide.lock
glide.yaml
vendor/github.com/coreos/go-oidc/oauth2/oauth2.go
vendor/github.com/coreos/go-oidc/oauth2/oauth2_test.go

Update github.com/coreos/go-oidc/ to include coreos/go-oidc#87
which adds support for Azure AD

vendor: update go-oidc to add support for Azure AD

---

cmd/dex-worker/main.go
server/config.go
server/server.go
server/server_test.go
server/testutil_test.go

When specified the "--register-on-first-login" allows users logging in through remote connectors to skip registration. This make a lot of sense for connectors like LDAP, which have their own registration upstream.
Closes #310
This change also renames "server/testutil.go" to "server/testutil_test.go" to ensure it's not used outside of tests.
cc @sym3tri

*: add --enable-automatic-registration flag to worker

---

scope/scope.go

If an empty scope is somehow passed along, it shouldn't be validated
when checking refresh token scope.

scope: don't validate empty scopes

---

.travis.yml
Documentation/connectors-configuration.md
connector/connector_ldap.go
connector/connector_ldap_test.go
connector/connector_local.go
connector/interface.go
connector/login_local.go
functional/ldap_test.go
static/fixtures/connectors.json.sample

The first commit cleans up the LDAP connector a bit. A follow up one will add the groups implementation.
Cleanup includes:
* Remove some unlikely to be used fields to help configurability.
* Combined "serverHost" and "serverPort" into "host"
* Remove "timeout" (just default to 30 seconds).
* Remove "maxIdleConn" will add it back if users feel the need
to control the number of cached connections.
* Remove "trustedEmailProvider" (just always trust).
* Remove "skipCertVerification" you can't make this connector
ingore TLS errors.
* Fix configs that don't search before bind (fixes #481).
* Add more examples to Documentation
* Refactor LDAPPool Acquire() and Put() into a Do() function which
always does the flow correctly.
* Added more comments and renamed some functions.
Edit:
* Moved methods …

Clean up LDAP Connector

---

Documentation/email-configuration.md
cmd/dex-worker/main.go
email/interface.go
email/mailgun.go
email/mailgun_test.go
email/smtp.go
email/smtp_test.go
email/template.go
email/template_test.go
server/config.go
server/password_test.go
server/testutil_test.go
static/fixtures/emailer.json.sample
user/email/email.go
user/email/email_test.go

Still need to test with a full installation.
Closes #389

*: depricate --email-from flag and move to email config files

---

server/config.go
server/testutil_test.go
static/html/ldap-login.html
static/html/local-login.html
static/html/login.html
static/html/register.html
static/html/send-reset-password.html

fixes: #502
WIP
Add a new template function called `absPath` that converts relative
paths to absolute paths based on the issuerURL. The template function
can be used in templates like:
````html
<a href="{{ .MyRelativePath | absPath }}">
````
or simply:
````html
<a href="{{ absPath }}/myrelativepath">
````

backend: add absolute path to template links

---

connector/connector_ldap.go
connector/connector_local.go
connector/connector_oauth2.go
connector/connector_oidc.go
connector/interface.go
server/http_test.go
server/server.go

When Dex uses a non-root issuer URL, it current assumes that all
path prefixes will be trimmed by an upstream proxy (e.g. nginx).
This means that all paths rendered in HTML will be absolute to the
prefix, but the handlers still listen at the root.
Connectors are currently the only component that registers at a
non-root URL. Make this conform with the rest of Dex by having the
server determine the path the connector listens as rather than the
connector itself.
Updates #502
Note that this is part of a larger conversation about what it means
for Dex to be at a non-root URL path. See #521.
@xaka can you test this to ensure it works with your setup?

connector: fix path that connectors listen on

---

server/user.go
user/api/api.go
user/api/api_test.go

closes #530
cc @squat @sym3tri @chancez

user api: accept bearer tokens with multiple audiences

---

Documentation/connectors-configuration.md

Just a small typo fix in the documentation of the connectors.

Fix typo in dexctl parameter

---

server/server.go
server/server_test.go
user/manager/manager.go

When automatically registering a user from an IP that provides
a `DisplayName`, set it on the created user so that JWT we create
contain a meaningful `name` field.
Added new test and ran existing ones.

server: when registering a user, set user name if OIDC identity contains one

---

Documentation/connectors-configuration.md
connector/connector_uaa.go
connector/connector_uaa_test.go
server/http.go

This commit adds support for dex to authenticate users from a
CloudFoundry User Account and Authentication (UAA) Server.
Fixes: #538

connector: add uaa connector

---

Documentation/tls-setup.md
examples/README.md

It was noted in #542 that our examples don't hold valid client secrets for no-db mode.
#337 strikes again.

*: update examples to hold valid client secrets for no-db mode

---

Documentation/getting-started.md

The discovery URL has changed and now ends with /dex. As the scripts
were updated in #525, the documentation was not.
Broken since #521.
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

documentation: fix getting-started

---

db/refresh.go
refresh/repo.go
server/http.go
server/server.go
server/server_test.go

Added refresh token rotation.
Fixes #519

refresh token rotation

---

server/server_test.go

As we've seen on master it's very easy mistakenly make changes that
assume root URL paths. Run server integration tests at a non-root
issuer URL to prevent this.
cc @chancez @sym3tri

dev branch: run server tests at a non-root URL

---

server/cross_client_test.go
server/http.go
server/http_test.go
server/server.go

Closes #553
cc @sym3tri @chancez

server: fix registration redirect for non-root URLs

---

cmd/dex-worker/main.go
integration/user_api_test.go
server/config.go
server/server.go
server/user.go
user/api/api.go
user/api/api_test.go

ClientCredentials flow in basic User operations (createUser, getUser, resendInvitationMail)

---

examples/README.md

* In a9dce1c, the defaults are set to the `.example` paths, except for `emailer.json` which is instead committed into the git repository. So there's no need to duplicate those file in order to start dex-worker.
* The default value for discovery is moved from `/` to `/dex` in #521
* Typo in `client-secret` value.

documentation: multiple fixes in examples README

---

server/templates.go
server/templates_default.go
server/templates_default_gen.go

When compiling the default templates into the source code, use
string literals instead of escaped strings to reduce merge
conflicts.

dev-branch: generate string literals instead of escaped strings

---

server/cross_client_test.go
server/http.go
server/server.go
server/server_test.go

This PR adds the expires_in field to the response of token endpoint.
Related with #574.

server: add expires_in field to the response of token endpoint

---

static/html/header.html
static/html/reset-password.html

This commit reverts the last fix to the button, since it introduced
another issue. Also, it addressed the root cause of the original
problem, which was that one of the templates was missing the correct
class.

frontend: revert button fix

---

storage/storage.go

Because these values are used for OAuth2 codes, refresh tokens,
etc, they shouldn't be guessable. Increase the number of random
bytes from 64 to 128.
cc @gtank

storage: increase the number of bytes randomly generated for IDs

---

cmd/example-app/main.go

Some OpenID Connect providers, notably Google, don't follow the spec
and allow refresh tokens to be requested with the "offline_access"
scope. Try to determine which we're talking to by checking the
supported_scopes listed by the provider discovery.

dev branch: check if a provider supports a refresh token scope

---

server/handlers.go
server/oauth2.go
server/server_test.go

go-oidc sends an extra space before the list of scopes. This is bad
but we have to support it, so we'll be more lenient and ignore
duplicated whitespace.

server: allow extra spaces in scopes

---

CONTRIBUTING.md

That style guide is (or ought to be) enforced in all CoreOS repository documentation (`.md` files).
This change makes that more obvious.

docs: mention CoreOS docs style guide

---

storage/kubernetes/client.go

These status codes spam the error logs for events like key rotation
and third party resource creation. In these cases "bad" status codes
are expected and shouldn't be automatically printed.

storage/kubernetes: don't automatically print errors on bad HTTP status codes

---

storage/kubernetes/client.go

storage/kubernetes: set CurrentContext when the Kubeconfig file contains only one context

---

cmd/dex/serve.go
connector/github/github.go
connector/oidc/oidc.go
examples/config-dev.yaml

Allow users to define config values which are read form environemnt
variables. Helpful for sensitive variables such as OAuth2 client IDs
or LDAP credentials.

*: expand environment variables in config

---

storage/kubernetes/client.go
storage/kubernetes/client_test.go

The in cluster kubernetes client currently requires using the
downward API to determine its namespace. However this value can
be determine by inspecting the service account token mounted into
the pod. As a fallback, use this to guess the current namespace.

storage/kubernetes: guess namespace from the service account token

---

Documentation/storage.md

fyi @dghubble there's some third party resource docs here.

Documentation: add a document on storage options

---

server/handlers.go

fixes: #636
This commit addresses a problem where the `max-age` value is being set
in nanoseconds as opposed to seconds, as required by the specification.

server/handlers: fix Cache-Control header

---

Documentation/dev-integration-tests.md

Pointers on how to setup an OpenLdap container with Docker which can be used to run LDAP tests locally.
@ericchiang

Documentation: adding documentation for running ldap tests locally

---

connector/ldap/ldap.go
connector/ldap/ldap_test.go

wip will expand docs tomorrow and add an groups search mechanism.
cc @rithujohn191 @sym3tri

connector/ldap: expand LDAP connector to include searches

---

scripts/get-protoc

Right now `make grpc` only works if a user hasn't run a `make clean`.
Fix this.

scripts: fix get-protoc script to work directly after a clean

---

storage/kubernetes/client.go
storage/kubernetes/client_test.go
storage/kubernetes/storage.go
storage/kubernetes/types.go

Use a hash algorithm to match client IDs to Kubernetes object names.
Because cryptographic hash algorithms produce sums larger than a
Kubernetes name can fit, a non-cryptographic hash is used instead.
Hash collisions are checked and result in errors.
Closes #631

storage/kubernetes: allow arbitrary client IDs

---

connector/connector.go
connector/github/github.go
connector/mock/connectortest.go
connector/oidc/oidc.go
server/handlers.go
server/server.go
server/templates.go
server/templates_default.go
web/templates/approval.html
web/templates/login.html
web/templates/password.html

Let the server handle the state token instead of the connector. As a
result it can throw out bad requests earlier. It can also use that
token to determine which connector was used to generate the request,
allowing all connectors to share the same callback URL.
Callbacks now all look like:
https://dex.example.com/callback
Instead of:
https://dex.example.com/callback/(connector id)
Even when multiple connectors are being used.
Closes #597

*: allow call connectors to share a single a single callback

---

Documentation/storage.md
storage/conformance/transactions.go
storage/sql/config_test.go
storage/sql/sql.go

Still need to test this with the kubernetes third party resources.
closes #628
closes #600

storage/sql: use isolation level "serializable" for transactions

---

connector/ldap/ldap.go
server/server.go
server/server_test.go

Instead of throwing a 500 error if a user enters an invalid name,
display the same text box as if the user had entered the wrong
password.
NOTE: An invalid username now returns much quicker than an invalid
password. Consider adding an arbitrary sleep in the future if we
care about masking which was invalid.
cc @rithujohn191 @kans @dghubble 
closes #656

*: don't error out if a username doesn't exist in the backing connector

---

.travis.yml
scripts/rkt-build

*: travis tests and build scripts should use Go 1.7.3.

---

TODO.md
cmd/dex/config.go
cmd/dex/config_test.go
cmd/dex/serve.go
connector/github/github.go
connector/ldap/ldap.go
connector/mock/connectortest.go
connector/oidc/oidc.go
examples/config-dev.yaml
glide.lock
glide.yaml
storage/kubernetes/client.go
storage/kubernetes/k8sapi/client.go
storage/kubernetes/storage.go
storage/sql/config.go
storage/storage.go
vendor/github.com/ghodss/yaml/.gitignore
vendor/github.com/ghodss/yaml/.travis.yml
vendor/github.com/ghodss/yaml/LICENSE
vendor/github.com/ghodss/yaml/README.md
vendor/github.com/ghodss/yaml/fields.go
vendor/github.com/ghodss/yaml/yaml.go
vendor/github.com/ghodss/yaml/yaml_test.go

ghodss/yaml converts from YAML to JSON before attempting to unmarshal.
This allows us to:
* Get the correct behavor when decoding base64'd []byte slices.
* Use *json.RawMessage.
* Not have to support extravagant YAML features.
* Let our structs use `json:` tags

*: switch to github.com/ghodss/yaml for more consistent YAML parsing

---

cmd/dex/config.go
cmd/dex/config_test.go
cmd/dex/serve.go
examples/config-dev.yaml

cmd/dex: expose IDTokensValidFor and RotateKeysAfter server options in config

---

Documentation/v2.md

updates #655
(still need to do an update to the README)
cc @ElijahCaine

Documentation: add doc describing v2 changes

---

cmd/dex/config.go
cmd/dex/config_test.go
cmd/dex/serve.go
examples/config-dev.yaml

Bcrypt'd hashes have "$" characters in them. This means that #667
(accepting actually bcrypted values) combined with #627 (expanding
config with environment variables) broke the example config.
For now, allow storages and connectors to expand their configs from
the environment, but don't do this anywhere else.

cmd/dex: only expand from env for storages and connectors

---

Dockerfile

Add OpenSSL to the dex Docker container so wget can be used to query
HTTPS endpoints. This is a requirement for health checking when dex is
doing its own TLS termination.
This increased the image size from 20.37 MB to 20.92 MB (+550 KB).
Additionally add Ed and Rithu as maintainers.
Updates #682
cc @rithujohn191 @sym3tri
fyi @dghubble

Dockerfile: add OpenSSL to Docker container

---

Documentation/ldap-connector.md
connector/ldap/ldap.go

Specify "DN" as attribute name to return, but will only work if not present in ldap.Entry.Attributes
Use when full DN is stored in groupSearch's userAttr
Related to #536

Allow getAttr to return DN

---

server/server_test.go

Ensure compared times are within a second of one another instead of
rounding, which can flake if the two times are different enough to
do round to different values.
Tested using the golang.org/x/tools/cmd/stress tool.
The following set of commands fail without this patch:
$ go get golang.org/x/tools/cmd/stress
$ go test -o server.test github.com/coreos/dex/server
$ stress ./server.test -test.run=TestOAuth2CodeFlow
219 runs so far, 0 failures
425 runs so far, 0 failures
618 runs so far, 0 failures
802 runs so far, 0 failures
^C
Closes #699

server: fix expiry test flake

---

Documentation/github-connector.md
README.md
connector/connector.go
connector/github/github.go
connector/ldap/ldap.go
connector/mock/connectortest.go
connector/oidc/oidc.go
server/handlers.go
server/oauth2.go
server/server.go
server/server_test.go

This is a work in progress to add a RefreshConnector interface so refresh token requests query the upstream identity provider before returning.
Lots of testing needed.
Closes #693
Updates #678

connector: add RefreshConnector interface

---

Documentation/ldap-connector.md

Now that LDAP supports an `insecureSkipVerify` option, clarify that
`insecureNoTLS` is an extremely bad choice and as such we may drop
support for 389 in the future.
However, since we send plain text passwords from our frontend to our
backend, this probably gets us into a bigger conversation about dex's
TLS story. For example when terminiation is approporate. cc'ing
@dghubble for thoughts on how that might apply to our internal uses.
We probably want an overaching security doc at some point, but that
can be another PR.
cc @ElijahCaine since this is a docs review.

Documentation: clarify difference between LDAP ports and security guarentees

---

cmd/example-app/main.go

Use a non-empty state in the example-app to ensure dex is properly
preserving the state for the code flow.
Updates #712

cmd/example-app: use a non-empty state

---

glide.lock
glide.yaml
vendor/github.com/coreos/go-oidc/.travis.yml
vendor/github.com/coreos/go-oidc/jose/jwk.go
vendor/github.com/coreos/go-oidc/jwks.go
vendor/github.com/coreos/go-oidc/key/key_test.go
vendor/github.com/coreos/go-oidc/oidc.go
vendor/github.com/coreos/go-oidc/oidc/provider.go
vendor/github.com/coreos/go-oidc/test

Includes fixes for a panic when using HTTP/2[0] and some HTTPs calls
not actually using their passed context[1].
[0] coreos/go-oidc#117
[1] coreos/go-oidc#119

*: update vendored go-oidc

---

.travis.yml

We don't want to clutter the Quay repo with non-release tags,
particularly if they're not for the master branch.

v1: don't deploy on merge

---

Makefile
scripts/check-go-version

Add a script to check the Go version before building dex. This
gives a nice error message rather than just failing to compile.
With changes:
$ go version
go version go1.6.4 linux/amd64
$ make
ERROR: dex requires Go version 1.7+. Please update your Go installation: https://golang.org/dl/
Makefile:93: recipe for target 'check-go-version' failed
make: *** [check-go-version] Error 2
Checks only added for building the actual binary, not tests, since
this is aimed at users just starting off with the project.
Closes #738

*: check go version before building

---

cmd/dex/serve.go
examples/config-dev.yaml

New:
```
$ ./bin/dex serve examples/config-dev.yaml 
time="2016-12-15T13:14:03-08:00" level=info msg="config issuer: http://127.0.0.1:5556/dex" 
time="2016-12-15T13:14:03-08:00" level=info msg="config connector: mock" 
time="2016-12-15T13:14:03-08:00" level=info msg="config connector: local passwords enabled" 
time="2016-12-15T13:14:03-08:00" level=info msg="config storage: sqlite3" 
time="2016-12-15T13:14:03-08:00" level=info msg="config static client: example-app" 
time="2016-12-15T13:14:03-08:00" level=info msg="listening (http) on 0.0.0.0:5556"
```
Old:
```
$ ./bin/dex serve examples/config-dev.yaml 
time="2016-12-15T13:16:09-08:00" level=info msg="listening (http) on 0.0.0.0:5556" 
```
Negative case
New:
```
$ ./bin/dex serve examples/config-dev.yaml 
time="2016-12-15T13:14:31-08:00" …
```

cmd/dex: provide better feedback when parsing config

---

server/handlers.go
server/server.go
server/templates.go
web/templates/error.html

Tested the change with the example-app, it successfully displays an error template with error type and error description.
closes #657 
@ericchiang

server: add error HTML templates with error description.

---

storage/conformance/conformance.go
storage/sql/migrate.go
storage/sql/sql.go
storage/storage.go

Dex's Postgres client currently uses the `timestamp` datatype for
storing times. This lops of timezones with no conversion, causing
times to lose locality information.
We could convert all times to UTC before storing them, but this is
a backward incompatible change for upgrades, since the new version
of dex would still be reading times from the database with no
locality.
Because of this intrinsic issue that current Postgres users don't
save any timezone data, we chose to treat any existing installation
as corrupted and change the datatype used for times to `timestamptz`.
This is a breaking change, but it seems hard to offer an
alternative that's both correct and backward compatible.
Additionally, an internal flag has been added to SQL flavors,
`supportsTimezones`. This allows us to handle …

storage: fix postgres timezone handling

---

scripts/check-go-version

I followed https://github.com/coreos/dex/blob/master/Documentation/getting-started.md
and make fails, because scripts/check-go-version references the wron shell in it's shebang.
sh has no arrays

build fails

---

glide.lock
glide.yaml
vendor/github.com/coreos/go-oidc/verify.go

Includes fix for https://github.com/coreos/go-oidc/issues/123.

Bump go-oidc package

---

server/handlers.go
server/oauth2.go
server/oauth2_test.go
server/rotation.go
server/server.go
server/server_test.go

Accept the following response_type for the implicit flow:
id_token
token id_token
And the following for hybrid flow
code id_token
code token
code token id_token
This corrects the previous behavior of the implicit flow, which
only accepted "token" (now correctly rejected).
cc @rithujohn191 @xeonx 
@xeonx can you see if this branch works with your client?
closes #761

server: fixes for the implicit and hybrid flow

---

server/handlers.go
server/oauth2.go
server/oauth2_test.go
server/server_test.go
storage/storage.go

The "at_hash" claim, which provides hash verification for the
"access_token," is a required claim for implicit and hybrid flow
requests. Previously we did not include it (against spec). This
PR implements the "at_hash" logic and adds the claim to all
responses.
As a cleanup, it also moves some JOSE signing logic out of the
storage package and into the server package.
For details see:
https://openid.net/specs/openid-connect-core-1_0.html#ImplicitIDToken
closes #771

server: add at_hash claim support

---

Documentation/ldap-connector.md

Without a name, the example app's login form will only show `Log in with` as a button label.

Docs: Added a name to the LDAP connector

---

Documentation/github-connector.md
Documentation/ldap-connector.md
Documentation/saml-connector.md
cmd/dex/serve.go

Addresses one of the many issues detailed in #681

cmd/dex: make connector name field mandatory in dex configuration.

---

server/oauth2.go
server/oauth2_test.go

cc @rithujohn191 @marians
Fixes #791
Probably a cherry pick candidate.

server: support POSTing to authorization endpoint

---

Documentation/gitlab-connector.md
cmd/dex/config.go
connector/gitlab/gitlab.go
web/static/img/gitlab-icon.svg
web/static/main.css

connector: add GitLab connecor

---

server/handlers.go
server/templates.go
web/templates/login.html
web/templates/password.html

Switch from using "text/template" to "html/template", which provides
basic XSS preventions. We haven't identified any particular place
where unsanitized user data is rendered to the frontend. This is
just a preventative step.
At the same time, make more templates take pure URL instead of
forming an URL themselves using an "authReqID" argument. This will
help us stop using the auth req ID in certain places, preventing
garbage collection from killing login flows that wait too long at
the login screen.
Also increase the login session window (time between initial
redirect and the user logging in) from 30 minutes to 24 hours,
and display a more helpful error message when the session expires.
How to test:
1. Spin up dex and example-app with examples/config-dev.yaml.
2. Login through both the …

{web,server}: use html/template and reduce use of auth request ID

---

server/api.go
server/api_test.go
storage/conformance/conformance.go
storage/sql/config.go
storage/sql/crud.go
storage/sql/migrate_test.go
storage/sql/sql.go

This fixes #808.
If a database `Exec` command fails due to an "already exists" error, it is translated to a storage.ErrAlreadyExists error and propagated forward.
Added additional conformance tests to check for this scenario.

storage: Surface "already exists" errors.

---

Makefile

This makes specifying the VERSION when building native operating system packages require less hacks.
Refs: #811

[Makefile] Allow specifying VERSION as an env var

---

Documentation/storage.md

This makes manually creating the `o-auth2-client.oidc.coreos.com` actually work.
Fixes #818

[storage.md] Fix the ThirdPartyResource syntax

---

storage/kubernetes/storage.go
storage/kubernetes/storage_test.go

PR #815 fixed the Kubernetes storage implementation by correctly
returning storage.ErrAlreadyExists on POST conflicts. This caused a
regression in TPR creation (#822) when some, but not all, of the
resources already existed. E.g. for users upgrading from old
versions of dex.
Fixes #822

storage/kubernetes: fix conflict error detection in TRP creation

---

Documentation/api.md
Makefile
examples/config-dev.yaml
examples/grpc-client/.gitignore
examples/grpc-client/README.md
examples/grpc-client/cert-destroy
examples/grpc-client/cert-gen
examples/grpc-client/client.go
examples/grpc-client/config.yaml
examples/grpc-client/openssl.conf

The example program implements a Dex client that makes gRPC API calls to create, list and delete passwords.

examples: adding a gRPC client example.

---

server/rotation.go
server/rotation_test.go

server: fix expiry detection for verification keys

---

storage/conformance/conformance.go
storage/sql/crud.go

fixes #847
credit to @Calpicow for identifying.

storage/sql: add missing WHERE statement to refresh token update

---

Documentation/oidc-connector.md
README.md
connector/oidc/oidc.go
connector/oidc/oidc_test.go

closes #859
@curtisallen if you can confirm the fix I'll add docs and such.

connector/oidc: expose oauth2.RegisterBrokenAuthHeaderProvider

---

connector/oidc/oidc.go
connector/saml/saml.go
server/handlers.go

fixes #871.
Tested this change by running the example-app with okta. The "Creating SAML data: SAML does not support offline access" error is no longer displayed. The example app does not display a refresh token on the final out put page.

connector: Connectors without a RefreshConnector should not error out

---

storage/conformance/conformance.go
storage/kubernetes/storage.go
storage/kubernetes/types.go
storage/memory/memory.go
storage/sql/crud.go
storage/sql/migrate.go
storage/storage.go

This change adds the connector object to the back-end storage. This object will be used by the connector APIs.
Added unit tests.
Ran the conformance tests on Kubernetes:
PASS
ok  	github.com/coreos/dex/storage/kubernetes	8.533s

storage: add connector object to backend storage.

---

Documentation/saml-connector.md
connector/saml/saml.go
connector/saml/saml_test.go

Add ssoIssuer to fix Response issuer checking

---

Documentation/saml-connector.md
connector/saml/saml.go

Comparing with the spec, it appears that Audience values refer to EntityIssuer, and not RedirectURI (though in most cases they are the same, but not all).
This sets EntityIssuer to RedirectURI by default if it is not explicitly set, allowing implementations that need it to function correctly.
Spec: http://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0.html
We see that EntityIssuer is `https://sp.example.com/SAML2`, but Destination is `https://sp.example.com/SAML2/SSO/POST`
```xml
<samlp:AuthnRequest
xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
ID="identifier_1"
Version="2.0"
IssueInstant="2004-12-05T09:21:59Z"
AssertionConsumerServiceIndex="1">
<saml:Issuer>https://sp.example.com/SAML2</saml:Issuer> …
```

Validate audience with entityIssuer if present, use redirectURI otherwise

---

connector/saml/saml.go
connector/saml/saml_test.go
connector/saml/types.go

Intention is to make this code a little more understandable. Clean up some loops, add comments, etc.
Will add a bunch of tests tomorrow.
cc @rithujohn191 @squat

connector/saml: clean up SAML verification logic and comments

---

Documentation/github-connector.md
connector/github/github.go

Fixes https://github.com/coreos/dex/issues/622.
This change enables Dex to support login via GitHub enterprise. Users have to include the hostname of the GitHub enterprise account in the Dex ConfigMap.
This change has been tested with GitHub Enterprise edition.

connector/github: add support for github enterprise.

---

server/rotation.go

Fixes https://github.com/coreos/dex/issues/890.
If the user is running multiple instances of dex, it is possible that one instance can rotate the keys before another gets around to doing it. Since this is an acceptable situation, we can avoid logging this as an error.

server/rotation.go: avoid displaying the "keys already rotated" error

---

README.md

It was pointed out by @davidillsley that we don't point this out
anywhere in our docs.

README: add section about reporting security vulnerabilities

---

connector/saml/testdata/bad-status.tmpl
connector/saml/testdata/bad-status.xml

Notice this when inspecting the code coverage results. For some
reason this test wasn't triggering the bad status code path, maybe
due to signature validation. Removing the comment fixed the code
coverage.

connector/saml/testdata: fix bad status test case

---

Documentation/kubernetes.md

Additional step to make Dex working on Kubernetes when RBAC authorization is used.
Without this step, Dex is giving errors like:
... cannot create thirdpartyresources.extensions at the cluster scope ...
or
... cannot get signingkeies.oidc.coreos.com in the namespace ...

Dex on Kubernetes with RBAC authorization - documentation updated

---

cmd/dex/config.go
cmd/dex/config_test.go
cmd/dex/serve.go
server/handlers.go
server/server.go
server/server_test.go
storage/conformance/conformance.go
storage/memory/static_test.go
storage/static.go
storage/storage.go

This change enables connector objects to be dynamically modifiable. The connectors defined by the user in the Dex ConfigMap will be deemed as static connectors and will be 'read-only'. 
Dynamic connectors can be created, updated or deleted via gRPC API calls from a dex client (api calls yet to be implemented). This essentially means that every time the dex server refers to a connector object it needs to ensure that it has retrieved the latest version of this connector object from the storage.

server: account for dynamically changing connector object in storage.

---

cmd/dex/serve.go

The "local" connector will have an empty config attribute which will flag an error due to the following check:
if c.Config == nil {
return fmt.Errorf("invalid config: no config field for connector %q", c.ID)
} 
This change will add the "local" connector directly to the storageConnectors slice to avoid the check above

cmd/dex/serve: add local connector directly to static connectors in storage

---

Documentation/ldap-connector.md

Users will be unable to specify a bindPW with `$` in it directly in the config file. We use os.ExpandEnv to expand the config file and this will look at the '$' and try to apply an environment variable to replace it with and accoridng to the source code https://golang.org/src/os/env.go there is no way to escape it. 
If users want to specify a password with `$` they should save it in an env variable.
Fixes #930

Documentation/ldap-connector.md: Warn about LDAP connector's bindPW restriction.

---

Documentation/github-connector.md

Looks like a lot of users are trying the GitHub connector with private email ids.

Documentation/github-connector: warn user that GitHub email id should be public.

---

examples/config-dev.yaml

examples: document explicit flow in example config

---

Documentation/oidc-connector.md
connector/oidc/oidc.go
connector/oidc/oidc_test.go
examples/config-dev.yaml

See #959 - Google's OIDC implementation supports limiting access to a certain Google Apps / G Suite domain. This lets dex users ensure that only people in their organization can log in, and not just anyone with a Google account.

Google hosted domain support

---

storage/storage.go

Our team is going to use Azure AD as an IdP with SAML 2.0 connector. However, when the connector sends an AuthnRequest to Azure AD's endpoint, Azure AD often responds with an error message such as `The request is not a valid Saml2 protocol message`.
After a brief investigation, I found that the connector often generates an AuthnRequest whose ID attribute starts with a digit though such an ID attribute is forbidden by the XML specification. The ID attribute is originally generated by `storage.NewID()` and this PR will change the behavior of the function to avoid generating an ID which starts with a digit.
Refs: https://www.w3.org/TR/REC-xml/#sec-attribute-types

bugfix: avoid generating an invalid ID attribute in SAML's AuthenRequest element

---

Documentation/ldap-connector.md

A lot of people seem to be confused about how they should implement group specific queries. Thought it would be nice to have this as part of our docs.

Documentation: add a group query example for the ldap connector.

---

.travis.yml

thanks for catching this, @ericchiang.

.travis.yml: bump golang version to 1.8.3

---

server/rotation.go

This fixes https://github.com/coreos/dex/issues/976.
It also ensures that it displays "keys already rotated" as an info log message instead of an error message.

server/rotation.go: Fix key rotation with multiple dex instances.

---

connector/oidc/oidc.go
examples/config-dev.yaml

connector/oidc: fix hosted domain support.

---

Documentation/github-connector.md
connector/github/github.go

connector/github: support for multiple orgs and teams within orgs; allow filtering by both orgs and teams
Documentation: examples of GitHub `orgs` field with multiple orgs and org with teams
The GitHub connector should give more fine-grained control over which organizations and teams have access to an application. Restricting authorization to (multiple) `teams` within (multiple) `orgs` by specifying them in the `connector` config section gives dex users such control.
Tests: set up organizations with/out teams and a test user; went through scenarios listed in this [function description](https://github.com/estroz/dex/blob/6cab4ada83802b80eb21e3fdcb3123a778d1c196/connector/github/github.go#L286-L288)
Note: this PR obsoletes #1008 because similar errors are returned if user is not a org …

connector/github: multiple orgs, query by teams

---

server/api.go
server/api_test.go
server/server.go
server/server_test.go

server: log bcrypt cost if > 12, error on runtime > 10s
The bcrypt hashing algorithm runtime grows exponentially with cost, and might cause a timeout if the cost is too high. Notifying the user of high cost and of long running calculations will help with parameter tuning and debugging.
Tests: added test cases for both additions
Fixes #962

Log large bcrypt costs, error if password-hash comparison takes > 10s

---

Documentation/github-connector.md
connector/github/github.go

connector/github: `user` email field will be populated even if user has a private (primary) email
Documentation: removed private emails caveats section
Tests: tested manually using a user with a private primary email.
Fixes #1017

connector/github: enable private, primary emails

---

Documentation/github-connector.md

This PR updates GitHub connector docs to notify users of our current workaround relating to #920. Part of the issue, users outside of the organization being able to log into dex-authenticated apps, was solved by https://github.com/coreos/dex/pull/1013. 
Test cases for the above PR:
1. User not in a config org: fails
1. User in a config org but not in a config team: fails
1. User in a config org with no config teams: passes
1. User in a config org with no config teams, but already granted the app permission: **fails** <- issue
1. User in a config org and in a config team: passes

Documentation: github org redirect caveat

---

connector/gitlab/gitlab.go

connector/gitlab: correct scope strings, better default scope, and update-able scopes
Current scope strings were taken from GitHub API, and are incorrect. Scopes cannot be updated either. This PR fixes both issues. API version upgraded to support scopes, and is the latest API version.
Fixes #1009

connector/gitlab: correct scope strings, better default

---

connector/github/github.go

Removed logic that used a GitHub users' display name over their login name. Login name will work in API requests while display name will not.
Fixes a bug where users with both a display name and login name would not see org membership correctly.
Tests: ran through all cases in #1019 manually
Fixes #1032

connector/github: fix username used when making API requests

---

connector/github/github.go

connector/github: switch debug -> info log levels and add a more informative negative userInOrg log message
Info logs are more useful as they're always created. More informative userInOrg log message will help users troubleshoot login issues.

connector/github: debug->info logging, informative userInOrg msg

---

connector/github/github.go

This change being made to account for GitHub Enterprise not supporting verified emails. If connecting to GitHub Enterprise (as indicated by hostName field being populated), the email.Verified field is set to true regardless of what comes back from the GitHub API.

When connecting to GitHub Enterprise, force email verified field to true

---

connector/github/github.go

connector/github: fix issue of skipped org membership check when client doesn't specify `groups` scope while using `orgs` config field.
Fix a bug where checking if a user is an organization member would be skipped if a client didn't provide the "groups" scope.
Revert behavior of "org" to not check if a user is an organization member. Admins that need to require a user be an organization member to log in should use the newly added "orgs" field.
Tests: went through tests listed in #1019 for `orgs`, and tested `org` to make sure users outside that org can log in (old behavior)

connector/github: fix groups scope check when 'orgs' is populated

---

server/api.go
server/api_test.go
server/server.go
server/server_test.go

api.go: `checkCost` only returns an error if hash cost is too high or low (or if `Cost` fails)
server.go: remove timeout logic and reverte back to a hash comparison, with an addition cost check
server_test.go: `MinCost` will cause `Login` to error now, so use `DefaultCost` instead.
Instead of timing out after 10 seconds of hashing, dex should not permit a bcrypt hash cost > 16. The below benchmarks show that cost > 16 exponentially grows to times that a user would notice when logging in, considering that dex will likely be running on a server (much beefier than my machine).
Tests for login timeouts have been removed.
Applies to #1030. Middleware for generically timing out requests will be implemented soon.
Benchmarks (Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz):
Cost | Time (sec)
:---: | …

server: set sane bcrypt cost upper bound

---

Documentation/oidc-certification-setup.md

Document setting up a dex test server and OpenID test instance to test dex against the OpenID Connect Basic OP ([profile outline](http://openid.net/wordpress-content/uploads/2016/12/OpenID-Connect-Conformance-Profiles.pdf), section 2.1.1) test profile.
Relates to #42

Documentation: OIDC conformance test setup

---

Documentation/github-connector.md

Part of the caveat currently described by GitHub connector documentation is no longer an issue, but the part relating to re-authorization of an application after being added to an organization is still valid.

Documentation: fix redirect caveat description

---

server/api.go
server/api_test.go

Test modification triggers the panic reported by a user. Rest of the patch fixes the panic.
Fixes #1055

server: fix panic caused by deleting refresh token twice through api

---

Makefile
connector/github/github.go
scripts/gofmt

Noticed in #1058 that our gofmt make target isn't actually erroring
if someone commits misformatted code.

Makefile: error out if go files aren't correctly formatted

---

Documentation/storage.md
storage/kubernetes/client.go
storage/kubernetes/k8sapi/crd_extensions.go
storage/kubernetes/storage.go
storage/kubernetes/types.go

This PR makes the following changes:
1. Add CRD support for kubernetes storage. In order to enable CRDs a Boolean flag has been introduced in the kubernetes storage config (`useCRD`).
2. The apiVersion i.e the API Group and version can be configured via the ConfigMap.

storage/kubernetes: add CRD support

---

storage/kubernetes/types.go

Fixes #1070 
OfflineSession object should have the `kind` value as `OfflineSessions` instead of `OfflineSession`. Missed an 's' at the end

storage/kubernetes: Correct the OfflineSession object CRD definition

---

storage/kubernetes/storage.go

Logging before attempting to make any connection to Kubernetes is useful when the connection hangs and dex is killed before it can log any errors.

storage/kubernetes: Log before registering custom resources

---

storage/kubernetes/client.go

does the http.Client ever get a timeout attached to it for requests that timeout? Or would the server timeout the request?

add client request timeout

---

server/oauth2.go
server/server_test.go

See https://github.com/coreos/dex/issues/1087

Cross clients improvement - requesting client ID always added to the audience claim

---

connector/gitlab/gitlab.go
connector/gitlab/gitlab_test.go

Fix regression in Link parser. 
.* is to ambiguous.

connector/gitlab: Fix regexp in Link parser

---

web/templates/password.html

In the tectonic-installer we are doing some tests to check if the console is up and running. Just adding some ids for better tests and to not rely on css or xpath.
Please let me know what do you think.

tests: add ids to elements for testing automation

---

Documentation/authproxy.md
README.md
connector/authproxy/authproxy.go
connector/github/github.go
connector/gitlab/gitlab.go
connector/ldap/ldap.go
connector/mock/connectortest.go
connector/oidc/oidc.go
connector/oidc/oidc_test.go
connector/saml/saml.go
server/handlers.go
server/server.go

In Debian, we’re currently investigating whether we can use dex as part of https://sso.debian.org/ (see also https://wiki.debian.org/DebianSingleSignOn).
In the current setup, users authenticate against Apache2, and the web application behind sso.debian.org issues certificates based on the `REMOTE_USER` request environment variable.
Hence, to keep (especially user-visible) changes at a minimum, we’d like to keep the setup the same regarding authentication, just replace the certificates part with dex as an OIDC provider (for GitLab and others).
The “external” connector in this pull request accomplishes that; see also the included documentation.
Please consider merging this pull request. Thanks!

Implement the “external” connector (for Apache2 mod_auth etc.)

---

Documentation/authproxy.md
server/server.go

follow-up for https://github.com/coreos/dex/pull/1100

authproxy.md: strip X-Remote-User

---

connector/oidc/oidc_test.go

Notice this flake here https://travis-ci.org/coreos/dex/jobs/293766424
Unit tests shouldn't talk to the internet.
```
=== RUN   TestOidcConnector_LoginURL
--- FAIL: TestOidcConnector_LoginURL (30.47s)
oidc_test.go:79: failed to open connector: failed to get provider: Get https://accounts.google.com/.well-known/openid-configuration: dial tcp 108.177.10.84:443: i/o timeout
```
@roguePanda noticed this was added in https://github.com/coreos/dex/pull/974. Removing it for now. If you'd like to follow up with a PR to add the test back in please do.

connector/oidc: remove test that talks to the internet

---

.travis.yml
Documentation/dev-integration-tests.md
scripts/test-k8s.sh
storage/kubernetes/client.go
storage/kubernetes/storage.go

*: run kubernetes tests in travis

---

web/static/main.css

Fixes an issue where the ldap icon was missing in the tectonic console.
I think the long-term fix would be to change the login template to add classes based on the connector type, not the connector ID. That requires some bigger changes though.

Add tectonic-ldap matching rule to ldap icon.

---

README.md

We haven't been using milestones or actively planning sprints for dex lately. It's probably better to just remove this.
Closes https://github.com/coreos/dex/issues/1122

README.md: remove milestones link

---

server/handlers.go
server/templates.go
web/templates/password.html
web/themes/coreos/styles.css

This way, the user who has selected, say, "Log in with Email" can make up
their mind, and select a different connector instead.
However, if there's only one connector set up, none of this makes sense -- and
the link will thus not be displayed.
Fixes #1115.

show "back" link for password connectors

---

Documentation/ldap-connector.md
connector/connector.go
connector/ldap/ldap.go
connector/ldap/ldap_test.go
connector/mock/connectortest.go
examples/config-ldap.yaml
server/handlers.go
server/server.go
server/server_test.go
server/templates.go
web/templates/password.html

Cherry pick of #1116
Updates #1127
Assigning @rithujohn191 for approval

password connectors: allow overriding the username attribute (password prompt)

---

api/api.proto

It would be good to have a stable package name for consistency.

Specify Java package for dex Protobuf API

---

Documentation/microsoft-connector.md
README.md
connector/microsoft/microsoft.go
server/server.go
web/static/img/microsoft-icon.svg
web/static/main.css

The connector provides an ability to authenticate in Dex via Microsoft with both personal and organization accounts. It's possible to restrict authentication based on the type of account or even to require accounts to belong to specific tenant.
Groups are also supported and will be queried if `groups` claim is present in the request __and__ `tenant` is configured in Dex configuration file. Groups support is not without caveats, though. See Documentation/microsoft-connector.md for details.

Implement Microsoft (Azure AD) connector

---

server/handlers.go
server/templates.go

We are facing an problem in health-checking a dex service. The health-check endpoint provided by dex always returns with HTTP status code 200 even if it is returning an error status page.
The function which renders an error page doesn't seem to take care of HTTP status code. This PR will fix the function to set a proper status code before sending contents.

Bugfix: Set a proper status code before sending an error status page

---

Documentation/using-dex.md

Change provider.NewVerifier to provider.Verifier per the godocs:
https://godoc.org/github.com/coreos/go-oidc#Provider.Verifier

Correct "Verifier" method name in using-dex doc

---

server/templates.go

Hey all. This is an update to the description of the "email" scope that clarifies that it only grants access to view the user's email _address_ rather than their actual emails.

Clarify email scope description

---

Documentation/oidc-connector.md

document limitations in the OpenID Connect connector

---

server/handlers.go

Before, you could not POST your credentials to a password-connector's
endpoint without GETing that endpoint first. While this makes sense for
browser clients; automated interactions with Dex don't need to look at
the password form to fill it in.
A symptom of that missing GET was that the POST succeeded (!) with
login successful: connector "", username="admin", email="admin@example.com", groups=[]
Note the connector "". A subsequent call to finalizeLogin would then
fail with
connector with ID "" not found: failed to get connector object from storage: not found
Now, the connector ID of an auth request will be updated for both GETs
and POSTs.

handlers/connector_login: update AuthRequest irregardless of method

---

connector/saml/saml_test.go
connector/saml/testdata/tampered-resp.xml

As sketched here:
https://developer.okta.com/blog/2018/02/27/a-breakdown-of-the-new-saml-authentication-bypass-vulnerability
Thought it was interesting to see how our SAML connector behaved. And
it seems to be behaving well. :)
(The interesting line in the added test data response is [this one](https://github.com/coreos/dex/compare/master...srenatus:sr/add-test-case-for-tampered-nameid-field-with-comment?expand=1#diff-513a1479ee39e4d5528de65982c3529eR51).)

saml: add tests case covering tampered NameID field (comment)

---

scripts/check-go-version

the current way  just keeps one prefix number as the major number, it should be the whole number after the dot.
for now, if make executed, go 1.10 will be reported **unsupported**

Update check go major version way

---

Documentation/connectors/gitlab.md
connector/gitlab/gitlab.go

The URL `https://www.gitlab.com` which is the default baseURL for the GitLab connector does not work any more. According to the DNS entries it's still pointing to an Azure ip adress while the whole service has moved to google cloud. Since `https://gitlab.com` is main URL for GitLab anyway that's probably a better default anyway. 
Documentation also updated.

fix default baseURL for GitLab connector

---

connector/ldap/ldap.go

Some directory servers (I think it's Oracle) return
Constraint Violation: Exceed password retry limit. Account locked.
when attempting to login too many times. While constraint violation can
mean many things, we're checking this as an error on BIND, so it's
more likely that something like this has happened than any other thing.
Hence, we should treat it as an "incorrect password" situation, not an
internal error.
It would of course be preferrable to surface more information about this
precise error (and similar ones), but I think this is beyond this small
change.
(This is some prior art: https://github.com/vesse/passport-ldapauth/issues/21 )

connectors/ldap: treat 'constraint violation' on bind as bad credentials

---

storage/etcd/config.go

Heya! Subtle bug here for `etcd3` storage backend. The timeout was being unnecessarily multiplied by `time.Second` causing a near-infinite timeout before returning on connection errors. This makes debugging Dex with etcd storage very annoying :)
```
fmt.Printf("time 1: %v\n", 2 * time.Second)
fmt.Printf("time 2: %v\n", 2 * time.Second * time.Second)
output:
time 1: 2s
time 2: 555555h33m20s
```

fix timeout bug for etcd3 client connect

---

Documentation/dev-releases.md
Makefile
examples/k8s/dex.yaml

This complements #1284. 
For every push to master (this should include merges, but I haven't merged anything since setting this up), and every pushed tag, quay will now build (and tag, respectively) docker images in the https://quay.io/dexidp/dex repository.

release process: update quay notes

---

README.md

This fixes a link to the Bitbucket Cloud documentation from README.md - I forgot to change this link when renaming Bitbucket to Bitbucket Cloud.

Fix broken link to Bitbucket Cloud documentation

---

Documentation/connectors/oidc.md

The OIDC connector documentation / example doesn't mention the scopes config parameter.  It probably should.
I'm not super excited about that 106-character line containing the URL, but the link to the documentation is relatively long.

Add mention of `scopes` parameter in OIDC doc

---

.travis.yml
Dockerfile

Using an old version of Go was breaking the build. Update travis and the Docker image while we're at it.
https://travis-ci.org/dexidp/dex/builds/444775302

*: update go version

---

connector/mock/connectortest.go

we've been using the mock passwordConnector for some internal testing, but it doesn't satisfy the `RefreshConnector` interface. this change fixes that.

add Refresh() to mock passwordConnector

---

storage/kubernetes/storage.go

responding to this issue #1332 #1308 , this PR will provide a simple fix to disable CRD creation step. 
In our case, this feature will greatly reduce the need for cluster scope permission to create CRDs, providing that we already have got a DEX running at cluster level which means all necessary CRDs have been created already, and we want to deploy a separate DEX in a team's namespace with minimal permissions(kubernetes Role only, no clusterRole allowed.) in order to de-couple this DEX with the existing cluster-wide DEX.
Thanks!

allow it to disable CRD creation

---

server/handlers.go

PR addresses issue https://github.com/dexidp/dex/issues/1263 and implement the following change:
On failed login user will see message provided by the connector instead of generic `Failed to return user's identity.` . Example: `Failed to authenticate: github: user "<username>" not in required orgs or teams`

Issue #1263 - Render error message provided by connector if user authentication failed

---

storage/conformance/conformance.go

this failed on my machine due to the unexported 'loc' field of the time structure - it was nil in one and set to a ton of timezone data in the other. not sure why, but I don't think it's critical to compare these hidden fields so long as the timestamp's actual value is equal.

fix bogus conformance failure due to time zones

---

Documentation/connectors/github.md
connector/github/github.go
connector/github/github_test.go

I've discovered that new behavior implemented in https://github.com/dexidp/dex/pull/1340 might be undesired for some users. The user might be part of multiple orgs and teams, so if all groups are loaded then JWT token does not fit into cookie. 
With changes from https://github.com/dexidp/dex/pull/1340 applications which uses Dex + github without configuring orgs now might get a token which does not fit into cookie. Although it is a rare case I think it worth adding new setting which explicitly enable github connector to load all user groups.

Issue #1102 - Add config to explicitly enable loading all github groups

---

storage/sql/config.go
storage/sql/config_test.go

This enables the use of socket paths like `/var/run/postgresql` for the 'host' instead of requiring TCP.

Use pq connection parameters instead of URLs for postgres connections

---

Documentation/connectors/github.md
connector/github/github.go
connector/github/github_test.go

This allows the connector to be configured with `both` so that both team names and slugs can be returned in the groups. This makes configuring teams a bit more foolproof in Concourse; we would often have confusion over whether the team name or slug should be given by the user, so it's easier to just allow both, since collisions shouldn't be possible anyway.

Add 'both' option to use team name AND slug in TeamNameField

---

Documentation/connectors/ldap.md

LDAP connector - Document that 'DN' must be in capitals

---

Documentation/connectors/ldap.md
Documentation/kubernetes.md
Documentation/storage.md
examples/k8s/dex.yaml

Related to issue #1262 .
While not strictly related to TLS, I'd like to make one or more follow-up PRs to fix issues around old references to TPRs, missing instructions on creating the serviceAccount and roles for RBAC etc. But this is a first pass, hopefully it makes reviewing easier.

Kubernetes docs: clarify steps around use/creation of TLS assets.

---

Makefile

Go 1.9 removed "./..." matching the vendor directory while Go 1.10 added
build and test caching. This means we no longer need to grep out
vendored matches (except for golint which doesn't implement the same
behavior), and we no longer need to pre-build packages with "go build -i".
https://golang.org/doc/go1.9#vendor-dotdotdot
https://golang.org/doc/go1.10#build

Makefile: cleanups for newer versions of Go

---

cmd/dex/config_test.go
storage/sql/config.go
storage/sql/postgres_test.go

This is for #1354.
I've not had a need for `MaxIdleConns` and `ConnMaxLifetime` myself, but it felt weird to only expose of the three settings.

postgres: expose database/sql tunables

---

cmd/dex/config.go
cmd/dex/config_test.go
cmd/dex/serve.go
server/handlers.go
server/server.go

This is a band-aid against #1292
I did not change the default from 24h, but I think it should be much lower for safety.

Make expiry of auth requests configurable

---

Dockerfile

Go 1.11.3 and 1.10.6 were released to mitigate security issues.
These don't appear to impact dex, but update anyway.
Ref: https://groups.google.com/forum/#!topic/golang-announce/Kw31K8G7Fi0

Dockerfile: update to Go 1.11.3

---

cmd/example-app/main.go
server/handlers.go
storage/kubernetes/client.go

I think we should better use http.MethodGet instead of "GET", the same as "POST".

Replace "GET", "POST" to http.MethodGet and http.MethodPost

---

connector/ldap/ldap.go
connector/ldap/ldap_test.go

In my organization, we don't have an LDAP mail attribute because email addresses are always based on username. This PR adds an `emailSuffix` option for this use case, where an email domain can be specified in place of a mail attribute.

LDAP connector - add emailSuffix config option

---

Dockerfile

Dex doesn't actively use ECDSA keys, but update anyway for CVE-2019-6486
https://groups.google.com/forum/#!topic/golang-announce/mVeX35iXuSw

Dockerfile: update Go to 1.11.5

---

Documentation/connectors/kubelogin-activedirectory.md
Documentation/connectors/ldap.md
examples/config-ad-kubelogin.yaml

This PR includes Active Directory and kubelogin integration sample.

Add Active Directory and kubelogin integration sample.

---

connector/ldap/ldap_test.go

The filters for user and group searches hadn't been included in our LDAP
tests. Now they are.
The concrete test cases are somewhat contrived, but that shouldn't
matter too much. Also note that the example queries I've used are not
supported in AD: https://stackoverflow.com/a/10043452

ldap_test: add filter tests

---

server/handlers.go
server/handlers_test.go
server/server.go

Instead of querying the storage every time a health check is performed
query it periodically and save the result.
Updates #1386

server: update health check endpoint to query storage periodically

---

Documentation/connectors/github.md
connector/github/github.go
connector/github/github_test.go

Allow an option to use the github user handle rather than an id.
For downstream apps using a github handle is much simpler than working with numbers.
Whilst the number is stable and the handle is not - GitHub does give you a big scary warning if you try and change it that bad things may happen to you, and generally few users ever change it.
This can be enabled with a configuration option `useLoginAsId`

Use github login as the id

---

.travis.yml
go.sum

Go 1.11.3 changed how checksums are created in some cases, which caused
failures building via modules. (ref golang/go#29278)
Update the checksums for the failing modules.
To catch this is the future, a modules build was added to the build matrix. I
also noted that we were pinning the `.0` patchlevel of each go version which
wouldn't have picked this up, updated it to build with the latest patch
release.

Update modules for go 1.11.4+

---

Dockerfile

- Update build container to golang:1.12.4-alpine
- Update dex image to alpine:3.9
- Run dex as non-root user
Signed-off-by: Stephen Augustus <saugustus@vmware.com>
Fixes: #1425

Update Docker build/image

---

cmd/dex/serve.go

Hi,
According to https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/, client ID should not be easily guessable and many people use random hex strings. It's therefore easier to identify clients in logs using their name instead of their ID.

cmd/dex/serve.go: log static client name instead of ID

---

Documentation/connectors/gitlab.md
connector/gitlab/gitlab.go
connector/gitlab/gitlab_test.go

The GitLab connector was missing the group/org/team filtering as in BitBucket or GitHub connector. In this PR I would like to cure this absence.

gitlab: support for group whitelist

---

server/handlers.go

When listing connectors fails, incorrect error variable is printed.

Print appropriate error

---

pkg/log/logger.go

The logging interface added in #1408 captured only logging methods used in dex itself. I understand the rationale, but I also find it awkward to see functions like `Warnf` left out when `Warn` exists. And similarly, having `Errorf` but not `Error`.
For projects that extend Dex to introduce additional connectors, for example, it feels awkward to have to use `fmt.Sprintf` for `Warn`, but not for `Error`.

Round out logging interface with functions for all levels

---

server/server.go

I am troubleshooting an issue with my Dex setup where tokens fail to get refreshed (due to getting a 401 back on `/token`), and I realized that there are no metrics for the `/token` endpoint, which is a bit annoying as it makes it harder to track how frequently this issue is happening over time, is it the first time it happens, etc.  So I figured it be nice to add the same basic instrumentation that other handlers benefit from to the CORS handlers as well.

server: add metrics for CORS handlers.

---

Documentation/connectors/oidc.md
connector/oidc/oidc.go

Some oauth providers return "thin tokens" which won't include all of the
claims requested. This simply adds an option which will make the oidc
connector use the userinfo endpoint to fetch all the claims.
as an example of an IDP that does this: https://support.okta.com/help/s/article/Okta-Groups-or-Attribute-Missing-from-Id-Token

Add option in oidc to hit the optional userinfo endpoint

---

Documentation/connectors/oidc.md
connector/oidc/oidc.go
connector/oidc/oidc_test.go

I make userID configurable.
The claims are changed `map[string]interface{}` from struct because these vary depending on the OIDC provider.
And userID is made configurable.
There are cases where users want to use other than sub-claim as userID.
(related https://github.com/concourse/dex/pull/8)
Thanks!

oidc: Make userID configurable

---

.travis.yml

This is because I suspect the gofmt rules change between these versions to
make half the travis CI tests fail sometimes?
Compare [this](https://travis-ci.org/dexidp/dex/builds/538212316) with [that](https://travis-ci.org/dexidp/dex/builds/538220934) 🤕

travis: replace golang 1.10 and 1.11 with 1.12

---

connector/oidc/oidc.go
connector/oidc/oidc_test.go

connectors/oidc: truely ignore "email_verified" claim if configured that way

---

connector/linkedin/linkedin.go

This updates LinkedIn connector to use the more recent v2 APIs. Necessary because v1 APIs are not able to retrieve email ids any more with the default permissions.
The API URLs are now different. Fetching the email address is now a separate call, made after fetching the profile details. The `r_basicprofile` permission is not needed any more, and `r_liteprofile` (which seems to be the one assigned by default) is sufficient.
The relevant API specifications are at:
- https://docs.microsoft.com/en-us/linkedin/shared/integrations/people/profile-api
- https://docs.microsoft.com/en-us/linkedin/shared/integrations/people/primary-contact-api
- https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq#how-do-i-retrieve-the-members-email-address
fixes #1452

Update LinkedIn connector to use v2 APIs

---

Documentation/connectors/oidc.md
connector/oidc/oidc.go
connector/oidc/oidc_test.go

this PR is needed to support OpenID providers that don't have a "name" claim

make userName configurable

---

ADOPTERS.md
Documentation/production-users.md

Let's get that list up to date -- for one thing, it's interesting, and it will probably help with #1379.

ADOPTERS: replace Documentation/production-users.md, add Chef

---

cmd/example-app/main.go
cmd/example-app/templates.go
server/handlers.go
server/oauth2.go

This makes it easy to play with the new parameter.
However, it also shows a problem: when trying to login to dex (run via `dex serve examples/config-dev.yaml`), and providing `local` as `connector_id`, the "back link" will be shown, and go back in browser history one step -- this will _not_ lead you to the connector selection, but to example-app. To be fixed in a follow-up PR (_help wanted!_ :wink:)
Added two small cleanups, nothing too significant.

add connector_id to example app

---

Documentation/connectors/microsoft.md
connector/microsoft/microsoft.go

This PR add a `useGroupUUID` option to return groups UUIDs instead of names. And, it change the behavior of the `groups` option to not only allow user member of a particular group but also act as a whitelist for the groups return in the claim.
The main reason for using group UUIDs, is that group names are not unique in Microsoft Azure AD.

microsoft: option for group UUIDs instead of name and group whitelist

---

Documentation/connectors/gitlab.md
connector/github/github.go
connector/gitlab/gitlab.go
connector/gitlab/gitlab_test.go

I'm not user if we can use the same name `useLoginAsID` as in GitHub since in GitLab it is called Username in the API (vs Login). But in this case, the config is the same.
We have a test for it as well (which I have added, but now it is valid :)

connector/gitlab: implement useLoginAsID as in GitHub connector

---

cmd/dex/config.go
cmd/dex/config_test.go
cmd/dex/serve.go

- Bulk Validate all the configuration
- Added test case for validation.
```
Invalid Config:
-	no issuer specified in config file
-	no storage supplied in config file
-	must supply a HTTP/HTTPS  address to listen on
exit status 2
```
Carry forward from #1264

Return config validation errors in one go

---

server/api.go

Before:
msg="api: password check failed : %vcrypto/bcrypt: hashedPassword is not the hash of the given password"
After:
msg="api: password check failed : crypto/bcrypt: hashedPassword is not the hash of the given password"

server/api: fix logging in VerifyPassword

---

server/handlers.go

The state parameter is invalid, expired, or already consumed and this HTTP request should not be retried.

Return HTTP 400 for invalid state parameter

---

Makefile

When doing `make bin/golint` one will get an error about go modules and lint.  By asking `go install -v ...` on the absolute file path, the error goes away.
I'm unsure about this nuance of `go install` where the absolute path will work just fine but the current `REPO_PATH` does not.  Regardless, this _does_ fix it and it does allow dex to use the latest and greatest grpc and lint libraries, unlike my previous PR.
Fixes #1506

Adjusting Makefile so that `golint` will compile

---

server/handlers_test.go

Exercises some validation logic in the callback handler

Add tests for some callback handler error conditions

---

Documentation/templates.md
cmd/dex/config_test.go
server/server.go
server/templates.go

This follows a discussion from #1470

Allow arbitrary data to be passed to templates

---

cmd/dex/config.go
cmd/dex/config_test.go
cmd/dex/serve.go
server/handlers.go
server/server.go

We are currently building an auth proxy system that will be used to authenticate users before being redirected to their destination. The fact that Dex automatically forwards to the connector if there's only one has been confusing for our users. They type `my-service.com` in their browsers and end up on Google login, not a great UX.
This PR allows to specify an option to always show the connector selection screen even if there's only one. That way our users will land on a themed login page, and select "Login with Google" before ending up on Google login.
Let me know what you think!

Add option to always display connector selection even if there's only one

---

examples/config-dev.yaml

Improve example "documentation" for oauth2 configuration feature introduced in #1505 and other previously-added feature.

Add examples for recent additions to oauth2 configuration options

---

server/handlers.go

`CallbackConnectors` display the error message to the user, which is quite nice for debugging purposes however, `PasswordConnectors` haven't returned it, this fixes that.

connector/ldap: display login error

---

Documentation/kubernetes.md

The Kubernetes guide has a bit of an unusual structure, where the config shown at the beginning of the document is not valid, and requires steps later in the document.
To clarify it a bit, and avoid restructuring the whole document, I propose to add a small note addressing the CA file used in the apiserver config.

Clarify the origin of the ca file in the Kubernetes guide

---

server/api.go

I was not able to build the project due to missing the "golang.org/x/net/context" (with `go version go1.12.9 darwin/amd64`). It looks like there are two options here to fix this: (1) add a dependency to golang.org/x/net/context, or (2) use the context from the standard library.
Since the comment in the code does no longer apply (it is two years old) and the linked issue seems to be resolved, I think we can safely move to use "context".

Replace x/net/context with stdlib context

---

cmd/dex/serve.go

The default cipher suites used by Go include a number of ciphers that
have known weaknesses. In addition to leaving users open to these
weaknesses, the inclusion of these weaker ciphers causes problems with
various automated scanning tools.
This PR disables the CBC-mode, RC4, and 3DES ciphers included in the
Go standard library by passing an explicit cipher suite list.
The ciphers included here are more line with those recommended by
Mozilla for "Intermediate" compatibility. [0]
*Performance Implications*
The Go standard library does capability-based cipher ordering,
preferring AES ciphers if the underlying hardware has AES specific
instructions. [1] Since all of the relevant code is internal modules,
to do the same thing ourselves would require duplicating that
code. Here, I've placed …

Use a more conservative set of CipherSuites

---

connector/gitlab/gitlab.go

Fixes: https://github.com/dexidp/dex/issues/1518

gitlab: add groups scope by default when filtering is requested

---

.gitignore
server/handlers.go
server/templates.go
server/templates_test.go
web/templates/header.html

Fixes #1553 
This PR makes sure every template refers to its local assets using a URL relative to the request's URL.
For example:
server listens at localhost/dex so serverPath is dex
reqPath is /dex/auth
assetPath is static/main.css
relativeURL("/dex", "/dex/auth", "static/main.css") = "../static/main.css"
I had to propagate the request's path from each handler down to the templates' data.
I chose to pass the whole http request as a parameter to the template render functions, as it may contain other useful information in the future (eg values from context).
I can change it to only pass down the request's path if it's preferable.
Signed-off-by: Yannis Zarkadas <yanniszark@arrikto.com>

server: templates: use relative URLs to refer to assets

---

storage/sql/config.go

MySQL 5.7.20 introduced the `transaction_isolation` system variable, so pre 5.7.20 versions won't work with Dex MySQL storage (like AWS Aurora currently). This PR adds some basic detection logic for those use cases. See https://github.com/dexidp/dex/pull/1485#issuecomment-533977858 for more details. Once we can't get rid of the `SERIALIZABLE` requirement, this logic can be removed.

storage/mysql: support pre-5.7.20 instances with tx_isolation only

---

README.md
connector/connector.go
connector/github/github.go
connector/gitlab/gitlab.go
connector/ldap/ldap.go
server/handlers.go
server/oauth2.go
storage/etcd/types.go
storage/kubernetes/types.go
storage/sql/crud.go
storage/sql/migrate.go
storage/storage.go

Signed-off-by: Nandor Kracser <bonifaido@gmail.com>
Implemented preferred_username in ID Token for:
- GitHub
- GitLab
- LDAP
TODO:
Fixes: #1076

add preffered_username to idToken

---

connector/oidc/oidc.go

If you have an oidc connector configured *and* that IDP provides thin
tokens (e.g. okta) then the majority of the requested claims come in the
getUserInfo call (such as email_verified). So if getUserInfo is
configured it should be run before claims are validated.

Run getUserInfo prior to claim enforcement

---

Documentation/connectors/saml.md
connector/saml/saml.go
connector/saml/saml_test.go

I'm not suggesting this should be taken as is, but I wanted to use it as a conversation starter on adding SAML support for group filtering. This is based on conversation in #1476 
I thought briefly about a generalized approach but right now I just wanted to get a primitive implementation vetted and ideally merged, and then follow that with figuring out what it looks like across providers.
Obviously, there are no tests or docs in this change.

Adding support for allowed groups in SAML Connector

---

server/handlers.go

Missed `preferred_username` claim added on refresh handler.

preferred_username claim added on refresh token

---

Documentation/connectors/oidc.md
connector/oidc/oidc.go

There's been some discussion in #1065 regarding what to do about
refreshing groups. As it stands today dex doesn't update any of the
claims on refresh (groups would just be another one). The main concern
with enabling it is that group claims may change more frequently. While
we continue to wait on the upstream refresh flows, this adds an option
to enable the group claim. This is disabled by default (so no behavioral
change) but enables those that are willing to have the delay in group
claim change to use oidc IDPs.
Workaround to #1065

Add option to enable groups for oidc connectors

---

Documentation/connectors/google.md
connector/google/google.go

Many other providers support this feature already, so Google can't be left out.

connector/google: support group whitelisting

---

connector/oidc/oidc.go
connector/oidc/oidc_test.go

`ouath2.RegisterBrokenAuthHeaderProvider()` is deprecated and now behaves as a noop.
This modifies `connector/oidc` to set `oauth2.Endpoint.AuthStyle` in its place. 
The `sync.Mutex` that guarded `oauth2.RegisterBrokenAuthHeaderProvider` became vestigal, so it was removed.

Deprecated oauth2.RegisterBrokenAuthHeaderProvider

---

server/handlers.go
server/templates.go
web/static/main.css
web/templates/login.html

We are picking icons by provider ID. For example:
1. User can type anything into ID field.
2. ID field don't match any css class name with icon
3. User have no icon even if he picked provider with predefined icon (github, gitlab, etc.)
Using type field will make user always have icons for all providers on login screen.
Because we know all possible provider types and can prepare icons for them.
Only icons that don't fit into the logic now is google-icon.svg and coreos-icon.svg.

Pick icons on login screen by connector type instead of ID

---

Documentation/connectors/openshift.md
README.md
connector/openshift/openshift.go
connector/openshift/openshift_test.go
server/server.go

Support for authenticating against OpenShift

OpenShift connector

---

storage/sql/config.go

The upstream package that Dex uses for MySQL storage support has the following bug https://github.com/go-sql-driver/mysql/issues/674.
This addition to the config.go file removes the dex based default of 5 idle DB connections when using the go-SQL-driver for MySQL.
fixes issue https://github.com/dexidp/dex/issues/1608

Fixed mysql EOF issue

---

connector/oidc/oidc.go
connector/oidc/oidc_test.go

This helps to avoid "no email claim" error if the email scope was not specified.
Closes #1598

Adding oidc email scope check

---

connector/google/google.go

The list of groups is paginated (default page is 200), so when a user
has more than 200 groups, only the first 200 are retrieve.
This change is retrieving all the groups for a user by querying all the
pages.

google: Retrieve all the groups for a user

---

server/server.go

Before the PR, Dex will break if `PrometheusRegistry` is not provided. IMHO that field doesn't need to be required unless there is a specfic reason (?).
With this PR, if user is not interesting at collecting Dex metric through Prometheus, one could config a Dex server without `PrometheusRegistry`.

Optional Prometheus Registry

---

Documentation/connectors/ldap.md
connector/ldap/ldap.go
connector/ldap/ldap_test.go
examples/config-ad-kubelogin.yaml
examples/config-ldap.yaml

**This PR changes Dex LDAP connector config structure!**
Add an ability to fetch user's membership from groups of a different type by specifying multiple group attribute to user attribute value matchers in the Dex config:
```yaml
groupSearch:
userMatchers:
- userAttr: uid
groupAttr: memberUid
- userAttr: DN
groupAttr: member
```
In other words the user's groups can be fetched now from ldap structure similar to the following:
dn: cn=john,ou=People,dc=example,dc=org
objectClass: person
objectClass: inetOrgPerson
sn: doe
cn: john
uid: johndoe
mail: johndoe@example.com
userpassword: bar
dn: cn=qa,ou=Groups,ou=Portland,dc=example,dc=org
objectClass: groupOfNames
cn: qa
member: cn=john,ou=People,dc=example,dc=org
dn: cn=logger,ou=UnixGroups,ou=Portland,dc=example,dc=org
objectClass: posixGroup …

connector/ldap: add multiple user to group mapping

---

Documentation/kubernetes.md

In 58093dbb2 the kubernetes documentation was updated to refer to CRDs
rather than TPRs when discussing how storage works for dex. However, the
rest of the line was not updated and still referred to the TPR section,
whose anchor link was changed in 395febf80 with the removal of TPR
support. This change updates the kubernetes documentation to point to
the currect section of the storage documentation for CRDs.

Fix kubernetes storage link

---

Documentation/kubernetes.md

Hi,
A proposal to remove a "caveat" from the page.
Here are some different supporting factors:
- The warning is 3 years old.
- The issue it references has been closed. #682.
- I've tested an instance of k8s dex with TLS & health checks. It worked.
- The project dex-k8s-authenticator has an example dex chart with TLS & health checks. That's been available for some time.
- When k8s does a probe: "If scheme field is set to HTTPS, the kubelet sends an HTTPS request _skipping the certificate verification_."  Since certificate verification is skipped, there shouldn't be a problem with a custom CA.

update doc regarding health check

---

cmd/dex/config.go
cmd/dex/serve.go
examples/config-dev.yaml
server/handlers.go
server/oauth2.go
server/server.go

As per comment https://github.com/dexidp/dex/pull/1163#issuecomment-572975220, this PR from [ConcourseCI](https://github.com/concourse) team is a rework of https://github.com/dexidp/dex/pull/1163 since the original PR is outdated and its author allowed us to continue his work. 
cc @pivotal-jwinters 
@bonifaido thanks!

Rework - add support for Resource Owner Password Credentials Grant

---

storage/sql/config.go
storage/sql/migrate.go
storage/sql/migrate_test.go
storage/sql/sql.go

Furthermore increase `auth_request.state` length to 4096 in MySQL because JWT states can easily exceed the current limit and get cut, which causes weird login issues. Postgres and SQLite is not affected because they are using `TEXT`.
Fixes: #1658

storage/sql: allow specifying sql flavor specific migrations

---

connector/openshift/openshift.go
connector/openshift/openshift_test.go

Automatically sets the email field to be based on the username for the OpenShift connector

Setting email for OpenShift connector

---

Documentation/connectors/oidc.md
connector/oidc/oidc.go

For OIDC offline_access, the `prompt` used to be hardcoded to `consent`:
```
opts = append(opts, oauth2.AccessTypeOffline, oauth2.SetAuthURLParam("prompt", "consent"))
```
However, in some OIDC provides this value is not supported (e.g. OneLogin: https://developers.onelogin.com/openid-connect/api/id-token) where it states:
> Optional. If used must be set to one of the following:
> - login - The user will be prompted with a login dialog.
> - none - The user will not be prompted with a login dialog. If they do not have a current session a login_required error will be returned.
> 
This adds the `promptType` param, set by default to `consent` but with the ability to explicitly set it in the config and override it.

Make prompt configurable for oidc offline_access

---

cmd/dex/serve.go
storage/storage.go

Having ID and Secret in clear inside configuration files for static
clients is not ideal. This commit allows setting these from environment
variables.
Signed-off-by: Yann Soubeyrand <yann.soubeyrand@gmx.fr>
Rebased Yann's changes from: https://github.com/dexidp/dex/pull/1428

storage/static.go: expand environment variables in client ID and secret

---

.github/workflows/ci.yml

Signed-off-by: Nandor Kracser <bonifaido@gmail.com>
Somehow MySQL started to fail in recent CI runs, see: https://github.com/dexidp/dex/pull/1673/checks?check_run_id=516025437
Also the MySQL service is scheduled for removal from the default image: https://github.community/t5/GitHub-Actions/github-actions-cannot-connect-to-mysql-service/m-p/31578/highlight/true#M831

ci: add mysql service

---

server/handlers.go

There is a chance that offline storage could fall out of sync with the
refresh token tables. One example is if dex crashes/is stopped in the
middle of handling a login request. If the old refresh token associated
with the offline session is deleted, and then the process stops, the
offline session will still refer to the old token.
Unfortunately, if this case occurs, there is no way to recover from it,
since further logins will be halted due to dex being unable to clean up
the old tokens till referenced in the offline session: the database is
essentially corrupted.
There doesn't seem to be a good reason to fail the auth request if the
old refresh token is gone. This changes the logic in `handleAuthCode` to
not fail the entire transaction if the old refresh token could not be
deleted …

handlers: do not fail login if refresh token gone

---

storage/kubernetes/client.go

When constructing the host address string, the address is
not wrapped in square brackets. This does not work in IPv6
Kubernetes deployments. This commit adds square brackets
around the address. IPv4 was also tested to ensure it works
with wrapped address.
fixes #1643
Signed-off-by: Jerry Sun <jerry.sun@windriver.com>

Wrap Kubernetes host address in square brackets

---

server/handlers.go

In case of missing refresh token in db application will return 500 when user tries to issue new refresh token.
This PR adds automatic consistency fixing in case of missing refresh token in db by ignoring missing one. This could happen in case of interrupted write.

Automatic consistency fixing in case of missing refresh token in db

---

connector/keystone/keystone.go
connector/keystone/keystone_test.go

_Note: This is a replacement of #1442 as the original author hasn't been responsive, but is still a valuable contribution. I've rebased from master._
After the successful login to keystone, the Email of the logged in user
is fetch from keystone and provided to `identity.Email`.
This is useful for upstream software that uses the Email as the primary
identification.
_Note: Email is now required when using Dex with a Keystone Backend and pusher/oauth2_proxy@v5.0.0_

Added Email of Keystone to Identity

---

storage/conformance/conformance.go
storage/kubernetes/types.go

storage/kubernetes: remove shadowed ResourceVersion from Connector

---

README.md

Adds a section on the slack channel to the README
- Fixes #1682

Adding slack channel to README

---

Documentation/connectors/openshift.md

Serviceaccount annotation in oc patch instruction was malformed. Format
specification of Client ID for a Service Account was missing.

Documentation: Fix typo and add specification in openshift connector doc

---

Documentation/connectors/atlassian-crowd.md
README.md
connector/atlassiancrowd/atlassiancrowd.go
connector/atlassiancrowd/atlassiancrowd_test.go

**What this is**
In the current implementation, the `preferred_username` claim remains empty. Some clients might require that claim and Dex supports it, if set from the connector's side.
This PR allows the connector to **optionally** support the `preferred_username` claim. It achieves this by allowing a user to choose to fill the `preferred_username` claim by one of the available Crowd fields. Specifically: `key`, `name` or `email`. Invalid options cause the claim to remain empty.
**Breaking change:** No. Existing configuration should not notice this change.
**Optional:** Yes.
**Notes:**
- Added test for `identityFromCrowdUser` function which was not extensively tested before
- Added entry for the Crowd connector in the readme
- Updated documentation for the connector
- I'm fairly new to …

Allow preferred_username claim to be set for Crowd connector

---

cmd/dex/serve.go

For statically-configured public clients it should be allowed for both
Secret and SecretEnv fields to be empty.

allow no secret for static public clients

---

connector/github/github.go

PR for this issue: https://github.com/dexidp/dex/issues/1699

create github oauthconfig with redirecturl

---

web/static/img/oidc-icon.svg
web/static/main.css

Add the SVG icon for the OIDC providers ([the one that Wikipedia uses](https://commons.wikimedia.org/wiki/File:Openid.svg)).

Add icon for OIDC provider

---

Documentation/connectors/saml.md
connector/saml/saml.go
connector/saml/saml_test.go

This should make AllowedGroups equivalent to an LDAP group filter:
When set to true, only the groups from AllowedGroups will be included in the
user's identity.
This is not the great refactoring where all the connectors use some common logic, but just another band-aid to provide some useful functionality to SAML users. 
------
Fixes #1476

connector/saml: add 'FilterGroups' setting

---

Documentation/connectors/gitea.md
README.md
connector/gitea/gitea.go
connector/gitea/gitea_test.go
server/server.go

This PR adds Gitea as a connector for Dex.
Note: As documented, this new connector doesn't yet support Groups claim, however as Gitea offers a similar API to Github, it could be added in as a later PR.

Add Gitea connector

---

connector/google/google.go
examples/config-dev.yaml

Fixes #1718
--------
The code *did* originally have a check for empty adminEmail and empty serviceAccountFilePath, but didn't check this when loading the config - so tried to open an empty filename.
With this fix, token refresh works when using the "google" connector instead of the "oidc" connector to talk to Google, even without a hosted domain.

Allow the "google" connector to work without a service account

---

docker-compose.yaml
examples/config-dev.yaml
storage/sql/config_test.go

This PR tries to resolve the pain of testing different storage options quickly. I have added different almost all storage options/versions (except Kubernetes CRDs) and included the corresponding Dex config counterparts as well.

add docker-compose.yaml for local testing

---

connector/microsoft/microsoft.go

Without this scope, a refresh token will not be returned from Microsoft

dexidp#1440 Add offline_access scope, if required

---

.github/workflows/ci.yml
.github/workflows/release.yml
Dockerfile

Adding architecture support for arm/arm64/amd64 docker images using docker `buildx` functionality.
Tested arm64 running on a local Kubernetes cluster to confirm it was working without issues.
Signed-off-by: Michael Fornaro <20387402+xUnholy@users.noreply.github.com>

Adding architecture support for arm/arm64/amd64 docker images

---

server/templates.go
server/templates_test.go

#1554 breaks the ability to specify an icon for header using external URL like [this one](https://kubernetes.io/images/favicon.png).
I added check, that if assetURL points to external URL, no transformations required.

Fix templates which asset path points to external URL

---

server/server.go

Allow user to provide a static key for signing without rotation.

Add constructor for static key strategy

---

Documentation/connectors/bitbucketcloud.md
connector/bitbucketcloud/bitbucketcloud.go
connector/bitbucketcloud/bitbucketcloud_test.go

Replace deprecated `/teams` API endpoint with the actual one `/user/permissions/teams`.
Support of `/teams` endpoint ends 14 October 2020. 
* With this PR, we do not need `teams` scope to access user teams anymore
* Output of endpoints differs a little
Closes #1811
P.S. I also tested these changes with changes from #1688. Everything works fine and looks compatible despite there are some conflicts in tests between these PRs.

fix: Replace deprecated teams endpoint in bitbucket connector

---

Documentation/connectors/bitbucketcloud.md
connector/bitbucketcloud/bitbucketcloud.go
connector/bitbucketcloud/bitbucketcloud_test.go

This PR provides support for team groups.  The only option added is `includeTeamGroups`. When the option value is `true`,  we make an additional request to Bitbucket API to get all team group names and combine them with the team name using `/`.
The groups claim in dex id_token looks like:
* Without option: `groups=["my_team"]`
* With option: `groups=["my_team", "my_team/administrators", "my_team/members"]`
I started working on it because there was no chance to do authn/authz management in the frames of one team. This behavior is something that other connectors already has (github, gitlab).
My only concern is sending a request to deprecated API to get team groups. However, Atlassian said, that `/groups` endpoint would be supported until the equal method would appear in 2.0 API.

feat: Add team groups support to bitbucket connector

---

Dockerfile

The Dockerfile was changed to do
COPY web .
which is unfortunate because that means copy the *contents* of the directory
"web", rather than copying the directory itself which is what the author
intended.
Issues: #1820
Signed-off-by: Alastair Houghton <alastair@alastairs-place.net>

fix: copy the "web" directory.

---

server/server.go

The Authorization header needs to be allowed when doing CORS because
otherwise /userinfo can't work.  It isn't one of the headers
explicitly allowed by default by Gorilla, so we have to call
handlers.AllowedHeaders() to specify it.
Fixes #1532

fix: allow Authorization header when doing CORS

---

storage/kubernetes/storage.go
storage/kubernetes/storage_test.go

Running two dex instances in HA mode in the Kubernetes cluster, we are constantly receiving messages like this from one instance:
```json
{"level":"info","msg":"keys rotated, next rotation: 2020-10-08 15:33:14.700531412 +0000 UTC","time":"2020-10-08T09:33:14Z"}
```
And errors from another instance:
```json
{"level":"error","msg":"failed to rotate keys: PUT https://*****/apis/dex.coreos.com/v1/namespaces/******/signingkeies/openid-connect-keys Conflict: response from server \"{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Operation cannot be fulfilled on signingkeies.dex.coreos.com \\\"openid-connect-keys\\\": the object has been modified; please apply your changes to the latest version and try …
```

fix: Handle Kubernetes API conflicts properly for signing keys

---

.golangci.yml
Makefile
cmd/dex/config.go
connector/atlassiancrowd/atlassiancrowd.go
connector/authproxy/authproxy.go
connector/github/github.go
connector/google/google.go
connector/ldap/ldap.go
connector/saml/saml.go
server/api_test.go
server/deviceflowhandlers.go
server/deviceflowhandlers_test.go
server/handlers.go
server/server.go
server/server_test.go
server/templates.go
storage/conformance/conformance.go
storage/kubernetes/k8sapi/client.go
storage/kubernetes/types.go
storage/sql/config.go
storage/sql/crud.go
storage/static.go
storage/storage.go

There is a naughty warning in the "Run linter" CI job logs:
```
[runner] Can't run linter goanalysis_metalinter: ST1001: failed prerequisites:...
```
Examples: [1](https://github.com/dexidp/dex/runs/1264022987?check_suite_focus=true), [2](https://github.com/dexidp/dex/runs/1247767485?check_suite_focus=true), [3](https://github.com/dexidp/dex/runs/1260081191?check_suite_focus=true)
Bumping the golangci-lint version to the actual one fixes the problem. It requires golangci-linter configuration changes because the `enable-all` option was marked as deprecated. Users have to use the `disable-all` option and manually enable linters they want.
I also fixed some style problems to enable the following linters:
- golint
- gochecknoinits
- gocritic
- ineffassign
- nakedret
- staticcheck
- varcheck …

fix: Bump golangci-lint version and fix some linter's problems

---

connector/ldap/ldap.go
server/handlers.go

fix: Minor style fixes after merging PKCE implementation

---

storage/kubernetes/storage.go
storage/kubernetes/storage_test.go

Kubernetes provides API consistency through `resourceVersion` field. Updating resource with a higher resource version than contained in storage cause conflict errors. Users may encounter such errors, which is unwanted behavior. In my opinion, it's good just to retry a failed request in case of conflict.

feat: Retry Kubernetes update requests

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

**Overview**:
This PR adds issues templates and pull request template according to [this documentation](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests)
Templates make it easier to maintain the project.
* Bug report template will help with collecting the necessary information for debugging
* Pull request and feature request templates will help people to think about why they open / would like to open a PR
Adding them will standardize the communication process between maintainers and users.

chore: Add description templates

---

server/oauth2.go
server/oauth2_test.go

Relates to:
* https://github.com/dexidp/dex/pull/1722 (also allow usual IP addresses)
* https://github.com/dexidp/dex/pull/1784 (PKCE)

Allow public clients (e.g. SPAs using implicit flow or PKCE) to have redirect URLs other than localhost

---

storage/sql/config.go
storage/sql/config_test.go
storage/sql/crud_test.go
storage/sql/migrate_test.go
storage/sql/sqlite.go
storage/sql/sqlite_test.go

**Overview**:
Split the SQLite storage backend into a separate file and add a build tag so dex can compile when cgo is disabled.
`github.com/mattn/go-sqlite3` requires cgo, which causes the entire `storage/sql` package to fail to compile:
```
go test ./storage/...
?   	github.com/dexidp/dex/storage	[no test files]
?   	github.com/dexidp/dex/storage/conformance	[no test files]
storage/sql/sqlite.go:40:22: undefined: sqlite3.Error
storage/sql/sqlite.go:44:33: undefined: sqlite3.ErrConstraintPrimaryKey
storage/sql/migrate_test.go:26:22: undefined: sqlite3.Error
storage/sql/migrate_test.go:30:33: undefined: sqlite3.ErrConstraintUnique
```

Don't try to build sqlite storage when cgo isn't enabled

---

Dockerfile

Signed-off-by: Martin Heide <martin.heide@faro.com>
**Overview**:
- Add go.mod + go.sum to Dex docker image.
- Inventory of Go modules for analysis of CVEs and open source licenses.
- Important for commercial projects.
**Special notes for a reviewer**:
Example inventory result from WhiteSource:

Copy module dependencies to Docker image for CVE scanning / dependency analysis

---

.github/workflows/ci.yml
cmd/dex/config.go
cmd/dex/config_test.go

Closes https://github.com/dexidp/dex/issues/1876
See issue + release note below.
@sagikazarmark I guess this one is for you, since you commented on the issue.
```release-note
By setting the env variable `DEX_EXPAND_ENV` to `false`, the user can disable env expansion in storage and connector configs.
This is an opt-in change: Env expansion is still enabled by default.
It can be useful to disable env expansion to avoid workarounds e.g. if you use templating to generate dex-config.yaml, and some of your values (e.g. the LDAP bindPW) may include dollar characters.
```

Allow to disable os.ExpandEnv for storage + connector configs by env variable DEX_EXPAND_ENV = false

---

examples/config-dev.yaml

Update path reference in documentation example.
The example path probably doesn't exist, and even if it does, the filename is pretty much certainly wrong.
```release-note
NONE
```

docs: Correct tlsClientCA example reference

---

connector/authproxy/authproxy.go

This is a small PR to allow configuration of the header returned by the auth proxy.
We are using traefik as reverse proxy + traefik-forward-auth plugged on google to access our argocd interface.
But in traefik-forward-auth, the returned header after authentication is `X-Forwarded-User`.
With this feature, we can now login to argocd using the dex config :
```
connectors:
- type: authproxy
id: traefik
name: traefik
config:
headerName: X-Forwarded-User
```
dex will fetch the header set by traefik forward auth and authenticate the user with the correct user email.

Allow configuration of returned auth proxy header

---

examples/config-dev.yaml
server/server.go
web/themes/dark/styles.css

* Add frontend section to `examples/config-dev.yaml`
* Fix stale code commentaries
* Minor fixes dark theme colors
The initial intention of this PR was to add a frontend settings section to ease fronted development. Playing with the example-app and frontend settings, I found outdated commentaries and possible improvements for dark theme colors. To avoid spamming with PRs, the fixes were included in this one.
Nothing that should be added to release notes.

chore: add frontend section to dev config

---

storage/conformance/conformance.go
storage/etcd/etcd.go
storage/etcd/types.go

This change fixes a bug in the PKCE implementation when using `etcd` as the storage engine. As of v2.27.0, this combination is broken and a `code_verifier` cannot be used to request a token. 
Specifically, you will get an errant error `No PKCE flow started. Cannot check code_verifier` error when requesting `/token` despite the fact that a `code_challenge` and `code_challenge_method` were indeed provided to `/auth`.
This PR also adds a PKCE AuthCode round-trip check to the storage conformance tests. Indeed that test fails on v2.27, and now it passes 🙏 .
- In `CreateAuthCode`, the etcd storage implementation uses `fromStorageAuthCode()` to convert a `storage.AuthCode` into the etcd variant.
- In `GetAuthCode`, however, the implementation attempts to directly unmarshal the json into the …

Fix the etcd PKCE AuthCode deserialization

---

server/server.go
storage/storage.go

A little fix to log garbage collected amount of device codes and device requests.
```release-note
Fix garbage collection logging of device codes and device request 
```

fix: log device flow entities GC result if no auth entities collected

---

server/oauth2.go
server/oauth2_test.go

* Used a constant as the first argument of newErr method
* Replaced error state "invalid_requests" with "invalid_request" in case of receiving no response_type
* Added a test
According to https://tools.ietf.org/html/rfc6749#section-3.1.1, the state `invalid_requests` is invalid (and it looks like a typo). 
To avoid similar errors in the future, this PR replaces all state arguments with constants.
Correct error on empty response_type is required to pass the OpenID certification.
The only user-facing change is replacing invalid_requests with invalid_request.

Use constants to form oauth2 error responses

---

server/handlers.go

* Update claims_supported
* Update token_endpoint_auth_methods_supported
Dex supports sending client credentials via post but doesn't say about it on discovery. The same about claims.
Adding `client_secret_post` to auth metods is required to pass Basic OpenID certification tests.
```release-note
Discovery endpoint contains updated claims and auth methods.
```

fix: update auth methods and claims from discovery endpoint

---

server/deviceflowhandlers.go
server/handlers.go
server/server_test.go

* Add headers
* Add tests
https://tools.ietf.org/html/rfc6749#section-5.1
> The authorization server MUST include the HTTP "Cache-Control"
response header field [RFC2616] with a value of "no-store" in any
response containing tokens, credentials, or other sensitive
information, as well as the "Pragma" response header field [RFC2616]
with a value of "no-cache".
It is also ok (and better) to add Cache-Control header to device authorization response as in the example in https://tools.ietf.org/html/rfc8628#section-3.2
Cache headers are required to pass the OpenID certification.
```release-note
Add "Cache-control: no-store" and "Pragma: no-cache" headers to token responses
```

Add Cache-control headers to token responses

---

server/oauth2.go
server/server_test.go

Check the "request" in auth request and throw an error if found. 
According to the [specification](https://openid.net/specs/openid-connect-core-1_0.html#JWTRequests), an error is added. There is a [specification for error responses](https://openid.net/specs/openid-connect-core-1_0.html#AuthError).
Sending an error is required to pass OpenID certification tests.  The previous test suite allows completely ignoring this parameter, but after migrating to the new suit treating the request parameter correctly becomes mandatory.
https://openid.net/specs/openid-connect-core-1_0.html#JWTRequests
```release-note
Return an error to auth requests with the "request" parameter.
```

fix: unsupported request parameter error

---

cmd/dex/serve.go
go.mod
go.sum

Add graceful shutdown mechanism to all servers:
* HTTP
* HTTPS
* Telemetry
* grpc
Closes #1942
```release-note
Graceful shutdown.
```

feat: graceful shutdown

---

examples/ldap/config-ldap.yaml
examples/ldap/docker-compose.yaml

Signed-off-by: Martin Heide <martin.heide@faro.com>
The OpenLDAP example config didn't cover LDAPS yet.
It helps OpenLDAP users to run an example with LDAPS.
The secure configuration "3)" with `insecureSkipVerify: false` worked for me before.
Because of https://github.com/osixia/docker-openldap/issues/506 , it doesn't work out of the box any more with the current Docker image.
```release-note
NONE
```

Extend OpenLDAP example for LDAPS

---

server/handlers.go
server/handlers_test.go

Change returning error for invalid auth codes.
The https://tools.ietf.org/html/rfc6749#section-5.2 says that we MUST return invalid_grant error for invalid auth codes.
Returning correct (according to RFC) errors is required to pass OpenID certification tests.
```release-note
Return invalid_grant error if auth code is invalid or expired.
```

fix: return invalid_grant error for invalid or expired auth codes

---

server/handlers.go
server/oauth2.go

This PR adds support for c_hash on the id_token.
The c_hash is required in the hybrid flow, and optional otherwise.
According to https://openid.net/specs/openid-connect-core-1_0.html#CodeValidation
> If the ID Token is issued from the Authorization Endpoint with a code, which is the case for the response_type values code id_token and code id_token token, this is REQUIRED; otherwise, its inclusion is OPTIONAL.
**OpenID Connect Certification**
The test (OP-IDToken-c_hash) now succeeds

Add c_hash to id_token, issued on /auth endpoint, when in hybrid flow

---

web/templates/approval.html

Improve template for the case where a client requests only "openid" scope and nothing else (i.e. no "profile", "email" etc)
Before:
After:
Closes #1732
Only a correction to a web page displayed when granting access

Improve "Grant Access" template when client requests only openid scope

---

cmd/dex/serve.go

Call the `Close` method on storage in case of graceful shutdown
Closes #1523
```release-note
Close storage on graceful shutdown
```

fix: close storage on shutdown

---

server/api.go

**Overview**:
Allows public clients created with the API to have no client_secret to support the PKCE flow.
Closes: #1870. Now all clients with no client_secret created by the API gets a random secret. This adds a check if the client is public and allows for empty client_secret if that is the case.

Allow public clients created with API to have no client_secret

---

.github/workflows/ci.yaml
connector/ldap/ldap_test.go

Explicitly launch LDAP tests
After merging #1997, it became impossible to use `make test` or `go test ./...` locally without a mock LDAP server. 
```release-note
NONE
```

fix: do not run LDAP tests locally by default

---

Dockerfile
cmd/dex/serve.go
config.yaml.dist
server/server.go
server/templates.go
web/web.go

Embed web assets into the Dex binary
This change should simplify the distribution of Dex since it won't rely on the filesystem (except the config).
It also simplifies configuration since we don't need a default value anymore.
Fixes  #1959
```release-note
Default web asset location is changed to none (users should remove it from their configuration)
Web assets in the official container image are moved to `/srv/dex/web`
```

Embed web assets

---

README.md

Delete go.dev badge
This badge is confusing a little because it leads to the page with stale documentation.
It was previously discussed here https://github.com/dexidp/dex/pull/2087
```release-note
NONE
```

chore: remove go dev badge from README

---

connector/microsoft/microsoft.go

Signed-off-by: Erica Taylor <ricky@wellplayed.games>
This PR adds a `promptType` field to the configuration of the Microsoft connector.
Closes #1911.
This allows users of Dex to specify which kind of prompt the Microsoft connector should display. Previously this used the default value which didn't prompt unless the user was signed out of Microsoft.
```release-note
The prompt type which the Microsoft connector uses can now be configured with the `promptType` setting.
Valid values are `login`, `none`, `consent` and `select_account`.
```

Support setting the prompt type for the Microsoft connector

---

.github/workflows/ci.yaml
storage/sql/config.go

The MySQL storage connector now uses the `port` field to allow connecting to MySQL instances running on a non-standard port.
Fixes #2098
```release-note
Fix MySQL connection to use the provided port
```

Fix MySQL connection to use the provided port

---

.github/SECURITY.md
README.md

This is an initial version of the security policy. I've already requested a dedicated email address (`security@dexidp.io`) for this purpose. I will update the policy once that's set up, but it shouldn't block this PR.
Fixes #1617
Fixes #1867

Initial security policy

---

server/deviceflowhandlers.go
server/handlers.go
server/server.go
server/server_test.go

[rfc6749#section-3.2](https://tools.ietf.org/html/rfc6749#section-3.2)
* Make `/token` endpoint responding to requests with device auth grant
* Allow only POST requests `/token` endpoint
* Do not search for a client in storage if an invalid grant type is provided
Fixes https://github.com/dexidp/dex/issues/1953 
As was mentioned in the issue above, the main problem that the token endpoint is not discoverable.
This MR leaves the possibility to get a token from the `/device/token` endpoint. 
There are no breaking changes, but it will be better to avoid using /device/token endpoint in the feature.
```release-note
Make `/token` endpoint responding to requests with device auth grant. The `/device/token` endpoint becomes DEPRECATED.
```

fix: use /token endpoint to get tokens with device flow

---

Makefile
cmd/dex/serve.go
cmd/dex/version.go
server/api.go
server/api_test.go
version/version.go

* Delete "version" package
* Inject version variable in two places
Closes https://github.com/dexidp/dex/issues/1944
I thought about this issue. It seems that injecting the version twice  (during the build stage) as good as injecting it once and then importing it two times. There is no possibility to import the version anymore, though (which was our goal).
```release-note
Discard package "version."
```

Discard package "version"

---

.golangci.yml
Makefile
server/handlers.go
server/oauth2.go
storage/ent/client/offlinesession.go
storage/memory/memory.go
storage/storage.go

* Bump golangci-lint
* Replace the [deprecated](https://github.com/golangci/golangci-lint/issues/1892) `golint` with the closest linter by its features - `revive`
> Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint.
* Fix some bugs
* Add lint-fix command to Makefile
Maintenance.
```release-note
NONE
```

Bump golag-ci lint version to 1.40.1

---

examples/k8s/dex.yaml

Fix the error
Readiness probe failed: Get "http://100.105.5.5:5556/healthz": dial tcp 100.105.5.5:5556: connect: connection refused
Client sent an HTTP request to an HTTPS server.
```release-note
```

set readinessProbe to https

---

.github/workflows/ci.yaml
cmd/dex/config.go
storage/ent/client/authrequest.go
storage/ent/client/client.go
storage/ent/client/connector.go
storage/ent/client/devicetoken.go
storage/ent/client/keys.go
storage/ent/client/main.go
storage/ent/client/offlinesession.go
storage/ent/client/password.go
storage/ent/client/refreshtoken.go
storage/ent/postgres.go
storage/ent/postgres_test.go
storage/ent/sqlite_test.go
storage/ent/types.go

* Add constructor for Postgres storage
* Tests for Postgres storage bootstrapping
* Connect conformance tests
Related #1864
Composing DSN method and storage structure are mostly copypasted from the "raw SQL" storage. I think they are good enough to continue using them.
```release-note
Add an experimental ent-based postgres storage.
```

feat: Add ent-based postgres storage

---

go.mod
go.sum
scripts/manifests/crds/authcodes.yaml
scripts/manifests/crds/authrequests.yaml
scripts/manifests/crds/connectors.yaml
scripts/manifests/crds/devicerequests.yaml
scripts/manifests/crds/devicetokens.yaml
scripts/manifests/crds/oauth2clients.yaml
scripts/manifests/crds/offlinesessionses.yaml
scripts/manifests/crds/passwords.yaml
scripts/manifests/crds/refreshtokens.yaml
scripts/manifests/crds/signingkeies.yaml
storage/kubernetes/client.go
storage/kubernetes/k8sapi/crd_extensions.go
storage/kubernetes/storage.go
storage/kubernetes/types.go

* add Kubernetes version discovery mechanism
* create crds as apiextensions.k8s.io/v1 for kubernetes clusters >= 1.16
Fixes #1895
There is no test that proves crds creation in kubernetes clusters >= 1.10 works (related to #1999).
It is not a breaking change.
```release-note
kubernetes storage: create custom resource definitions as apiextensions.k8s.io/v1
```

feat: create CRDs as apiextensions.k8s.io/v1

---

storage/kubernetes/client.go
storage/kubernetes/client_test.go

If Dex fails to get namespace from the token or variable name, read it from the service account namespace file
Related https://github.com/dexidp/dex/issues/2082
Fixed some minor issues in this PR:
* Dial -> DialContext (because Dial is deprecated and DialContext is a direct substitution)
* context -> k8sContext to avoid overlapping with imported package
* Make some variables constant
```release-note
Get namespace for Kubernetes storage client in a cluster from the service account namespace file as a fallback.
```

fix: read namespace from file for Kubernetes storage client

---

storage/kubernetes/client.go
storage/kubernetes/client_test.go
storage/kubernetes/storage.go
storage/kubernetes/transport.go

In Kubernetes 1.21 [BoundServiceAccounTokenVolume](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume) is enabled by default.
Related #2082
I looked through the client-go code and did the same.
```release-note
Update service-account token periodically if Dex is running in Kubernetes cluster
```

feat: Update token periodically if Dex is running in Kubernetes cluster

---

connector/mock/connectortest.go
server/handlers.go
server/handlers_test.go

Using dex with the kubernetes oidc client results in the creation
of an Offline Session with empty ConnectorData.
This results in a working login, however, the ldap connector will fail once the client attempts to refresh its token.
This change will insert the ConnectorData from the initial Login
into the OfflineSession, as already done in `handlePasswordLogin`.
Not doing this results in failures to refresh a token.
I've observed this with the ldap connetor, other connectors might
be affected as well.
The ldap connector will fail with this error message:
`failed to refresh identity: ldap: failed to unmarshal internal data: unexpected end of JSON input`
The `Refresh` method of the ldap connector will first try to unmarshal
the ConnectorData, which was empty, as dex wouldn't
store it in …

handlePasswordGrant: insert connectorData into OfflineSession

---

storage/sql/sqlite.go

Takes care of issue in https://github.com/dexidp/dex/issues/2153
```release-note
NONE
```

storage/sql: use only one sqlite3 connection

---

examples/config-dev.yaml
examples/k8s/dex.yaml

Include an example command using `htpasswd` to bCrypt passwords in `staticPasswords` sections in example config files.
The former text
> bcrypt hash of the string "password"
is rather vague and not helpful if you are attempting to add your own static password here. I had to Google tools for running bCrypt from the command line, and found by trial and error that the default difficulty level of 5 is rejected by Dex (requires 10).
N/A
Just examples, so I think not.
```release-note
NONE
```

Demonstrate use of `htpasswd` for bCrypt in `staticPasswords`

---

server/handlers.go
server/oauth2.go
server/oauth2_test.go
server/server_test.go

**Overview**:
Fixes several unrelated problems related to auth flow error handling
1) Fixes a case of wrong error returned in case of unsupported grant type (according to RFC should be "unsupported_grant_type", not "invalid_grant").
2) Fixes "connector not found" error displayed in an inconsistent not-end-user-friendly way (errTokenHelper used instead of renderError)  
3) Makes errors related to invalid connector in parseAuthorizationRequest redirect back to the client (as RFC states that after client_id/redirect uri is validated, all further errors should be redirected to client)
4) Makes two type of errors returned from parseAuthorizationRequest explicit (either redirected error or displayed error)
This PR partially fixes #1796 
**Special notes for a …

Improve auth flow error handling

---

examples/k8s/dex.yaml

Bump Dex image to v2.30.0 for Kubernetes deployment example
Signed-off-by: Radoslav Dimitrov <dimitrovr@vmware.com>
The Dex version in the Kubernetes yaml file is outdated and also has the issue of failing with newer Kubernetes releases caused by the way namespace is read.
The following PR bumps the Dex version used in the Kubernetes deployment example to v2.30.0 (which includes the fix for the namespace failure issue).
```release-note
```

Bump Dex image to v2.30.0 for Kubernetes deployment example

---

.golangci.yml
cmd/dex/serve.go
connector/atlassiancrowd/atlassiancrowd.go
connector/atlassiancrowd/atlassiancrowd_test.go
connector/bitbucketcloud/bitbucketcloud.go
connector/gitea/gitea.go
connector/github/github.go
connector/gitlab/gitlab.go
connector/google/google.go
connector/keystone/keystone.go
connector/keystone/keystone_test.go
connector/ldap/ldap.go
connector/ldap/ldap_test.go
connector/linkedin/linkedin.go
connector/openshift/openshift.go
connector/saml/saml.go
connector/saml/saml_test.go
examples/example-app/main.go
examples/grpc-client/client.go
server/deviceflowhandlers_test.go
server/server_test.go
storage/conformance/gen_jwks.go
storage/kubernetes/client.go
storage/kubernetes/client_test.go
storage/kubernetes/transport.go
storage/sql/config.go

The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
> The io/ioutil package has turned out to be a poorly defined and hard to understand collection of things. -- https://golang.org/doc/go1.16#ioutil
> Avoid meaningless package names. Packages named util, common, or misc provide clients with no sense of what the package contains. -- https://go.dev/blog/package-names
The Golang team has decided to deprecate the `io/ioutil` package and recommends new code to use the new definitions. To avoid inconsistency in the future, it is a good idea to move all current usage of `io/ioutil` functions to the new definitions.
No breaking changes. …

refactor: move from io/ioutil to io and os package

---

storage/ent/mysql.go

Fix after merging https://github.com/dexidp/dex/pull/2272
Ioutil is a deprecated package.
```release-note
NONE
```

chore: fix ioutil lint error after merging MySQL ent storage

---

server/handlers.go
server/server.go

Signed-off-by: ariary <ariary9.2@hotmail.fr>
Modify the discovery endpoint result. The grant type supported are no longer fully "hard-coded". 
The discovery endpoint is used to  help client application to know how dex is configured for the sign-in flow.
Currently the grant types supported were hard-coded, which does not always match the dex configuration.
The aim of this PR is to add `password` in the grant type supported list if it is the case 
```release-note
NONE
```

Add parametrization of grant type supported in discovery endpoint

---

server/templates.go

I test dex on Win10 platform, i found it dont launch success, I try to solve this problem, found slash convert is be necessary.
It should also be able to run on Linux.
```release-note
```

fix web static file path slash error for win platform

---

server/refreshhandlers.go
server/server_test.go

Change the error returned. Add tests.
According to [rfc6749](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2), it is required to return the `invalid_grant` error if the refresh token from the request was issued for another client.
It is required to pass the OIDC conformance test:
> Attempting to use refresh_token issued to client 2 with client 1: CheckErrorFromTokenEndpointResponseErrorInvalidGrant: 'error' field has unexpected value
```release-note
Return the invalid_grant error on claiming token of another client.
```

fix: return invalid_grant error on claiming token of another client

---

connector/ldap/ldap.go
pkg/log/deprecated.go
server/deviceflowhandlers.go

* print warning message if deprecated fields are used
* calculate user matches only on the connector opening
We cannot remove deprecated fields without letting users know about our intentions.
Users will see a warning message in dex logs if they have deprecated fields in their LDAP connector config.
```release-note
ldap: deprecation warning about `groupSearch.userAttr` and `groupSearch.groupAttr`
```

chore: warning about deprecated LDAP groupSearch fields

---

Makefile

> "this script is deprecated, please do not use it anymore. check https://github.com/goreleaser/godownloader/issues/207"

chore: update golangci-lint download script

---

connector/bitbucketcloud/bitbucketcloud.go
connector/bitbucketcloud/bitbucketcloud_test.go

Signed-off-by: Rahul M Chheda <rahul.chheda@accurics.com>
Bitbucket's `/teams` endpoint is now decrecated: https://developer.atlassian.com/cloud/bitbucket/rest/api-group-teams/#api-teams-get
Resolves: https://github.com/dexidp/dex/issues/2391
Not a lot of changes here.
Nope
```release-note
- Replace `/teams` API w/ `/workspaces`
```

[fix] Replace /teams API w/ /workspaces endpoints

---

README.md
connector/authproxy/authproxy.go

Added `groupHeader` and `groups` configuration for authproxy connector. 
Example :
```
connectors:
- type: authproxy
id: http-proxy
name: http-proxy
config:
userHeader: X-Forwarded-User # default is X-Remote-User
groupHeader: X-Forwarded-Group # default is X-Remote-Group
staticGroups:
- admin
```
This allow users to configure argocd dex to use authproxy connector and specify the users default group and the HTTP header to read to get the group.

Allow configuration of returned groups via authproxy connector

---

connector/oidc/oidc.go

This PR adds acr_values support for the OIDC connection
Fixes: #2417 
yes, a new non-mandatory field is introduced called `acrValues` in the config of the OIDC connection

feat: Add acr_values support for OIDC

---

Dockerfile

This bump Alpine to the latest version.
This bumps Alpine to the latest version and fixes a high CVE -2022-0778 that was fixed in Alpine 3.15.2
```release-note
Bump Alpine to 3.15.4
```

Bump Alpine to latest version

---

.github/workflows/artifacts.yaml
.github/workflows/docker.yaml
Dockerfile

Build distroless images
Fixes #2406
```release-note
```

Publish official distroless images

---

server/refreshhandlers.go

Log only errors.
If a user goes to the token refreshing endpoint with no existed token, it floods logs with the not found error.
```
{"level":"error","msg":"failed to get refresh token: not found","time":"2022-04-06T06:14:17Z"}
```
It is ok. Dex used to skip these errors previously. They accidentally came out after the token refreshing handler refactoring.
```release-note
fix: log only errors on refreshing a token
```

fix: log only errors on refreshing

---

.github/workflows/artifacts.yaml

Revert the matrix build to a single built job per base image.
Apparently matrix builds don't work with multi-platform images.
See https://github.com/docker/build-push-action/issues/130
```release-note
NONE
```

Build multi-platform images in a single build job

---

connector/openshift/openshift.go
connector/openshift/openshift_test.go

This introduces a new function for the OpenShift connector with the ability to inject a `http.Client` for usage. This will enable us to i.e. modify the `x509.CertPool` and support adding system specific certificates as trusted within library usage.
We are currently using dex as a library within our application running on OpenShift as a containerized workload.
When using the connector in combination with the internal OAuth server of OpenShift, they OAuth server may be either 
1. internally exposed, whereas the certificate will be explicitly added under a specific mount point.
2. exposed externally, behind a OpenShift route and a certificate the cluster admin chose.
Since we want to cover both cases ideally when using it as a library, it would be nice to have some way of telling the …

Create setting to allow to trust the system root CAs

---

connector/oauth/oauth.go
connector/oauth/oauth_test.go

Signed-off-by: Shuanglei Tao <tsl0922@gmail.com>
Add numeric user ID support for oauth connector
```release-note
Add numeric user ID support for oauth connector
```

Add numeric user ID support for oauth connector

---

connector/oidc/oidc.go

Signed-off-by: Anthony Brandelli <abrandel@cisco.com>
At some point in the evolution of dex it seems like some Google specific stuff got left in the OIDC connector, when there is now a Google specific one. 
I would like to gather feedback on this PR whether it makes sense to remove this, given that there could be users out there who are utilizing the OIDC connector but using Google as their IDP, instead of using the Google connector. I don't want to break people, but I also think this stuff is pretty 
Originally added in https://github.com/dexidp/dex/pull/974 which is before the Google connector was split out here https://github.com/dexidp/dex/pull/1185. I believe that this is just a miss since then, I am unaware of any other IDPs (but of course I am not aware of everyone's configuration) …

Remove google specific hd / hosted domain claim config from oidc connector

---

.github/workflows/artifacts.yaml
.github/workflows/docker.yaml

Try to build dex without using cache and see the impact
There are a lot of failed docker builds, and their nature is unknown. Most of the time job freezes after preparing the cache
```
2022-05-06T04:34:03.2162689Z 
2022-05-06T04:34:03.2162791Z #79 exporting cache
2022-05-06T04:34:03.2163057Z #79 preparing build cache for export
2022-05-06T04:35:07.8469443Z #79 preparing build cache for export 64.7s done
2022-05-06T10:06:23.6107579Z ##[error]The operation was canceled.
2022-05-06T10:06:23.6170814Z Post job cleanup.
2022-05-06T10:06:23.7425906Z ##[group]Removing temp folder /tmp/docker-build-push-x2GXuu
2022-05-06T10:06:23.7426866Z ##[endgroup]
```
I would like to build Dex images without caching and see how it affects building time (and …

chore: do not use caching for docker build

---

connector/oidc/oidc.go
connector/oidc/oidc_test.go

Signed-off-by: Anthony Brandelli <abrandel@cisco.com>
I broke https://github.com/dexidp/dex/pull/2505 with a bad rebase, this is a PR off a fixed branch, sorry for the confusion @nabokihms 
Allows for dex to function with IDPs that do not return an ID token in the reply when using a refresh_token grant.
Although this seems to be rare, the OIDC spec does not require that an id_token be present in the reply when using a refresh_token grant. Additional info in https://github.com/dexidp/dex/issues/2498.
This is a toggle in PingFed, so there is at least one common IDP out there where there won't always be a refresh token.
Closes https://github.com/dexidp/dex/issues/2498
Note that if a user has an IDP where ID tokens aren't present when using a refresh_token grant, AND also chooses not to …

OIDC connector: Support cases where there is no id_token when using a refresh_token grant

---

.golangci.yml

2m -> 4m
An example of a timed out job
https://github.com/dexidp/dex/runs/6526055941?check_suite_focus=true
```release-note
NONE
```

Bump lint timeout to reduce the number of failed executions

---

cmd/dex/config.go
cmd/dex/serve.go
examples/config-dev.yaml

Add profiling endpoints for the Dex telemetry server.
Related to #778
```release-note
feat: enable profiling endpoints
```

feat: enable profiling endpoints

---

storage/kubernetes/client.go
storage/kubernetes/storage.go

If something causes the number k8s resources to increase beyond a
certain threshold, garbage collection can fail because the query to
retrieve those resources will time out, resulting in a perpetual cycle
of being unable to garbage collect resources.
In lieu of trying to get *every* object each cycle, we can limit the
number of resources retrieved per GC cycle to some reasonable number.

Limit the amount of objects we attempt to GC on each cycle

---

config.yaml.dist

Add expiry.refreshToken settings to `config.yaml.dist`
config-dev.yaml is "deprecated" and these settings aren't mentioned anywhere else, so to ensure users know the available configuration options, these should be added to `config.yaml.dist`
```release-note
Add expiry.refreshToken settings to config.yaml.dist
```

Add expiry.refreshToken settings to config.yaml.dist

---

connector/gitlab/gitlab.go
connector/gitlab/gitlab_test.go

Use GitLab's `refresh_token` instead of `acces_token` during `connector.Refresh` when `offline_access` is specified.
Closes #2316 
```release-note
Fix GitLab connector to use refresh_tokens with `offline_access`
```

Use GitLab's refresh_token during Refresh.

---

connector/microsoft/microsoft.go
connector/microsoft/microsoft_test.go

This PR implements the solution proposed in https://github.com/dexidp/dex/issues/2585 to accelerate users logins using the Microsoft Connector when multiple sessions are present.
Closes #2585
Adds optional `domainHint` string configuration parameter to the Microsoft Connector
When `domainHint` is configured, the Microsoft Connector will encode the string as `domain_hint` in the Authorization Code URL.
Added 2 new tests to cover the `TestLoginURL` function in the Microsoft Connector.
```release-note
Adds optional `domainHint` configuration parameter to the Microsoft connector to streamline logins for single-tenant deployments.
```

Add domainHint parameter to Microsoft Connector

---

server/deviceflowhandlers.go
server/deviceflowhandlers_test.go
storage/conformance/conformance.go
storage/ent/client/devicetoken.go
storage/ent/client/types.go
storage/ent/db/devicetoken.go
storage/ent/db/devicetoken/devicetoken.go
storage/ent/db/devicetoken/where.go
storage/ent/db/devicetoken_create.go
storage/ent/db/devicetoken_update.go
storage/ent/db/migrate/schema.go
storage/ent/db/mutation.go
storage/ent/db/runtime.go
storage/ent/schema/devicetoken.go
storage/etcd/etcd.go
storage/etcd/types.go
storage/kubernetes/types.go
storage/sql/crud.go
storage/sql/migrate.go
storage/storage.go

This adds support for the PKCE `code_challenge` and `code_verifier` values defined in RFC7636 when using the device code flow. This is especially useful when a client secret can not be used for SPA. 
Signed-off-by: Bob Callaway <bcallaway@google.com>

add PKCE support to device code flow

---

connector/microsoft/microsoft.go

Adds a new configuration option for the Microsoft connector to explicitly declare the scopes to be requested in tokens
[Users have noted](https://github.com/sigstore/fulcio/issues/157) that requesting a default scope of `user.read` (aka `profile`) vs `["openid", "email"]` may be too broad for a simple ID token. This PR allows for the Microsoft connector configuration to explicitly set the minimum scope to something other than `user.read` (per Microsoft [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent)), which is available in other similar connectors.
New config option for connector
Signed-off-by: Bob Callaway <bcallaway@google.com>

add config to explicitly set scopes for microsoft connector

---

connector/oidc/oidc.go
connector/oidc/oidc_test.go

When using the OIDC provider, in combination with Microsoft ADFS using OpenID, groups can be filtered on Microsoft's side. Whenever the result of this filtering consists of only one group, the response back to Dex will be a string instead of an array of strings.
**OIDC response examples:**
_Response with multiple groups:_
```json
{
"aud": "microsoft:identityserver:XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX",
"iss": "http://domain.acme.com/adfs/services/trust",
"iat": 1661346019,
"exp": 1661349619,
"email": "myemailaddress@acme.com",
"given_name": "Henk",
"family_name": "Vries, De",
"unique_name": "Vries, Henk de",
"winaccountname": "henkie",
"groupsid": [
"K8s_P_Group1",
"K8s_P_Group2"
],
"group": [
"K8s_P_Group1",
"K8s_P_Group2"
],
"apptype": "Confidential",
"appid": …
```

fix: Fallback when group claim is a string instead of an array of strings

---

connector/authproxy/authproxy.go
connector/authproxy/authproxy_test.go

Added support to use multiple values for group header on authproxy connector.
If you use multiples values using comma-separated, the connector can't understand there are different groups.
Definition to use comma-separated list [RFC2616 section 4.2](https://www.rfc-editor.org/rfc/rfc2616#section-4.2)
```
NONE
```

feat(connector/authproxy): support multiple groups

---

connector/keystone/keystone.go
connector/keystone/keystone_test.go

Refactors the Keystone connector to reduce the number of instantiations of HTTP clients.
Improves performance and reduces boilerplate.
```release-note
NONE
```

Reduce HTTP client creations in the Keystone connector

---

connector/google/google.go
connector/google/google_test.go

This (hopefully) reverts a bug introduced in #2530 which does not handle the case where application default credentials nor a service account file (containing credentials) are needed to operate a Google connector.
Fixes: #2670 
NONE
```release-note
fixes regression for Google connector when used without groups
```
Signed-off-by: Bob Callaway <bcallaway@google.com>
@ichbinfrog

fix for issue 2670; check for no serviceAccountFilePath and no email

---

storage/conformance/transactions.go

commit 49471b14c8080ddb034d4855841123d378b7a634 has a failing test case due to the lack of specification of an HMACKey
https://github.com/dexidp/dex/actions/runs/3144248007/jobs/5110000846
Signed-off-by: Bob Callaway <bcallaway@google.com>

supply HMACKey in test case

---

go.mod
go.sum

Update golang.org/x packages

---

server/refreshhandlers.go
storage/kubernetes/lock.go
storage/kubernetes/storage.go
storage/kubernetes/storage_test.go

This PR moves the external provider refresh call to the transaction. If the underlying Dex storage has a proper locking mechanism, in combination with the `reuseInterval` option for all concurrent requests, Dex will call refresh for an external provider only once.
Closes https://github.com/dexidp/dex/issues/2547
```release-note
Refresh the id token only once for all concurrent requests. Fixes errors on token refreshing for Gitlab/OIDC providers.
```

fix: refresh token only once for all concurrent requests

---

connector/google/google.go
connector/google/google_test.go

This PR backports #2695 to v2.35.x
See the above PR for details.

Backport #2694 to v2.35.x

---

connector/google/google.go
connector/google/google_test.go

Make admin email optional when no service account path is configured
This PR reverts #2679 and attempts to fix the original regression reported in #2670 (supposedly introduced in #2530; released in 2.34.0).
The behavior after this PR should be identical to the original behavior IF a service account is configured.
According to #2670 admin email doesn't work when default credentials are used. We need more information on that though for a permanent fix.
@jonkerj do you have anything else to share other than "there was something wrong with default application credentials"?
Also fixes regression reported in #2694 (caused by #2679).
Backport PR also submitted in #2696
I had no way of testing this change at this time.
```release-note
Fix regression introduced in #2679
```

Make admin email optional when no service account path is configured

---

Dockerfile

Backport Go update to v2.35.x

---

connector/google/google.go
go.mod
go.sum

Only initialize google admin service if necessary
Fixes #2699

Only initialize google admin service if necessary

---

Dockerfile

Backport https://github.com/dexidp/dex/pull/2705 to v2.35.x

Backport #2705 to v2.35.x

---

server/refreshhandlers.go
server/server_test.go

There is a possibility that connector data will be saved to refresh token, which can lead to refresh tokens invalidation.
The flow of connectorData is too complicated. I opened an issue to think about it in the future.
See https://github.com/dexidp/dex/issues/2728
```release-note
Do not use connector data from the refresh token field.
```

fix: Do not use connector data from the refresh token field

---

connector/github/github.go
connector/github/github_test.go

This PR is a revamped version of https://github.com/dexidp/dex/pull/1298.
It allows identifying users by verified company email without marking it as primary.
This PR adds new `preferredEmailDomain` config option for GitHub connector.
If set, an email address with the specified domain takes precedence over the primary email.
When a user is logged into a service that uses Dex, such as ArgoCD, via GitHub, the user is identified by the account's primary email address.
However, in a company, we have the following needs:
* Identify employees by their company domain email address
* Allow employees to use their own(not-for-only-work) GitHub account
To satisfy these, we need an option that can return a specific domain email address as the user's email address.
N/A
```release-note
Add new …
```

Add preferredEmailDomain config option for GitHub connector

---

connector/google/google.go
connector/google/google_test.go

Removed the unique function and integrated into `getGroups` to reduce the number of calls to google.
Depending on the groups a user belongs to the current code can make several extraneous calls to google. This can occur either when a user has several indirect memberships to a group or when the user has both an indirect and direct membership to a group:
```
user -> [one, two, three]
one -> [numbers]
two -> [numbers]
three -> [numbers]
numbers -> []
user -> [foo, bar]
foo -> [bar]
bar -> []
```
Implementing a standard map setup reduces calls to google down to `number of groups + original user`.
I'm not sure if google allows it, but it also eliminates a stack overflow if there was a circular membership:
```
user -> [one]
one -> [two]
two -> [three]
three -> [one]
```
```release-note
NONE
```

Move unique functionality into getGroups to reduce calls to google

---

storage/kubernetes/client.go
storage/kubernetes/storage_test.go

Validate kubernets object names on the Dex side
For some endpoints, we directly get data out of a user request and build a URL for the request to Kubernetes API out of it.
The problem does not look urgent, because Dex always builds the prefix of the URL on his side, yet we need to protect API from malicious or invalid requests.
https://cwe.mitre.org/data/definitions/918.html
```release-note
fix: prevent server-side request forgery using Kubernetes storage
```

fix: prevent server-side request forgery using Kubernetes storage

---

.golangci.yml
Makefile
connector/atlassiancrowd/atlassiancrowd.go
connector/connector.go
connector/google/google_test.go
connector/microsoft/microsoft.go
connector/saml/saml.go
connector/saml/saml_test.go
server/oauth2.go
server/templates.go
storage/ent/postgres.go
storage/kubernetes/client.go
storage/kubernetes/lock.go
storage/kubernetes/transport.go
storage/sql/config.go
storage/sql/crud.go
storage/storage.go

Updates the version of golangci-lint defined in the Makefile.
Versions prior to v1.48.0 are incompatible with go v1.19, which is in use since d33e9948059abe45257cc6b734870b2c4f3c4ea5.
Linting fails:
```console
❯ go version
go version go1.19.2 linux/amd64
❯ make bin/golangci-lint
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | BINARY=golangci-lint bash -s -- v1.46.0
golangci/golangci-lint info checking GitHub for tag 'v1.46.0'
golangci/golangci-lint info found version: 1.46.0 for v1.46.0/linux/amd64
bgolangci/golangci-lint info installed ./bin/golangci-lint
❯ bin/golangci-lint run
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt
goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.22() …
```

chore: Upgrade golangci-lint to v1.50.1 from v1.46.0

---

connector/oidc/oidc.go

Fix for an error (it occurs when the `getUserInfo` is set to true and a custom ca is used)
A fix for https://github.com/dexidp/dex/pull/1632
This is a fix for the feature that is not released.
```release-note
NONE
```

fix: propagate http client to userInfo requests for OIDC connector

---

server/handlers_test.go
server/templates.go

This will help to distinguish errors and successful requests.
Context https://github.com/dexidp/dex/pull/2454#issuecomment-1080514456
```release-note
Requests with invalid passwords are responded to with the 401 error code.
```

fix: return 401 if password is invalid

---

storage/storage.go

Fixes https://github.com/dexidp/dex/pull/1424
```release-note
chore: Add a comment about config/email JSON tag bug
```

chore: Add a comment about config/email JSON tag bug

---

server/server.go
server/templates.go
web/robots.txt
web/web.go

To avoid Dex being accidentally scraped by robots.
```release-note
Add default robots.txt
```

feat: Add default robots.txt

---

server/handlers.go
server/handlers_test.go
server/server_test.go

Fixes #2686.
Skip redirection to `/approval` if it is not required.
I've locally made `handleApproval` always return an error.
And I ran tests and confirmed that it does not fail (= `/approval` is not accessed).
```release-note
enhance: Skip redirection to `/approval` when it's not required
```

Skip redirection to approval when it is not required (#2686)

---

Makefile
go.sum

Fix failing CI jobs
Some of the `generate` commands add entries to the root go.mod file. To avoid changes, as a quick fix, executing go-mod-tidy should be the last step.
```release-note
NONE
```

fix: Run go mod tidy last (fix verify command)

---

docs/enhancements/token-exchange-2023-02-03-#2812.md

DEP for RFC 8693 OAuth 2.0 Token Exchange / grant_type urn:ietf:params:oauth:grant-type:token-exchange
Discussion / design requested before implementation
```release-note
NONE
```

DEP for RFC 8693 OAuth 2 Token Exchange

---

server/handlers.go
server/handlers_test.go

Skip redirect to approval only if skip approval is enabled and the approval prompt is not forced.
Fixes https://github.com/dexidp/dex/issues/2875
```release-note
Fix the bug when Dex skips approval screen by default
```

fix: Do not skip approval screen by default

---

Dockerfile

Add xx to test cross-compilation: https://github.com/tonistiigi/xx
Speed up container image builds
```release-note
NONE
```

Add xx to cross-compile binaries in Docker

---

connector/ldap/ldap.go
connector/ldap/ldap_test.go

Make `DN` field case-insentitive for attributes getters.
If `dn` or `Dn` is used as an attribute selector, Dex silently ignore it and does not return any values. The real problem is when `dn` is used to bind groups.
Example:
```yaml
userMatchers:
- userAttr: member
groupAttr: dn
```
With the snippet above users will always have empty groups.
```release-note
feat: Make LDAP connector DN attribute field case-insensitive.
```

LDAP case-insensitive DN attribute

---

connector/oidc/oidc.go

Fail if the hostedDomains option is specified in an OIDC connector config
The option was removed. After the upgrade, users still using OIDC connectors for their Google providers may accidentally open access to more people than before.

Fail if OIDC config contains hosted domains

---

Makefile
scripts/git-diff

Utilize native git diff feature
This `--exit-code` option does exactly what the script is doing
Removes the need to maintain a script that does same with more code.
```release-note
```

Utilize native git diff --exit-code

---

cmd/dex/serve.go
go.mod
go.sum

reloads certificates from disk on file change or SIGHUP
#2814
Not sure if it's necessary to expose a config option to disable this?
The linked https://github.com/shaj13/tlsreconciler repo appears to no longer exist on github.
```release-note
TLS certificates are automatically reloaded on file changes or SIGHUP.
```

tls cert reloader

---

cmd/dex/config.go
cmd/dex/config_test.go
cmd/dex/serve.go
connector/connector.go
connector/mock/connectortest.go
connector/oidc/oidc.go
connector/oidc/oidc_test.go
server/handlers.go
server/handlers_test.go
server/oauth2.go
server/oauth2_test.go
server/refreshhandlers.go
server/server.go
server/server_test.go

Implement [RFC 8693](https://www.rfc-editor.org/rfc/rfc8693.html) which specifies exchanging third party tokens for native ones.
There are times when we wish to grant machines access to a protected endpoint without using long-lived, static API keys or user/password combinations.
Many modern execution environments can expose short-lived OIDC tokens for the duration of the execution, examples include:
- [GCP Service Identity](https://cloud.google.com/run/docs/securing/service-identity)
- [AWS Execution Role](https://docs.aws.amazon.com/lambda/latest/dg/lambda-intro-execution-role.html)
- [Github Actions OIDC](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect)
- [CircleCI …

RFC 8693 OAuth 2.0 Token Exchange

---

examples/config-dev.yaml

Followup to #2806 with adding grantTypes to the example config
Document the new `oauth2.grantTypes` field.
```release-note
NONE
```

include granttypes in example config

---

server/oauth2.go
server/server.go

DEX can support multiple-valued response type combinations ([spec](https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#Combinations)) but doesn't display it on the server endpoint :
[https://<idp_url>/.well-known/openid-configuration](https://<idp_url>/.well-known/openid-configuration)
This PR fixes this issue.
Some applications will check the ``response_types_supported`` retrieved from the following URL : [https://<idp_url>/.well-known/openid-configuration](https://<idp_url>/.well-known/openid-configuration) before performing any flow.
DEX servers will only display the following supported response types :
```json
"response_types_supported": [
"code",
"id_token",
"token"
]
```
Since DEX can support multiple-valued response type combinations, this field should display : …

feat: Update response_types_supported to allow multiple-valued response type combinations

---

connector/oidc/oidc.go
connector/oidc/oidc_test.go

Followup on #2806 for better access token handling.
verify access tokens by checking getuserinfo during a token exchange
The provider.Verifier.Verify endpoint we were using only works with ID tokens. This isn't an issue with systems which use ID tokens as access tokens (e.g. dex), but for systems with opaque access tokens (e.g. Google / GCP), those access tokens could not be verified. Instead, check the access token against the getUserInfo endpoint.
```release-note
NONE
```

verify access tokens by checking getuserinfo during a token exchange

---

README.md

fix k8s link in readme.md
The link https://kubernetes.io/docs/admin/authentication/#openid-connect-tokens  is now a 404.
```release-note
NONE
```

doc:fix k8s link in readme.md

---

server/handlers.go
server/handlers_test.go

Create offline sessions only if they are supported by the connector and if the user requests it with the scope `offline_access`.
Extend handler tests to verify this behavior.
This PR resolves the bug described in https://github.com/dexidp/dex/issues/3124
```release-note
Store offline sessions only if they are supported and were requested by the user
```

Store offline sessions only if they were requested by the user

---

connector/oidc/oidc.go

Filter users based on groups in OIDC connector.
Currently it is not possible to filter users based on groups like it is done with the `google` connector. This PR is an attempt to support group filtering in the `oidc` connector. The connector configuration takes an additional configuration as below to specify what the allowed groups are. If the user's groups belong to at least one of the `allowedGroups`, then authentication will be successful. The other change is to indicate that the user does not belong to allowed groups if authentication fails because the user does not belong to any of the allowed groups.
```
{
"name": "My-oidc",
"config": {
"issuer": "<ISSUER>",
"clientID": "12345678",
"redirectURI": "<Dex Callback>",
"clientSecret": "12345678",
"insecureSkipEmailVerified": true, …
```

Minimalistic support for group filtering in oidc connector

---

connector/microsoft/microsoft.go

Support custom API and graph URLs in Microsoft/Azure connector.
From #2459
> This change makes the Azure endpoints configurable.  For most users, the default 
> https://login.microsoftonline.com/ and https://graph.microsoft.com/ values 
> will remain the correct choice, but this allows users of Azure in special 
> regions, such as Government Cloud Services for export-controlled workloads, 
> to use the Microsoft connector to get group membership.
Fixes #2457
Fixes #2459
I was not able to test this change as I don't have access to such environments.
```release-note
Support custom api and graph URLs in Microsoft/Azure connector
```

feat(connector/microsoft): support custom api and graph URLs

---

cmd/dex/config.go
cmd/dex/serve.go
server/server.go

The CORS enforced endpoints only allow the `Authorization` header by default, and this behavior is not configurable.  For some environments, it is desirable to allow configuration of which headers should be accepted (e.g. when using Swagger UI with a Dex IDP, which for instance inserts a `x-requested-with` header to the CORS preflight check).
This PR allows the `AllowedHeaders` for CORS endpoints to be configurable, so that the host can decide if headers should be rejected or not.  By default, the `Authorization` header will be accepted to not interfere with any existing setups of Dex if no `allowedHeaders` are defined in the `config.yaml` file.
Yes
```release-note
Adds a configuration option `allowedHeaders` in the `web` section of `config.yaml` to change which headers are accepted on …
```

feat: Add configurable CORS Headers

---

connector/authproxy/authproxy.go
connector/authproxy/authproxy_test.go

This PR adds support for some additional headers to be propagated into claims in the authproxy connector.
I am using Dex with authproxy to turn an existing IdP, whose code is not under my control, into an OIDC provider. I want to be able to propagate the user ID and email address from the underlying IdP as OIDC claims alongside the username, which is not possible with the current headers and claims supported by the authproxy connector.
This PR adds support for two extra headers that can be used to propagate the user ID and email from the underlying IdP, and sets the claims. When these additional headers are not set, it reduces to the previous mode.
```release-note
Adds support for two additional headers, for user ID and email, to the authproxy connector.
```

Add support for extra claims to authproxy connector

---

cmd/dex/config.go
cmd/dex/serve.go
server/server.go

Fix linter errors after merging https://github.com/dexidp/dex/pull/3114

Fix lint errors after merging AllowedHeaders feature

---

.github/PULL_REQUEST_TEMPLATE.md

It was a copy-paste from Kubernetes, which we never used. As of today, to compose release messages, we use GitHub mechanism that uses PR titles and commits.
```release-note
```

Remove user-facing changes section from PR template

---

cmd/dex/config.go
pkg/featureflags/flag.go
pkg/featureflags/set.go

Dex is a piece of software used in production in many companies. Introducing breaking changes is what we try to avoid.
It makes sense to hide some crucial changes behind a feature flag. Before, we introduced a couple of particular environment variables for this purpose. 
This PR generalizes the approach for new feature flags in Dex.
How to implement, use, and find a feature flag in the code needs to be clarified. This PR aims to define and standardize the concept of feature flags.
The improvement to make the codebase cleaner.

Introduce a dedicated pkg for featureflags

---

.github/workflows/artifacts.yaml

Use cosign to sign container images (simple keyless method).
Signing container images enhances security by ensuring the integrity and authenticity of deployed images, reducing the risk of tampering and unauthorized modifications. It establishes a trust chain, confirming that the deployed image aligns with the developer's intent, thereby bolstering the security of your containerized applications.
Related https://github.com/dexidp/dex/issues/2865

Sign container images

---

cmd/dex/config.go
cmd/dex/config_test.go
cmd/dex/serve.go
config.yaml.dist

Add configuration options for TLSMinVersion and TLSMaxVersion.
This enables configuring specific TLS versions to accept. That allows use-cases such as setting TLS 1.3 as minimum version (disables TLS 1.2), or enforcing TLS 1.2 only (disables TLS 1.3) for easier debugging of secure connections.
Default functionality of Go TLS is to allow TLS 1.2 and TLS 1.3 and have client and server negotiate. (Except in Dex 2.37.0 where TLS 1.0 to TLS 1.3 were always enabled).
`serve.go` doesn't have any unit tests, so didn't add any. Unit tests are added for `config.go`.
This can be tested with `sslyze` for example:
1. Generate certs `cd examples/k8s; ./gencert.sh`
2. `cp config.dev.yaml config.yaml`
3. Add following under `web:`
```yaml
https: 127.0.0.1:5554
tlsCert: examples/k8s/ssl/cert.pem
tlsKey: …
```

feat: add TLS versions configuration

---

connector/authproxy/authproxy.go
connector/authproxy/authproxy_test.go

The `authproxy` connector only sets the `preferred_username` but not `username`. This causes issues with some OIDC clients that don't fallback to `preferred_username`.
One example here is `rallly` but I also noticed that there's no username when using dex with WikiJS.
In addition to `preferred_username`, the authproxy connector now also set's the `Username` field on the `connector.Identity`

Also set the username in authproxy connector

---

connector/oidc/oidc.go

This small changes fixes an issue in the token exchange flow. It explicitly sets the tokenType used for `GET /userinfo` to `Bearer` to be conform with the OIDC spec.
Without this change the tokenType would be set to either `urn:ietf:params:oauth:token-type:access_token` or `urn:ietf:params:oauth:token-type:id_token`, which doesn't satisfy the OIDC spec.
> The Access Token obtained from an OpenID Connect Authentication Request MUST be sent as a Bearer Token, per Section 2 of [OAuth 2.0 Bearer Token Usage](https://openid.net/specs/openid-connect-core-1_0.html#RFC6750) [RFC6750].
https://openid.net/specs/openid-connect-core-1_0.html#UserInfo (5.3.1)
Closes https://github.com/dexidp/dex/issues/3335

fix(tokenExchange): use correct token type for userInfo requests

---

server/handlers.go

Remove evaluation of skipApproval on approval page
The Pull Request https://github.com/dexidp/dex/pull/2897 caused a bug when using `oauth2.skipApprovalScreen: true` together with a client setting `approval_prompt=force` during the request. The tests validated correctly that the user gets redirected to `/approval` in this case, but the handler of the approval page contains some code which immediately returns the auth code if `oauth2.skipApprovalScreen: true` is set and ignores the `approval_prompt` parameter. Since there is a TODO comment to remove this check after some time, I guess it can be removed now to fix that issue.
```release-note
Fix a bug that Dex ignores approval_prompt=force when skipping approval screen is enabled as default behavior
```

fix: Do not evaluate skipApproval on approval page

---

server/handlers.go

Signed-off-by: i-amelia <viktoria.lyomcheva@gmail.com>
This PR adds logging of failed login attempts when using PasswordConnector. It will help to detect & alert brute force password attacks.
```release-note
NONE
```

Log failed login attempt

---

connector/ldap/ldap.go
connector/ldap/ldap_test.go

this patch draws error when queys (i.e. account / password) against ldap contain wildcard. 
fixes #3354 
not sure whether it would impact the existing usecases or not, but I an open to accept additional switcher to on/off.

fix: add sanitizer to ldap account and password

---

cmd/dex/config.go
cmd/dex/config_test.go
cmd/dex/serve.go
examples/config-dev.yaml
server/server.go
server/server_test.go

Customization of headers in the authentication server is crucial for enforcing stringent security measures by allowing the inclusion of specific headers required for authentication protocols and compliance standards. This customization ensures that authentication requests are processed securely, mitigating potential vulnerabilities and ensuring adherence to security policies.
Related https://github.com/dexidp/dex/discussions/3320

Add headers control to dex web server

---

Dockerfile

Updated the Distroless image to Debian 12
gcr.io/distroless/static is Debian 10, which is quite outdated. Updated to the Debian 12 version of the static image, and used the nonroot tag since the root user isn't needed.
We've been running a version of Dex in production with this image without issue.

Update Distroless to Debian 12

---

storage/kubernetes/client.go

https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names
Update max length of kubernetes object to fit kubernetes policy.
We faced an errror with oauth2 clients with id longer than 63 symbols (77 in particular).
```
{"level":"error","msg":"Failed to get client: invalid kubernetes resource name: must match the pattern ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and be no longer than 63 characters","time":"2024-03-28T19:20:09Z"}
{"level":"error","msg":"Failed to parse authorization request: Database error.","time":"2024-03-28T19:20:09Z"}
```

Update max length of kubernetes object to fit kubernetes policy

---

.github/workflows/checks.yaml

- run release note label ci only in dexidp/dex repo not in forks

chore: run release note label ci only in dexidp/dex repo not in forks

---

.github/workflows/artifacts.yaml

- use the default cosign version from the action
not pinning the cosign version helps to be always up-to-date and depends only in the action update

use the default cosign version from the action

---

connector/ldap/ldap.go

With the change introduced in https://github.com/dexidp/dex/pull/3372 Dex declines passwords that contain special characters. Since password is not passed to any kind of filters, it is safe to pass a password as is. No LDAP query injections are possible.
This commit is a revert of password escaping.
Related https://github.com/dexidp/dex/issues/3433

Do not escape password for LDAP connectors

---

connector/google/google.go
connector/google/google_test.go
connector/oidc/oidc.go

Add support for configurable prompt type for Google Connector. Reference https://github.com/dexidp/dex/issues/3450
- Allows the user to explicitly configure the value of `prompt` parameter in login URL generated by Google connector
Ref https://github.com/dexidp/dex/issues/3450
The original ask was to avoid the user experience of consent screen every time authentication flow goes through `dex` into Google by skipping `prompt=consent` flag. As per OIDC specification, there is no valid value for `prompt` param to achieve this. So this PR just allows the ability to set the value of `prompt` parameter through configuration. Setting an explicit `""` (empty) value for prompt should be functionally equivalent for skipping it for Google connector

feat: Add support for configurable prompt type for Google connector

---

.github/workflows/artifacts.yaml
.github/workflows/ci.yaml
.github/workflows/release.yaml

Add Provenance Attestation using GitHub Action and sigstore (https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/)
This adds the provenance attestation and push the attestation to the same registry as the image.
- per a limitation for the action it only pushes to `ghcr.io` and not to docker.io 
Rehearsal: 
job: https://github.com/cpanato/dex/actions/runs/9252829376/job/25451249054
attestation: https://github.com/cpanato/dex/attestations/921641 and attestation image: `ghcr.io/cpanato/dex@sha256:8e5d24d7a0f0fe95bbdf6722e1c724075d5d4c15cfa8d0ef4959f25103e12bac ` 
to verify
```
$ gh attestation verify oci://ghcr.io/cpanato/dex@sha256:8e5d24d7a0f0fe95bbdf6722e1c724075d5d4c15cfa8d0ef4959f25103e12bac --owner cpanato
Loaded digest …
```

introduce Provenance Attestation

---

connector/oidc/oidc.go
connector/oidc/oidc_test.go

- It gives option to override the value of jwks_uri received from .well-known/openid-configurations and allows to use user supplied custom url. 
Usage:  "Closes (#3519)"

OIDC connector option to override jwksURI

---

connector/keystone/keystone.go
connector/keystone/keystone_test.go
go.mod

OpenStack Keystone allows a user to authenticate against a domain. That domain can be specified either as the domain ID or the domain name when authenticating. The domain ID is a UUID or the special "default" domain ID so key off of that when deciding what to submit to the keystone API. Collapsed the code to share the domainKeystone struct by utilizing omitempty to skip unset fields.

feat: allow domain names or IDs in keystone connector

---

cmd/dex/serve.go
cmd/dex/serve_test.go

The problem caused by the mistake in the newLogger function. The nil value is returned even with the valid log format.
Closes https://github.com/dexidp/dex/issues/3559

Fix slog nil pointer error

---

web/static/form.js
web/static/main.css
web/templates/password.html

Disables the submit button on login to prevent clicking multiple times while waiting for a response from the form submission on login.
When connecting to a very slow provider a response can take several seconds, without a visual indicator users click the submit button several times. After multiple clicks when a response is returned it's often a 500 error page within our setup. Better to prevent the user from submitting the form multiple times and indicating that by disabling the button.
We can solve this issue internally by having a custom frontend documented here https://dexidp.io/docs/guides/templates/ but this felt like a good thing to share more widely to help others.
If necessary the following can be rewritten inline to avoid loading a unique JS file.

Prevent double clicking of the submit button on login

---

cmd/docker-entrypoint/main.go

This is a minor change to prevent a panic in an admittedly niche edge case.
This PR gracefully handles no args being passed to the entrypoint binary.
```sh
./docker-entrypoint
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
main.run({0xc000014140?, 0xc00006e740?, 0x0?}, 0x60?, 0x0?)
/usr/local/src/dex/cmd/docker-entrypoint/main.go:56 +0x5c5
main.main()
/usr/local/src/dex/cmd/docker-entrypoint/main.go:21 +0x65
./docker-entrypoint 
error: no args passed to entrypoint
```
This can occur if someone builds upon the upstream dex image (e.g., adding internal company certificates) and inadvertently breaks the entrypoint/cmd.

Gracefully handle no args being passed to entrypoint

---

cmd/dex/serve.go

Add a new metric `dex_build_info`, with `version` which will be set to the Git tag version.
```
$ curl -s http://127.0.0.1:5558/metrics | grep build
dex_build_info{goarch="arm64",goversion="go1.22.2",version="43a9a144a710803b6a3036368cec3bec9f6f02de-dirty"} 1 
```

feat: new Prometheus metrics build_info

---

connector/github/github.go

As discussed in https://github.com/dexidp/website/pull/176, even when `preferredEmailDomain` (which was added by https://github.com/dexidp/dex/pull/2740) is set on the GitHub connector, if the user has a __public__ email on their GitHub profile, it will take precedence over any private one which might match the `preferredEmailDomain` selector.
This is problematic for organizations which want to use the email filter to assign permissions to employees based on their corporate email, as they must tell users to remove any public emails from their profile.
Simply makes it so that we always preform an email check when `preferredEmailDomain` is non empty.
N/A

fix: always retrieve github emails when `preferredEmailDomain` is set

---

connector/oidc/oidc.go

The OIDC connector has two options that directly customize the http.Client used for requests: [`rootCAs`](https://github.com/dexidp/dex/blob/23a53a80f664649ff77be9a21eb279b0ecf01678/connector/oidc/oidc.go#L52) and [`insecureSkipVerify`](https://github.com/dexidp/dex/blob/23a53a80f664649ff77be9a21eb279b0ecf01678/connector/oidc/oidc.go#L67) (passed [here](https://github.com/dexidp/dex/blob/23a53a80f664649ff77be9a21eb279b0ecf01678/connector/oidc/oidc.go#L214) to http.Client [here](https://github.com/dexidp/dex/blob/23a53a80f664649ff77be9a21eb279b0ecf01678/pkg/httpclient/httpclient.go#L19)).
That customized http.Client isn't currently propagated through to the JWT verifier. This means that the verifier's requests to the JWKS endpoint can unexpectedly fail with certificate issues.
<details> …

fix: propagate http.Client to JWT verifier for OIDC connector

---

Dockerfile

Fixes https://github.com/dexidp/dex/issues/3632 by bumping gomplate from v3.11.8 to v4.0.0
This is breaking change bump in gomplate and requires testing. This is just a suggestion from me to fix the CVE. The local setup is not working well in my machine and I can't find the right docs to pursue that further, therefore I will set it to draft till tested by somebody else.

Bump gomplate 4.0.1

---

connector/oidc/oidc.go
connector/oidc/oidc_test.go

Add a group regex matcher to the OIDC connector config.
Sometimes the IDP's can send very long list of groups, not all IDP's support group filters from the IDP side.
I tested this in the unit tests, ~but not sure how to test this in a live environment.~ and in a live environment, and the filter works as expected.
It adds a new config field for OIDC: `groupsRegex`.
```release-note
ADD groups regex config for oidc connector.
```

add regex for oidc group matching

---

cmd/dex/config.go
cmd/dex/logger.go
cmd/dex/serve.go
examples/config-dev.yaml
server/deviceflowhandlers.go
server/handlers.go
server/introspectionhandler.go
server/introspectionhandler_test.go
server/oauth2.go
server/refreshhandlers.go
server/server.go

- Include client's real IP in logs.
- Capture and log unique request IDs.
- Update middleware to extract and forward this data.
- Enhance debugging and traceability. Improves insight and troubleshooting efficiency.
https://github.com/dexidp/dex/issues/1788

Enrich Dex logs with real IP and request ID

---

cmd/dex/config.go
cmd/dex/config_test.go
cmd/dex/serve.go
examples/config-dev.yaml
pkg/featureflags/set.go
server/api.go
server/api_test.go
server/server.go

Remove the `additionalFeatures` logic that was introduced in https://github.com/dexidp/dex/pull/3245
and replace it with a feature flag.
There are two places where we are doing the same thing. I just realized it after merging.
In the future, we can expand feature flags to be configured through the config file.

Remove additional features and add a feature flag instead

---

.github/workflows/ci.yaml
connector/ldap/ldap.go
docker-compose.test.yaml

* Use scheme without :// suffix
* Make test ldap server listen on custom ports to avoid stepping into go-ldap defaults
Fixes https://github.com/dexidp/dex/issues/3671

Fix scheme for DialURL ldap connection

---

cmd/docker-entrypoint/main.go
cmd/docker-entrypoint/main_test.go

Workaround to run gomplate from a non-root directory in distroless images, because gomplate tries to access CWD on start. See: https://github.com/hairyhenderson/gomplate/pull/2202
Closes https://github.com/dexidp/dex/issues/3675
Also simplified tests and exec logic a little bit

Change workdir for gomplate

---

.envrc

Update `nix-direnv` in the `.envrc` file to the newest version.
The current nix-direnv version has issues on MacOS due to BSD sed differing from GNU sed. This has been fixed in nix-direnv https://github.com/nix-community/nix-direnv/issues/120 
Updating to the newest nix-direnv version fixes this issue.

chore: update nix-direnv from 1.5.0 to 3.0.5

---

go.mod
server/server.go

This change adds additional handler metrics`response_size_bytes` and `request_duration_seconds`.
It replaces the dependency for `felixge/httpsnoop` with functions from prometheus/client_golang 
Closes #3698
I have used default buckets for the histograms. I will try over the next week to get a custom build into my own QA landscape, in order to validate the buckets.

feat(metrics): add response_size, request_duration histograms

---

server/oauth2.go
server/oauth2_test.go

Instead of only checking for "localhost", also validate through `net.ParseIP` + `IsLoopback` whether the host is numerically localhost
Currently, `localhost` is already used as a special case that allows any port and http scheme if no particular redirectURIs are configured. When integrating with ownClouds desktop client, it actually sends an arbitrary `http://127.0.0.1:xyz` redirect uri. Considering that the go standard library already has the functionality to check if a given IP is a loopback address, we can extend the `== "localhost"` with also a check for `IsLoopback()` which should allow the ownCloud desktop client to be accepted.

feat: also allow localhost equivalent IP addresses

---

server/server.go

Add a simple handler and return for the root path (kind of similar to prometheus exporter way of handling the root path).
Closes https://github.com/dexidp/dex/issues/857

Handle root path better (than nothing)

---

server/handlers.go
server/handlers_test.go

Offline session is not created if the skip approval option is toggled. In this case Dex looses connector data and cannot refresh tokens.
It leads to the different refreshing errors in logs like:
```
{"time":"2024-11-06T10:19:31.541474938Z","level":"ERROR","msg":"failed to refresh identity","err":"gitlab: failed to get refresh token: oauth2: \"invalid_grant\" \"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.\"","client_remote_addr":"10.244.28.54","request_id":"8e46b1aa-3bd2-4ef1-a844-ad0db91dbc1e"}
```
This PR adjust the part of the code to make it creating and updating connectorData when it is needed avoiding refresh errors.

Create offline sessions if approval is skipped

---

examples/example-app/templates.go

Add inline CSS code to make the example app looking less ugly and improve experience of users interacting with it.

Add CSS for example app to make it prettier

---

server/api.go

This PR adds resource versions to connectors that are API controlled but default. It does not require the Connector to use the resource revision, so that Kubernetes still functions. 
This fixes an issue with connectors where updates to a connector via the API does not get applied to the runtime use of the connector. This seems to have been previously fixed for Kubernetes specifically, but this is a more general fix.
Fixes #3855
I see no obvious way to test this, but if I am missing something, please let me know.

feat: set resource revision for connectors

---

.envrc
.github/workflows/artifacts.yaml
.github/workflows/ci.yaml
.gitignore
.golangci.yml
Makefile
api/v2/go.mod
connector/saml/saml.go
examples/go.mod
flake.lock
flake.nix
go.mod
server/introspectionhandler.go
storage/ent/mysql_test.go

Update Go version
This is required for other dependency updates to work.

build: update Go version

---

connector/authproxy/authproxy.go
connector/authproxy/authproxy_test.go

Allows proxies to pass `X-Remote-User-Name` header to set preferred username. Also adds tests.
Perhaps authproxy should be extended to allow any claims, instead of adding headers for preferred username, picture, etc? But that's out of scope for this PR.
Resolves #3876.
Defaults to the value of `X-Remote-User` ([user name](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims)), to preserve the existing default. But we may want to change this because preferred username = shorthand, and user name = display name.

Add authproxy preferred_username header

---

server/handlers.go

Avoid access token generation when `response_type` is either `id_token` (for implicit flow) or `code id_token` (for hybrid flow).
This PR aims to make dex better follow what is stated in the following sections of the OpenID Connect Core1.0 specification:
- [3.2.2.5. Successful Authentication Response](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthResponse) (for implicit flow)
- [3.3.2.5. Successful Authentication Response](https://openid.net/specs/openid-connect-core-1_0.html#HybridAuthResponse) (for hybrid flow)

Generate access tokens for implicit & hybrid flows only when needed

---

storage/kubernetes/storage.go

Use limit to reduce data transferred from Kubernetes API server to Dex
Closes https://github.com/dexidp/dex/issues/4019

k8s storage: Request only one object to check if API exists

---

Makefile

In this branch, I fixed issues my team and I encountered with the Makefile, where it would not function correctly when spaces were present in the path. The issue was traced back to how `PATH` and `SHELL` were being set, leading to failures when running `make` in directories with spaces in their names.
- This PR ensures that paths are **properly quoted** in the Makefile to prevent issues caused by spaces in directory names.
- Updates how `SHELL` passes the `PATH` variable to ensure compatibility with `/bin/sh` while keeping the correct environment settings.
- This fix is necessary for users working in directories with spaces (e.g., `/home/user/My Project/`), where `make` previously failed due to improper path handling.

Fix Makefile to Support Spaces in Paths

---

connector/atlassiancrowd/atlassiancrowd_test.go
connector/authproxy/authproxy_test.go
connector/github/github_test.go
connector/google/google_test.go
connector/ldap/ldap_test.go
connector/oauth/oauth_test.go
connector/oidc/oidc_test.go
connector/openshift/openshift_test.go
connector/saml/saml_test.go
server/api_test.go
server/rotation_test.go
server/server_test.go
storage/ent/mysql_test.go
storage/ent/postgres_test.go
storage/ent/sqlite_test.go
storage/etcd/etcd_test.go
storage/kubernetes/client_test.go
storage/kubernetes/storage_test.go
storage/memory/memory_test.go
storage/memory/static_test.go
storage/sql/config_test.go
storage/sql/migrate_test.go

Simplify tests by using `slog.DiscardHandler` instead of `slog.NewTextHandler(io.Discard, &slog.HandlerOptions{})`.
It reduces number of code symbols in tests.
The [DiscardHandler](https://pkg.go.dev/log/slog#DiscardHandler) was added in [Go 1.24](https://go.dev/doc/go1.24#logslogpkglogslog).

refactor: simplify tests by using slog.DiscardHandler

---

ADOPTERS.md

Splitting the ADOPTERS file to Companies and Projects. Adding a few adopters.
The list of adopters becomes quite long, and I suggest this split to make it more clear and helpful.
I also added two Dex adopters I recently became aware of:
- Kubeflow
- LLMariner

docs: Split Adopters to Companies and Projects

---

cmd/dex/logger.go

Wrap the grouped handler in requestContextHandler to preserve context attribute injection. 
fixes #4081

fix Incorrect Group Handling in RequestContextHandler logger.go

---

Dockerfile

Updating gomplate to newest version.
To see vulnerabilities within version you are using
clone github.com/hairyhenderson/gomplate
git checkout v4.3.0
Vulnerability #1: GO-2025-3503
HTTP Proxy bypass using IPv6 Zone IDs in golang.org/x/net
More info: https://pkg.go.dev/vuln/GO-2025-3503
Module: golang.org/x/net
Vulnerability #2: GO-2025-3487
Potential denial of service in golang.org/x/crypto
More info: https://pkg.go.dev/vuln/GO-2025-3487
Module: golang.org/x/crypto
Found in: golang.org/x/crypto@v0.31.0
Fixed in: golang.org/x/crypto@v0.35.0
// validate current version
git checkout v4.3.2
govulncheck ./...
No vulnerabilities found.

Resolve CVE by updating gomplate to 4.3.2

---

connector/ldap/ldap.go
connector/ldap/ldap_test.go
connector/ldap/testdata/schema.ldif

This pull request introduces improvements to Dex's LDAP connector to enable universal nested group search support across a variety of LDAP server implementations. It updates the code to allow recursive group membership discovery during user authentication and provides a more robust testing framework to validate the functionality.
This PR builds is largely based upon @paroque’s original #1058,
The groups() function in ldap.go was significantly refactored to add support for recursive nested group searching. Previously, the function directly built and executed LDAP search requests inline for each user matcher, then collected group names from the immediate search results. In the new version, the LDAP querying has been moved into a separate helper function called queryGroups(), which makes the …

Add recursive LDAP parent group search (AD-style hierarchy across all LDAPs)

---

connector/oidc/oidc.go

OIDC options `insecureSkipVerify` and `rootCAs` does not work now, we getting `x509: certificate signed by unknown authority` errors with this config:
```
connectors:
- type: oidc
id: "my-oidc"
name: "My OIDC"
config:
issuer: "https://dex.company.my/"
clientID: REDACTED
clientSecret: REDACTED
redirectURI: https://dex-client.company.my/callback
insecureEnableGroups: true
getUserInfo: true
userIDKey: "sub"
userNameKey: "email"
scopes:
- "openid"
- "email"
- "profile"
- "offline_access"
- "groups"
- "federated:id"
- "offline_access"
- "audience:server:client_id:kubernetes"
promptType: "consent"
rootCAs:
- |
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
insecureSkipVerify: true
```
```
{"time":"2025-07-17T18:34:03.235594098Z","level":"ERROR","msg":"failed to verify subject …
```

[oidc] pass httpClient to the TokenIdentity context

---

server/deviceflowhandlers.go
server/deviceflowhandlers_test.go

As per RFC8628 section 3.5, https://datatracker.ietf.org/doc/html/rfc8628#section-3.5 the authorization_pending response should extend RFC6749 section 5.2, https://datatracker.ietf.org/doc/html/rfc6749#section-5.2 which specifies that the HTTP response code should be 400, Bad Request.
RFC8628 compliance.
Partially fixes #4240

fix: device code pending HTTP response

---

storage/sql/sqlite_no_cgo.go

`ent` driver gives a normal error if the binary is compiled without CGO, but with our custom SQL driver Dex just fails to compile.
```
cmd/dex/config.go:273:26: undefined: sql.SQLite3
cmd/dex/config.go:315:43: undefined: sql.SQLite3
```
Somebody rised this once, but I didn't mange to find it quickly. With this PR it is now possible to compile Dex without CGO in case if the sqlite driver is not required in runtime.

Allow compilation without CGO
