dexidp/dex

email/smtp.go

email/smtp: Fix type comparison error

---

build

Tell the user how to fix ther error! That is the best type of error
message. :)

build: add install instructions for go-bindata

---

Documentation/dev-guide.md
Documentation/getting-started.md

Documentation: turn on registration in examples

---

Documentation/getting-started.md

Documentation: fix link

---

README.md

readme: added godoc link to readme

---

Documentation/dev-guide.md
examples/README.md

This is a rebase of https://github.com/coreos/dex/pull/174 for @mkobit

Tweak dev guide & update example README

---

db/connector_config.go

Added missing err return introduced by #199

db: fixed missing return statement GetConnectorByID

---

db/refresh.go
db/refresh_test.go

db: strconv.ParseInt specify base 10

---

static/html/header.html

static: use --issuer-name as title for public facing pages

---

connector/interface.go

connector: document Connector and ConnectorConfig interfaces

---

cmd/dexctl/command_config.go
connector/config_repo.go
functional/dexctl_test.go
server/config.go

*: allow dexctl set-connector-configs to read from stdin

---

db/client.go

db: log ignored base64 decode error

---

server/password_test.go

TestResetPasswordHandler depended on makeToken begin called twice during the initialization of a single test case and later assuming the result would match. Because the token has a timestamp accurate to the second, occasionally the timestamps would be slightly off within a single test case and cause the test to fail.
Adding a sleep statement to makeToken would cause the test to fail reliably.
Define a single token for each test case outside of the struct initializer so test cases compare the same token.
Closes #274
Additionally remove logging statements that dump entire HTML pages.

server: fix reset password test

---

Documentation/roadmap.md

Documentation: update roadmap with issue and PR numbers

---

server/http.go

A revision of #346. Apologies to @gerson24 for hijacking his PR, we'd like to get this into 0.3
Fixes #336

server: url decode basic auth credentials

---

Documentation/roadmap.md

cc @bobbyrullo, @sym3tri, @philips

Documentation: update roadmap for 0.4 release cycle

---

examples/app/main.go

This is super useful when testing refresh flows

examples/app: Show refresh token as well

---

env

*: fix build script to work outside of GOPATH

---

server/http.go
server/http_test.go

This reverts commit 821b242c83bd1770af0886899be163bdc77749cd.
fixes #443

Revert "Fix response_type missing param"

---

admin/api.go
client/client.go
client/manager/manager.go
integration/admin_api_test.go
schema/adminschema/README.md
schema/adminschema/v1-gen.go
schema/adminschema/v1-json.go
schema/adminschema/v1.json

Allow specification of client_{id, secret} in admin api

---

glide.lock
glide.yaml
vendor/github.com/coreos/go-oidc/key/key.go
vendor/github.com/coreos/go-oidc/key/key_test.go

*: update go-oidc to shorten length of key IDs

---

admin/api.go
client/client.go
db/client.go
db/conn_sqlite3.go
integration/admin_api_test.go

return 409 for duplicate client ids

---

Documentation/releases.md

Closes #452 by adding a note to create a Quay tag.
cc @chancez

Documentation: clean up release documentation

---

connector/connector_ldap.go

cc @rudyzhou2 can you sign off that this fixes #506?
Closes #506

connector: remove erroneous logging statement

---

contrib/standup-db.sh

Fix standup-db.sh

---

.travis.yml
Dockerfile

Also, run the build-docker script in the travis file.

*: fix path to email config in dockerfile

---

.travis.yml
build-docker

*: cleanup containers generated during tests to avoid deploy conflicts

---

Documentation/getting-started.md

| Typo           | Fix            |
| -------------- | -------------- |
| a an api       | an api         |
| adminsitrative | administrative |
| attemping      | attempting     |
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

documentation: fix typos in getting-started

---

server/server.go

server: fix the path registration for user APIs at non-root URLs

---

cmd/dex/config.go
server/handlers.go
server/oauth2.go
server/server.go
server/server_test.go

Friday hack.
cc @sym3tri @chancez @dghubble 
Am going to update this PR with an integration test later.

dev branch: support the implicit flow

---

TODO.md

While the issue tracker is being used for the master branch, add a
plain text TODO file to record work to do on this branch. Issues
are currently unprioritized and do not indicate requirements for
any particular milestone.
cc @sym3tri

dev branch: add TODO file

---

static/html/header.html

This PR fixes some visual issues with the button styles. Here are before and after screenshots for reference:
Before:
After:

static: fix button styles

---

storage/sql/config.go
storage/sql/gc.go

Was an oversight of the initial SQL PR.
cc @dghubble @squat @kans

storage/sql: enable garbage collection

---

server/handlers.go
server/server.go

dev branch: add health check endpoint

---

Documentation/connectors-configuration.md
connector/connector_facebook.go
connector/connector_facebook_test.go

This is an implementation of dex connector for facebook
Fixes #391

Connector: Connector for Facebook

---

storage/conformance/conformance.go
storage/conformance/gen_jwks.go
storage/conformance/jwks.go
storage/sql/crud.go
storage/sql/standup.sh

dev branch: fix sql keys query

---

server/rotation.go

server: fix key rotation polling

---

Documentation/proposals/upstream-refreshing.md

cc @dghubble @sym3tri @squat @kans

Documentation/proposals: add a proposal for keeping data in-sync during refreshes

---

server/handlers.go
server/templates.go
server/templates_default.go
web/templates/oob.html

*: port oob template

---

storage/conformance/conformance.go
storage/conformance/transactions.go
storage/kubernetes/storage.go
storage/kubernetes/storage_test.go

storage/conformance: add tests for transactional guarantees

---

connector/ldap/ldap.go

connector/ldap: fix bug in switch statement

---

storage/kubernetes/doc.go
storage/storage.go

storage: update godocs

---

Documentation/api.md
cmd/dex/config.go
cmd/dex/serve.go
examples/config-dev.yaml

cmd/dex: add option for gRPC client auth CA.

---

connector/ldap/ldap.go

connector: accept base64 encoded CA and add convience open method

---

Documentation/storage.md

Fix a tyop in the storage documentation

---

Documentation/openid-connect.md

Updated openid-connect.md: small typo

---

.travis.yml
scripts/rkt-build

closes #718.
@ericchiang  @sym3tri

*: update travis to use Go 1.7.4.

---

storage/kubernetes/client.go

storage/kubernetes: remove unused method

---

README.md

closes #722
cc @ElijahCaine @joshix

*: add section about dex and Kubernetes to README

---

README.md
cmd/example-app/templates.go
server/api.go
server/templates.go
storage/conformance/conformance.go
storage/sql/crud.go

Found a bunch of comment typos with goreportcard. Adding this here for quick access later.
https://goreportcard.com/report/github.com/coreos/dex

*: fix comment typos and add go report card icon

---

cmd/dex/serve.go

addresses https://github.com/coreos/dex/pull/723#pullrequestreview-12782691.
@ericchiang @chancez

cmd/dex: modify error messages to info messages.

---

cmd/dex/serve.go

Updated server now() func and logger to use UTC timestamps.
Log messages now use UTC:
time="2016-12-16T22:44:47Z" level=info msg="config issuer: http://127.0.0.1:5556/dex" 
time="2016-12-16T22:44:47Z" level=info msg="config connector: mock" 
time="2016-12-16T22:44:47Z" level=info msg="config connector: local passwords enabled" 
time="2016-12-16T22:44:47Z" level=info msg="config storage: sqlite3" 
time="2016-12-16T22:44:47Z" level=info msg="config static client: example-app" 
time="2016-12-16T22:44:47Z" level=info msg="listening (http) on 0.0.0.0:5556" 
@ericchiang

server: use UTC timestamps in dex.

---

examples/k8s/dex.yaml

replace bcrypt hash with an appropriate value for the string "password"

replace bcrypt hash with a working one

---

connector/ldap/ldap.go

connector/ldap: enable groupSearch to be empty

---

storage/conformance/conformance.go
storage/kubernetes/storage.go
storage/kubernetes/types.go

storage: Add ConnectorData to storage RefreshToken.

---

Documentation/dev-releases.md

Documentation: add docs on patch release process.

---

Documentation/proposals/token-revocation.md

Outline the design for handling refresh token revocation in Dex v2.

Documentation/proposals: Add a proposal for refresh token revocation.

---

Documentation/saml-connector.md

Typo correction. Also explicitly calling out that "offline_access" scope needs to be set to false

Documentation: Minor changes to SAML connector doc.

---

Documentation/kubernetes.md
Documentation/storage.md

closes #798
cc @rithujohn191 @ElijahCaine

Documentation: warn admins not to edit dex ThirdPartyResources manually

---

server/server_test.go

server: clean up test comments and code flow

---

web/static/main.css

web/static/main.css: fix typo.

---

Documentation/getting-started.md

It does basically the same thing, but is a little bit simpler...

simplified clone: using go get

---

storage/kubernetes/client.go
storage/kubernetes/storage.go
storage/kubernetes/types.go

storage/kubernetes: fix kubernetes storage conformance test failures

---

storage/kubernetes/client.go
storage/kubernetes/client_test.go

storage/kubernetes: fix hash initialization bug

---

storage/kubernetes/client.go

storage/kubernetes: enable HTTP/2 support

---

server/rotation.go
server/rotation_test.go

Cherry pick of https://github.com/coreos/dex/pull/829

server: fix expiry detection for verification keys

---

Documentation/integrations.md
Documentation/production-users.md

Production-users and Integrations pages, per the request from @philips

Added produciton-users and integrations pages

---

Documentation/kubernetes.md

Clarify some potentially confusing issues with how to run and build the
example-app binary.
fixes https://github.com/coreos/dex/issues/843

update kubernetes example-app explanation

---

storage/conformance/conformance.go
storage/sql/crud.go

Cherry pick of #848
Updates #847

storage/sql: add missing WHERE statement to refresh token update (cherry pick)

---

storage/kubernetes/storage.go

storage/kubernetes: log INFO level if TPR already exists, not ERROR

---

storage/conformance/conformance.go

Fixes https://github.com/coreos/dex/issues/849.

storage/conformance: update conformance tests with multiple entries per resource

---

glide.lock
glide.yaml
vendor/github.com/russellhaering/goxmldsig/canonicalize.go
vendor/github.com/russellhaering/goxmldsig/etreeutils/namespace.go
vendor/github.com/russellhaering/goxmldsig/etreeutils/sort.go
vendor/github.com/russellhaering/goxmldsig/sign.go
vendor/github.com/russellhaering/goxmldsig/validate.go

Diff of the package is here[0]. It's a little hard for me to figure out what features went in or what providers it may or may not have expanded support for based on the commit messages.
[0] https://github.com/russellhaering/goxmldsig/compare/e2990269f42f6ddfea940870a0800a14acdb8c21...51810e925e5fc495822fbddda8202f70a6e4a3f3

glide.yaml: update goxmldsig

---

cmd/example-app/main.go

fixes #874
cc @andrewrynhard @rithujohn191

cmd/example-app: fix custom CA behavior

---

server/api_test.go

server: use client connected to remove server for gRPC tests

---

Documentation/custom-scopes-claims-clients.md
Documentation/openid-connect.md
README.md

Documentation: document dex scopes, claims, and client features

---

server/server.go

fixes: https://github.com/coreos/dex/issues/890

server/server.go: make successful garbage collection log at info level

---

connector/saml/saml.go

Fix entityIssuer -> ssoIssuer typo

---

README.md

*: add GitLab connector to README

---

Documentation/custom-scopes-claims-clients.md
Documentation/dev-integration-tests.md
Documentation/saml-connector.md
README.md
cmd/dex/config.go
server/handlers.go

This means we no longer refer to it as "experimental" and wont make
breaking changes.

*: promote SAML to stable

---

connector/ldap/ldap.go
connector/ldap/ldap_test.go

Support schemas that determine membership by having fields on the
user entity, instead of listing users on a groups entity. E.g. the
following schema is now supported when it wasn't previously:
cn=eric,cn=user,dn=example,dn=com
objectClass=myPerson
cn: eric
uid: eric
email: eric@example.com
memberOf: foo
memberOf: bar
cn=foo,cn=group,dn=example,dn=com
objectClass=myGroup
cn: foo
cn=bar,cn=group,dn=example,dn=com
objectClass=myGroup
cn: bar

connector/ldap: fix case where groups are listed on the user entity

---

cmd/dex/config.go
connector/ldap/ldap.go

Signed-off-by: zhuguihua <zhuguihua@cmss.chinamobile.com>
Change storace to storage in cmd/dex/config.go,
change userSearch to groupSearch in connector/ldap/ldap.go

Fix two typos

---

server/api.go

Offline sessions only get created if the user has a refresh token. If ListRefresh() is called we should return an empty list for a user without refresh tokens instead of throwing an error.

server/api: return empty list of refresh tokens if user does not have any

---

Documentation/custom-scopes-claims-clients.md
server/oauth2.go
server/oauth2_test.go

server: fix localhost redirect validation for public clients

---

connector/github/github.go
connector/oidc/oidc.go

connector: improve error message for callback URL mismatch

---

scripts/docker-build

scripts: bump builder to Go 1.8.3

---

connector/ldap/ldap.go
connector/saml/saml.go
connector/saml/types.go
server/handlers.go

Add some log events to help debug common mis-configuration issues.
Will do a login through SAML and LDAP providers to show what these logs look like.

*: add log events for login, LDAP queries, and SAML responses

---

Documentation/github-connector.md

Documentation: fixed GitHub link syntax

---

connector/github/github.go

connector/github: fix username used when making API requests for patch release

---

connector/github/github.go

[cherry pick] connector/github: fix 'groups' scope check bug

---

Documentation/dev-integration-tests.md
Documentation/getting-started.md
Documentation/ldap-connector.md
examples/config-ldap.ldif
examples/config-ldap.yaml
scripts/slapd.sh

This is how I tested my changes for https://github.com/coreos/dex/pull/1021
Add a getting started guild using OpenLDAP. Hopefully others find this useful.
Not urgent.
cc @rithujohn191 @estroz

*: add "getting started" example for LDAP

---

storage/kubernetes/types.go

Cherry-pick change from master

storage/kubernetes: Correct the OfflineSession object CRD definition

---

connector/ldap/ldap_test.go

updates https://github.com/coreos/dex/issues/907

connector/ldap: add test for InsecureSkipVerify option

---

Documentation/authproxy.md
connector/authproxy/authproxy.go

authproxy: update docs and set a userID

---

Dockerfile
scripts/check-go-version

Updates https://github.com/coreos/dex/issues/1118

*: Go 1.7 no longer supported and updated build image to 1.9

---

Documentation/ldap-connector.md
connector/connector.go
connector/ldap/ldap.go
connector/ldap/ldap_test.go
connector/mock/connectortest.go
examples/config-ldap.yaml
server/handlers.go
server/server.go
server/server_test.go
server/templates.go
web/templates/password.html

password connectors: make prompt configurable

---

server/handlers.go
server/templates.go
web/templates/password.html
web/themes/coreos/styles.css

cherry-pick: show "back" link for password connectors

---

README.md

README: expand connector docs and assign each a level of support

---

connector/ldap/ldap.go

Fixes issue 1170
BsaeDN should be BaseDN

1170 - Fix comment typos

---

.travis.yml
Dockerfile

*: update build to Go 1.10

---

examples/config-ldap.yaml

Cleaning up whitespace in `config-ldap.yaml`.

Removing whitespace

---

examples/k8s/dex.yaml

Version mentioned in this example is very old and was causing issues

[version_update] Update the version to the latest

---

Documentation/connectors/oidc.md

Fixed a broken link to An overview of OpenID Connect

Fix a broken link in the oidc readme

---

server/oauth2.go

Noticed a minor spelling error while reading code.  PR > bug report. :)

minor spelling correction

---

.travis.yml

going to merge manually to fix the build

.travis.yml: fix golint import

---

.travis.yml
Makefile
glide.lock
glide.yaml
vendor/golang.org/x/lint/LICENSE
vendor/golang.org/x/lint/golint/golint.go
vendor/golang.org/x/lint/golint/import.go
vendor/golang.org/x/lint/lint.go
vendor/golang.org/x/tools/LICENSE
vendor/golang.org/x/tools/PATENTS
vendor/golang.org/x/tools/go/ast/astutil/enclosing.go
vendor/golang.org/x/tools/go/ast/astutil/imports.go
vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
vendor/golang.org/x/tools/go/ast/astutil/util.go
vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go
vendor/golang.org/x/tools/go/gcexportdata/importer.go
vendor/golang.org/x/tools/go/gcexportdata/main.go
vendor/golang.org/x/tools/go/internal/gcimporter/bexport.go
vendor/golang.org/x/tools/go/internal/gcimporter/bimport.go
vendor/golang.org/x/tools/go/internal/gcimporter/exportdata.go
vendor/golang.org/x/tools/go/internal/gcimporter/gcimporter.go
vendor/golang.org/x/tools/go/internal/gcimporter/iimport.go
vendor/golang.org/x/tools/go/internal/gcimporter/newInterface10.go
vendor/golang.org/x/tools/go/internal/gcimporter/newInterface11.go

cc @srenatus 
Will hopefully prevent us from breaking with newer Go versions :)

 *: vendor golint to prevent upstream changes from breaking the build

---

storage/sql/config.go
storage/sql/config_test.go

context: https://github.com/dexidp/dex/pull/1346#issuecomment-440305417

pg: support host:port for backwards-compatibility

---

Documentation/dev-dependencies.md

RE: https://github.com/dexidp/dex/pull/1365#issuecomment-443778021

Documentation/dev-dependencies.md: Update for Go modules

---

cmd/dex/serve.go

Some environments are subject to strict rules about the permitted TLS
protocol verion and available ciphers. This change makes the former
configurable for both HTTPS and gRPC.
The gRPC protocol rejects anything under TLSv1.2; however, it is still
useful to configure the tls protocol version explicitly because many
automated scanners do not recognize gRPC.
Signed-off-by: Steven Danna <steve@chef.io>

Bump minimum TLS protocol to TLSv1.2

---

cmd/example-app/main.go
cmd/example-app/templates.go

Add some code to display access token in example app. It may helps someone to understand oidc.
Thanks.

Display access token in example app

---

Documentation/connectors/oidc.md
connector/oidc/oidc.go

This pr adds the insecureSkipEmailVerified option suggested in #1405

Add option to OIDC connecter to override email_verified to true

---

MAINTAINERS

I haven't had time to contribute to dex recently and it's been over a
year since I've worked on Kubernetes. Going to make this official and
remove myself from the MAINTAINERS list. I'll still be around if you
need to know why any of the code is so crazy :)

MAINTAINERS: remove ericchiang@

---

MAINTAINERS

Following the suggestion in #1485. Let's add @bonifaido 🎉 👏

MAINTAINERS: add @bonifaido

---

Documentation/storage.md

sample query for mysql storage looks wrong.

Doc/storage.md: fix mysql sample query

---

cmd/dex/serve.go
connector/github/github.go
connector/gitlab/gitlab_test.go
connector/keystone/keystone.go
connector/oidc/oidc.go
connector/saml/saml.go
connector/saml/saml_test.go
server/oauth2.go
server/rotation.go
server/server.go
server/server_test.go
storage/etcd/types.go
storage/sql/config.go

Mostly gathered these using golangci-lint's deadcode and ineffassign
linters.

*: fix some lint issues

---

Dockerfile

Dockerfile: build with golang 1.12.9

---

Documentation/openid-connect.md

Fix URLs in curl cmd as stated in the overview doc.

---

MAINTAINERS

I would like to add Mark to the maintainers, he has already contributed to the project, and with more maintainers, we probably could speed up the project a little bit again! 💯

add @sagikazarmark to MAINTAINERS

---

.github/workflows/ci.yml
.golangci.yml
Makefile
scripts/gofmt

Replaces golint, fmt, vet with GolangCI lint.

Add golangci linter

---

.golangci.yml
cmd/dex/config_test.go
cmd/dex/serve.go
cmd/example-app/main.go
connector/bitbucketcloud/bitbucketcloud.go
connector/bitbucketcloud/bitbucketcloud_test.go
connector/github/github.go
connector/github/github_test.go
connector/gitlab/gitlab_test.go
connector/google/google.go
connector/keystone/keystone.go
connector/keystone/keystone_test.go
connector/ldap/ldap.go
connector/oidc/oidc_test.go
connector/saml/saml.go
server/api.go
server/api_test.go
server/handlers.go
server/handlers_test.go
server/server.go
server/server_test.go
server/templates.go
storage/conformance/conformance.go
storage/etcd/etcd.go
storage/kubernetes/client.go
storage/kubernetes/k8sapi/crd_extensions.go
storage/sql/config.go
storage/sql/crud.go

Enable more linters and fix violations

Fix linters

---

Documentation/templates.md

Give an example of the variables in the template such as `issuer` can be helpful. 
It lacks documentation, so I need to read the code to figure out.

add issuer in the templates.md

---

Documentation/connectors/kubelogin-activedirectory.md

This will update the document of "Integration kubelogin and Active Directory".
Now kubelogin supports credential plugin mode (new) and standalone mode (old). Currently the document uses standalone mode and this PR will replace it with credential plugin mode. It allows better user experience because user do not need to run kubelogin command explicitly.
Thanks the original author @okamototk.

Update kubelogin-activedirectory.md for credential plugin mode

---

Documentation/kubernetes.md

update kubernetes.md document

---

connector/openshift/openshift.go

Fix OpenShift connector rootCA option

---

server/oauth2.go

Logic is correct, just a typo in the comment.

Fix comment for implicit flow

---

go.mod
go.sum
storage/kubernetes/client.go

Remove copypasta dependency

---

.github/workflows/ci.yml
.github/workflows/release.yml

Add docker build and push to docker hub

---

Documentation/storage.md

Further to msg on slack `#dexidp` (fyi @JoelSpeed) here is PR (no issue) re a few doc tweaks I noticed while reading it.
One new para removed, included MySQL in header, and minor clarity tweak.

Minor documentation tweaks re storage.md

---

Makefile

Fix building the example app

---

Documentation/connectors/github.md
Documentation/getting-started.md

- update github documentation
- new make command for example app

update documentation 

---

server/handlers.go
server/handlers_test.go

abort connector login if connector was already set #1707

---

server/handlers.go

Original PR from @tomqwpl.
Issues: #1813

fix: log errors from login during password grant

---

Dockerfile

Reduced size by almost 2MB by not using the apk cache

feat: reduce image size without apk cache

---

.dockerignore
.gitpod.yml
README.md

**Overview**:
This commit implements a fully-automated development setup using Gitpod.io, an
online IDE for GitHub and GitLab that enables Dev-Environments-As-Code.
This makes it easy for anyone to get a ready-to-code workspace for any branch,
issue or pull request almost instantly with a single click.
Let's enable people to contribute to Dex from their browser! https://www.gitpod.io/
Not to mention, it's for a great cause! https://twitter.com/gitpod/status/1329141750196277249?s=20
**Special notes for a reviewer**:

Fully automate dev setup with Gitpod

---

.github/PULL_REQUEST_TEMPLATE.md
Dockerfile
README.md
docker-compose.yaml

- README.md: Use maintainers list for reporting security issues
- Update image versions
- golang:1.15.6-alpine3.12
- postgres:10.15
- gcr.io/etcd-development/etcd:v3.4.9
- .github: Add release notes block to pull request template
Periodic cleanups.
~**Do not merge yet.**~
```release-note
- README.md: Use maintainers list for reporting security issues
- Update image versions
- golang:1.15.6-alpine3.12
- postgres:10.15
- gcr.io/etcd-development/etcd:v3.4.9
- .github: Add release notes block to pull request template
```

Update image versions, add release notes block, update guidance on reporting security issues

---

README.md

Signed-off-by: Eric Chiang <ericchiang@google.com>

README: add warning to the SAML connector

---

cmd/dex/serve.go
cmd/dex/version.go

Add flags for bind address config options
Closes #1919
See the linked issue for details
The PR includes some unrelated refactors in separate commits.
```release-note
Add flags for bind address config options
```

Add flags for bind address config options

---

.github/ISSUE_TEMPLATE/config.yml
README.md

Update links pointing to slack channel
The new slack channel is on the CNCF slack
```release-note
NONE
```

Update links pointing to slack channel

---

.github/dependabot.yml
Dockerfile

Add dependabot config
Let's try automating dependency updates
```release-note
NONE
```

Add dependabot

---

Dockerfile

Generic docker improvements
This PR contains a number of improvements for the container image build:
- Improve order of instructions to better utilize the cache
- Copy every source file to the final image from the builder image
- Add an alias to the builder image
- Update base images
- Add a `/var/dex` data directory (closes #1954)
- Relocate module files to `/usr/local/src/dex` (see #1863, cc @heidemn-faro)
These changes mostly affect the image building process.
```release-note
`/var/dex` can be used as a data directory for Dex
Go module files are relocated to `/usr/local/src/dex`
```

Generic docker improvements

---

.editorconfig
config.dev.yaml
config.yaml.dist
examples/config-dev.yaml

New configuration examples for development purposes.
This PR adds two new configuration examples to the repo:
- `config.yaml.dist` - This serves as a dummy, empty config demonstrating most of the available options. Whenever making config option changes in code, this file should be updated to reflect those changes. Not all options are detailed here though: connector, client and password changes should be documented instead.
- `config.dev.yaml` - This file serves as a template for development purposes. It's minimal and contains only the necessary config options. It should be used instead of `examples/config-dev.yaml` (easier to find in the repo root, we can add it to the `Makefile` at some point)
`config.yaml.dist` can serve as a default configuration mentioned in …

Add new configuration examples

---

examples/example-app/templates.go

Improve alignment of example-app form.
Working a lot with example-app these days. I think that it needs a little "renovation".
Before:
After:
```release-note
Improve alignment of example-app form.
```

chore: make example-app form prettier

---

.golangci.yml
connector/atlassiancrowd/atlassiancrowd.go
connector/atlassiancrowd/atlassiancrowd_test.go
connector/bitbucketcloud/bitbucketcloud.go
connector/gitea/gitea.go
connector/ldap/ldap.go
connector/saml/saml.go
server/api.go
server/deviceflowhandlers.go
server/server.go
storage/conformance/conformance.go
storage/etcd/etcd.go
storage/kubernetes/k8sapi/client.go
storage/sql/crud.go
storage/storage.go

* Enable some useful linters
* Fix errors
We need this to make (and keep) code cleaner.

Enable unparam, prealloc, sqlclosecheck linters

---

cmd/dex/serve.go
go.mod
go.sum
server/handlers.go
server/handlers_test.go
server/server.go
server/server_test.go
storage/health.go

Improve health checks by separating liveness and readiness checks
Closes #1941
```release-note
NONE
```

Refactor health checks

---

.github/workflows/ci.yaml
Dockerfile
go.mod

Upgrade Go to 1.16
Use the latest Go version
We'll use the embed feature for web assets.
```release-note
NONE
```

Upgrade Go to 1.16

---

README.md

* Replace tectonic console with kubernetes-dashboard
* TPR -> CRD
* Add the link to adopters
This PR refreshes outdated information about using Kubernetes and Dex in the README.
```release-note
NONE
```

chore: update Kubernetes section in README

---

cmd/dex/serve.go

Refactor the use of run groups: simplify the code by removing intermediate helper functions.
It makes the code more readable.
It also fixes a regression introduced in  #1963
Fixes 2018
```release-note
NONE
```

Refactor run groups

---

Dockerfile

Stop using the slim version of gomplate
Looks like the slim version of gomplate doesn't work well on arm (see hairyhenderson/gomplate#1085)
Fixes #2052
```release-note
Fix arm images by using the non-slim version of gomplate
```

fix: stop using slim version of gomplate

---

go.mod
go.sum

Update xml roundtrip validator
Update xml roundtrip validator
```release-note
NONE
```

Update xml roundtrip validator

---

.github/workflows/ci.yaml
README.md
connector/keystone/keystone.go
web/static/img/keystone-icon.svg
web/static/main.css

* fix comments
* connector icon
* add info to connectors table
* bump e2e tests dependency 
Related to https://github.com/dexidp/website/pull/90
Nothing special.
```release-note
```

chore: add keystone connector icon and bump tests dependencies

---

MAINTAINERS

* Add new maintainer
* Keep alphabetical order
Related to https://github.com/dexidp/dex/discussions/1974
```release-note
```

Add @nabokihms to the maintainers list

---

connector/ldap/ldap.go

Anonymous LDAP bind needs to be explicit with the new ldap library.
Fixes  #2084
```release-note
NONE
```

Fix anonymous ldap bind

---

.github/workflows/docker.yaml

Update docker build config
```release-note
NONE
```

Update docker build config

---

server/server_test.go

Quick fix a flaky test that uses time.
```release-note
NONE
```

Quick fix flaky test

---

.github/workflows/ci.yaml
Dockerfile
Makefile
api/v2/go.mod
go.mod
storage/kubernetes/client_test.go

Update Go to 1.17
Update Go to 1.17
```release-note
NONE
```

Update Go to 1.17

---

Dockerfile

Backport alpine upgrade
Fixes #2326
```release-note
NONE
```

Backport alpine upgrade

---

.github/workflows/docker.yaml

ci: fix container image permissions
```release-note
NONE
```

ci: fix container image permissions

---

.github/workflows/docker.yaml

Fix GitHub Actions container image permissions
```release-note
NONE
```

Backport #2329: Fix GitHub Actions container image permissions

---

cmd/dex/serve.go

Signed-off-by: iam-veeramalla <abhishek.veeramalla@gmail.com>
Closes #2335 
@sagikazarmark as per our discussion on https://github.com/dexidp/dex/discussions/2334
NA
```release-note
```

feat: print dex version in the logs

---

.github/workflows/docker.yaml

Run Trivy scan on published container images
We should know about vulnerabilities in our images.
```release-note
NONE
```

ci: run trivy scan on container image

---

Dockerfile

Upgrade gomplate
Update to latest version
```release-note
NONE
```

chore: update gomplate

---

connector/bitbucketcloud/bitbucketcloud.go
connector/bitbucketcloud/bitbucketcloud_test.go

Backport Bitbucket workspaces endpoints fix
FIxes https://github.com/dexidp/dex/issues/2391
```release-note
NONE
```

Backport #2390: Replace /teams API w/ /workspaces endpoints

---

.github/workflows/docker.yaml

Add Docker cache to speed builds up
```release-note
NONE
```

ci: add Docker cache to speed builds up

---

go.mod

Update API package
```release-note
NONE
```

Update API package

---

.github/workflows/artifacts.yaml

New docker image build
Hopefully this will improve the container build performance
Also, this will be a good base for distroless image builds.
```release-note
NONE
```

New docker image build

---

.github/workflows/artifacts.yaml

Add docker metadata action
Test the new Docker metadata action to see if it can replace the shell script.
```release-note
NONE
```

Add docker metadata action

---

.github/workflows/artifacts.yaml

ci: use docker metadata for build input
```release-note
NONE
```

ci: use docker metadata for build input

---

go.mod
go.sum

```
go mod tidy -compat=1.17
```
```release-note
NONE
```

chore: Go mod update 1.17

---

.github/workflows/ci.yaml
.golangci.yml
Dockerfile
Makefile
connector/keystone/keystone.go
connector/keystone/keystone_test.go
connector/ldap/ldap.go
connector/openshift/openshift.go
flake.lock
flake.nix
go.mod
storage/conformance/jwks.go
storage/ent/mysql.go
storage/ent/postgres.go
storage/ent/sqlite.go
storage/kubernetes/storage_test.go
storage/sql/crud_test.go
storage/sql/migrate_test.go
storage/sql/postgres_test.go
storage/sql/sqlite.go
storage/sql/sqlite_test.go

Upgrade Go to the latest version.
Use the latest Go version to build the application.
Holding off until #2428 is merged (see ent/ent#2155 for more details).
```release-note
NONE
```

feat: upgrade Go to 1.18

---

Dockerfile

Update Go to 1.17.10
Apply latest security patches
```release-note
NONE
```

Update go to 1.17.10

---

.github/workflows/artifacts.yaml
.github/workflows/docker.yaml
Dockerfile

Signed-off-by: mayurwaghmode <waghmodemayur17@gmail.com>
https://github.com/hairyhenderson/gomplate/releases/tag/v3.11.2

updated gomplate version and added ppc64le support

---

flake.lock
flake.nix

build: bump Go version to 1.19 in Nix

---

Dockerfile

chore: update alpine version in Go image

---

ADOPTERS.md

Signed-off-by: Jann Fischer <jfischer@redhat.com>
Add the [Argo CD](https://argoproj.github.io/cd) project to the list of official Dex adopters.
```release-note
NONE
```

docs: Add Argo CD to list of Dex adopters

---

connector/google/google.go
go.mod
go.sum

Backport #2700 to v2.35.x

---

Dockerfile

https://github.com/hairyhenderson/gomplate/releases/tag/v3.11.3
https://github.com/advisories/GHSA-69cg-p879-7622
```release-note
Update gomplate version to 3.11.3 fix CVE-2022-27665
```

fix: Update gomplate version to 3.11.3 fix CVE-2022-27665

---

README.md

Fix https://github.com/badges/shields/issues/8671

Update GitHub workflow status

---

.github/workflows/ci.yaml

Use go 1.19 in the CI job.
The go module and Dockerfile moved to 1.19 in d33e994 The nix environment moved to go 1.19 in cf572e9
~This PR cannot merge until #2790 merges, because `make lint` will fail in the CI job.~ #2790 merged.
```release-note
NONE
```

ci: Use go 1.19

---

Dockerfile

Bump gomplate version to avoid scanners complaining about CVEs
https://github.com/hairyhenderson/gomplate/issues/1638
```release-note
feat: Bump gomplate 3.11.4
```

feat: Bump gomplate 3.11.4

---

examples/k8s/dex.yaml

```release-note
Bump image in examples/k8s/dex.yaml to v2.32.0
```

Bump image in examples/k8s/dex.yaml to v2.32.0

---

.github/workflows/artifacts.yaml

Comment uploading a tar with an image as an artifact.
It is flaky and required only if a maintainer wants to check the image.

Comment the flaky debugging stage

---

.github/workflows/ci.yaml
Dockerfile
go.mod
go.sum

https://go.dev/doc/devel/release
```release-note
Update Go 1.21
```

Bump Go 1.21

---

README.md

After [this commit](https://github.com/dexidp/dex/commit/6d55fe1c800819951eeece196bbfc67fdf037ae0), support for refresh tokens has been added to the OpenShift connector. However, it was missed in this commit to also adjust the README to specify that.
```release-note
```

Mark token refresh as supported by OpenShift connector

---

.golangci.yml
Makefile

Bump golangci-lint 1.55.2

---

Dockerfile

This resolves https://github.com/dexidp/dex/issues/3233
```release-note
```

Patch gomplate to v3.11.6

---

Dockerfile

Related discussion https://github.com/dexidp/dex/discussions/3272

Bump gomplate to v3.11.7

---

.github/workflows/checks.yaml
.github/workflows/ci.yaml
Dockerfile

Images:
* builder
* stager
* gomplate
* base alpine
* base distroless
Actions:
* check required labels
* kind
To be in line with other dependencies.

Pin actions and container image dependencies

---

.github/dependabot.yaml

Add dependabot for example app
As of today, only security updates are provided (and with the wrong label).

Add dependabot for example app

---

Dockerfile

Propagate the image version from the image metadata annotations to Dex. It will help us to avoid depending on git analysis by the script and take the date from the CI system.
Closes https://github.com/dexidp/dex/issues/3180

Propagate Dex version from build args

---

.github/workflows/checks.yaml

Explicitly set permissions to secure the CI

Set read only permissions to the check job

---

connector/ldap/ldap.go
storage/kubernetes/client.go

Backport fixes to v2.39.1

---

connector/saml/saml.go
storage/ent/db/ent.go

chore: fix function names in comment

---

.github/workflows/artifacts.yaml

Look for secrets before leaping
All forks get failures when they update `master` unless they have valid secrets set (and most won't...)
```release-note
NONE
```

Look for secrets before using them

---

.github/workflows/artifacts.yaml

Revert the change introduced in previous PRs. For each PR, we want to build images to check that the build passes successfully.

Build containers for branches

---

.github/workflows/artifacts.yaml

container-image -> container-images

Fix trivy scanning job

---

README.md

This PR fixes a broken link for `What's new in v2` in README.
Updates README with broken link fix.

README: Fix the broken link to v2 page

---

api/v2/go.mod
api/v2/go.sum

FIx CVE before Dex v2.41

---

README.md

This PR updates README (Development Section) to add a link to the official release documentation (https://dexidp.io/docs/development/releases/) to make it easier for developers to find instructions on the release process.
Make it easier for developers to find instructions on the release process.
Thanks for your time and consideration!

Update README: Add a link to release process in Development section

---

.github/workflows/ci.yaml

The docker-compose script was deleted in
https://github.com/actions/runner-images/pull/10368

Migrate to docker compose plugin

---

go.mod
go.sum
storage/ent/db/authcode_query.go
storage/ent/db/authrequest_query.go
storage/ent/db/connector_query.go
storage/ent/db/devicerequest_query.go
storage/ent/db/devicetoken_query.go
storage/ent/db/ent.go
storage/ent/db/keys_query.go
storage/ent/db/oauth2client_query.go
storage/ent/db/offlinesession_query.go
storage/ent/db/password_query.go
storage/ent/db/refreshtoken_query.go
storage/ent/db/runtime/runtime.go

Dependency update
Open it manually because of code generation

Bump ent v0.14.0

---

connector/saml/saml.go

handle empty data to avoid panics
"Closes #1757"
None

saml connector: fix nil pointer PANIC on validate saml

---

.github/ISSUE_TEMPLATE/config.yml

Commit a98ab893c2791d683162886d36f212aaee92e902 moved the `README.md` file. This PR adjusts sources to changes.

fix: update enhancement proposal link

---

pkg/httpclient/httpclient.go
pkg/httpclient/httpclient_test.go

Allow to load certificates from bytes and strings
In cloud environments, for publically available values it is easier to specify the content of a public certificate in the config than mounting it to the container.

Support base64 encoded and PEM encoded certs

---

.github/workflows/artifacts.yaml

Cache trivy DB for a day
https://github.com/aquasecurity/trivy-action/pull/397

Fix trivydb TOOMANYREQUESTS error

---

.github/workflows/artifacts.yaml
.github/workflows/trivydb-cache.yaml

Populate trivydb cache on the beginning of each day
Jobs tend to fail because of the ghcr rate limit

Update trivydb cache on the begging of each day

---

README.md

Fix url for Atlassian Crowd connector documentation.
Link in README.md points to the error 404 page.

chore: fix url for crowd connector in README.md

---

Dockerfile

build(deps): bump gomplate from 4.0.1 to 4.3.0

---

.dockerignore

Results in a dirty build according to the embedded VCS information.
remove version controlled files from dockerignore
Trivy scan results in a weird application version and false positive alerts

fix: remove version controlled files from dockerignore

---

Dockerfile

Updates Gomplate to the latest version v4.3.3
This addresses a CVE in Go module `x/net`, specifically the HTML parser
- https://nvd.nist.gov/vuln/detail/CVE-2025-22872

Resolve CVE by updating gomplate to 4.3.3
